OWNERS
projects/aws/eks-anywhere/build/create_attribution.sh
projects/brancz/kube-rbac-proxy/build/create_attribution.sh
projects/fluxcd/flux2/build/create_attribution.sh
projects/fluxcd/helm-controller/build/create_attribution.sh
projects/fluxcd/kustomize-controller/build/create_attribution.sh
projects/fluxcd/notification-controller/build/create_attribution.sh
projects/fluxcd/source-controller/build/create_attribution.sh
projects/jetstack/cert-manager/build/create_attribution.sh
projects/kubernetes-sigs/cluster-api-provider-aws/build/create_attribution.sh
projects/kubernetes-sigs/cluster-api-provider-vsphere/build/create_attribution.sh
projects/kubernetes-sigs/cluster-api/build/create_attribution.sh
projects/kubernetes-sigs/cri-tools/build/create_attribution.sh
projects/kubernetes-sigs/etcdadm/build/create_attribution.sh
projects/kubernetes-sigs/kind/build/build-kind-base-image.sh
projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
projects/kubernetes-sigs/kind/build/build-kindnetd-image.sh
projects/kubernetes-sigs/kind/build/create_attribution.sh
projects/kubernetes-sigs/kind/images/base/kubeadm-override.sh
projects/kubernetes-sigs/kind/images/k8s.io/kubernetes/build/download-images.sh
projects/kubernetes-sigs/kind/images/k8s.io/kubernetes/build/run.sh
projects/kubernetes-sigs/kind/images/k8s.io/kubernetes/hack/print-workspace-status.sh
projects/kubernetes-sigs/vsphere-csi-driver/build/create_attribution.sh
projects/kubernetes/cloud-provider-vsphere/build/create_attribution.sh
projects/mrajashree/etcdadm-bootstrap-provider/build/create_attribution.sh
projects/mrajashree/etcdadm-controller/build/create_attribution.sh
projects/plunder-app/kube-vip/build/create_attribution.sh
projects/rancher/local-path-provisioner/build/create_attribution.sh
projects/vmware/govmomi/build/create_attribution.sh

Remove year from license header on files.

Remove year from license verbiage

---

README.md

This table is more for our tracking purposes and I feel the README looks much cleaner with it collapsed by default.

Collapse base image tracker table

---

projects/aws/eks-anywhere/Makefile

Use new variable that was defined for cluster-controller base image.

Fix build arg for base image

---

projects/kubernetes-sigs/cluster-api/patches/0027-capd-do-not-reconcile-machine-if-cluster-or-machine-is-paused.patch

All CAPI and CAPV controllers check for the paused annotation on the object
or if the cluster is paused before reconciling. This check was added in the capd
docker machine controller in v0.4: https://github.com/kubernetes-sigs/cluster-api/pull/4453/commits/ec3492800174af48377566ef100feb9cef12aec8
This commit backports the upstream commit to our fork for v0.3

Check if docker machine or cluster is paused before reconciling

---

projects/kubernetes-sigs/cluster-api/patches/0028-add-support-for-registry-mirror-for-bottlerocket.patch

https://github.com/aws/eks-anywhere/issues/98
Add CAPI patch to allow registry mirror configuration for bottlerocket
This patch is added to resolve this issue:  https://github.com/aws/eks-anywhere/issues/98
I also noticed there were two `0026` patches so I renamed one of them to `0027`.

Add capi patch for bottlerocket registry mirror support

---

projects/aws/bottlerocket-bootstrap/pkg/utils/userdata.go

Changes to convert file permissions as an octal integer. Originally we were converting to base 10 which assigned the wrong permissions.

Converting from string to base 8 integer

---

EKSD_LATEST_RELEASES

Cherry pick of #60 on release-0.1.
#60: bump to latest eks-d release
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
```release-note
```

Automated cherry pick of #60: bump to latest eks-d release

---

projects/aws/eks-anywhere/Makefile
projects/aws/eks-anywhere/build/fetch_binaries.sh
projects/aws/eks-anywhere/docker/linux/Dockerfile

part of https://github.com/aws/eks-anywhere/issues/239
Add `kubectl` binary to the eksa-diagnostic-collector image. 
This will allow us to use [`run`](https://troubleshoot.sh/docs/collect/run/) collectors for Troubleshoot to execute `kubectl` commands, specifically toward the goal of `describe`'ing our CRDs for analysis.

Add kubectl to collector image

---

projects/kubernetes-sigs/cluster-api/patches/0029-Fix-proxy-template-for-bottlerocket-bootstrap.patch

Bottlerocket expects no-proxy setting to be a comma-separated list
of strings. The proxy template was parsing the input no-proxy list
and converting it to a string. This commit changes the template to
get the desired format.
Current generated value of no-proxy: "[localhost 127.0.0.1]"
New generated value for no-proxy: ["localhost", "127.0.0.1"]

Fix proxy template for bottlerocket bootstrap

---

projects/cilium/cilium/manifests/cilium-eksa.yaml

rolloutCiliumPods will monitor the `cilium-config` config map which holds the Cilium configuration and will rollout cilium agent pods when there is a new change.

Adding rolloutCiliumPods to true

---

projects/aws/eks-anywhere-test/helm/eks-anywhere-test/templates/deployment.yaml

These checksums cause the deployment to be redeployed when a config map
or secret changes during a helm upgrade.
https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

eks-anywhere-test helm chart: Adds config and secret annotations

---

Common.mk

Making the clone URL region specific, instead of statically linked to us-west-2.

Common make - Clone URL should be region specific

---

build/lib/helm_build.sh

This works locally for me, so maybe....
The setup.sh copies over the ~/.docker/config.json and that is in the build spec for this project.

Fix helm push permissions

---

build/update-attribution-files/make_attribution.sh

These project-specific targets were removed so the script needs to be modified to support the change.

Fix attribution generation for Flux projects and CAPI

---

projects/kubernetes-sigs/cluster-api/CHECKSUMS
projects/kubernetes-sigs/cluster-api/patches/0031-Add-ability-to-configure-the-cert-manager-version-in.patch

This kind of backport of https://github.com/kubernetes-sigs/cluster-api/pull/4748 into `v0.3.x` codebase
It's not the exact same implementation but very similar: allow the user to specify (optional) the cert-manager version
With this implementation, `clusterctl` still uses the embed manifest but at least it gives us more control over the upgrade process

Add patch to be able to configure the cert-manager version in clusterctl

---

projects/cilium/cilium/build/create_manifests.sh
projects/fluxcd/source-controller/build/install_deps.sh
projects/kubernetes-sigs/image-builder/build/setup_bottlerocket.sh
projects/kubernetes-sigs/image-builder/buildspecs/build-1-20-ubuntu-ova.yml
projects/kubernetes-sigs/image-builder/buildspecs/build-1-21-ubuntu-ova.yml

Removing yum installs of packages that are already on the builder-base image.

Remove redundant yum package installation

---

build/update-attribution-files/create_pr.sh

This corresponds to the secret key in the postsubmits cluster.
[Reference](https://github.com/aws/eks-distro-build-tooling/blob/main/pr-scripts/create_pr.sh#L95)

Fix filepath for mounted SSH key secret

---

build/lib/setup.sh
projects/kubernetes-sigs/kind/buildspec.yml
release/staging-build.yml

This PR adds a flag to the setup script to setup QEMU cross-platform emulation support. This will enable ARM64 builds for certain projects in CodeBuild.
/hold

Install QEMU during build setup

---

projects/cilium/cilium/build/create_manifests.sh
projects/cilium/cilium/expected_artifacts

Path is `projects/cilium/cilium/latest/manifests/cilium...`

Copy top-level manifests folder when pushing to S3

---

Common.mk
projects/fluxcd/helm-controller/buildspec.yml
projects/fluxcd/kustomize-controller/buildspec.yml
projects/fluxcd/notification-controller/buildspec.yml
projects/fluxcd/source-controller/buildspec.yml
projects/jetstack/cert-manager/buildspec.yml
projects/replicatedhq/troubleshoot/buildspec.yml

Fixes Codebuild looking for tarballs when uploading artifacts.

Make buildspecs consistent, add artifacts upload target to filter

---

projects/aws/eks-anywhere/Makefile

This overrides the default name we set using the org and repository name.

Override image component for diagnostic collector

---

Common.mk

This will prevent release branch specific calls in upload-artifacts. 

Build S3 artifacts in release make target

---

projects/aws/bottlerocket-bootstrap/Makefile

The image name is just `bottlerocket-bootstrap`

Override image component for Bottlerocket bootstrap image

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
projects/kubernetes-sigs/image-builder/packer/config/additional_components.json.tmpl
projects/kubernetes-sigs/image-builder/packer/config/validate_goss_inline_vars.json.tmpl
projects/kubernetes-sigs/image-builder/patches/0007-additional-eks-specific-goss-validations.patch

- Use pause.tar to pull in previous version pause image to make kubeadm init happy instead of pulling from ecr which will sometimes timeout on ssl handshake
- Use crictl sha256 file that now exists instead of generating it to avoid crictl building while image-builder and breaking checksum validation
- Fix goss validation due to change in version on kube binaries in latest eks-d releases

image-builder: improve ova built stability

---

projects/kubernetes-sigs/image-builder/Makefile

Enabling logging for packer when performing OVA builds.

Enable packer logs during OVA build

---

projects/kubernetes-sigs/image-builder/Makefile

Fixing these errors
```bash
vsphere: <iso> already exists, you can use -force flag to destroy it: <nil>
```

Force-delete existing VMs of same name during OVA build

---

projects/kubernetes-sigs/kind/buildspec.yml

If run in the foreground, we won't get back to the Codebuild shell context.

Run local registry container in detached mode

---

projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
projects/kubernetes-sigs/kind/images/node/Dockerfile

e2e presubmits are currently failing because the etcdadm binary in the amd64 kind image is actually the arm64 binary...

kind: use proper etcdadm arch binary

---

Common.mk
build/lib/docker/linux/useradd/Dockerfile
projects/fluxcd/helm-controller/Makefile
projects/fluxcd/helm-controller/docker/linux/Dockerfile
projects/fluxcd/kustomize-controller/Makefile
projects/fluxcd/kustomize-controller/docker/linux/Dockerfile
projects/fluxcd/notification-controller/Makefile
projects/fluxcd/notification-controller/docker/linux/Dockerfile
projects/fluxcd/source-controller/Makefile
projects/fluxcd/source-controller/docker/linux/Dockerfile
projects/jetstack/cert-manager/Makefile
projects/jetstack/cert-manager/docker/linux/cert-manager-acmesolver/Dockerfile
projects/jetstack/cert-manager/docker/linux/cert-manager-cainjector/Dockerfile
projects/jetstack/cert-manager/docker/linux/cert-manager-controller/Dockerfile

There are a few container images where we add new users.  This standardizes that to a common target in Common.mk.  This should also help with reproducibility of container images using the buildkitd inline cache option.

move adding users/groups to container image to common

---

build/update-attribution-files/create_pr.sh

From time to time the vsphere-provider presubmit will fail due to the dry run of attribution generation.  This is due to the branch already existing when trying to create it.  This changes to use -B which will create or reset.

create-pr: handle dry-run with multiple changes

---

Common.mk
build/lib/common.sh
build/lib/upload_artifacts.sh
build/update-attribution-files/create_pr.sh

Run artifacts upload in dry run mode locally and in presubmits to validate upload S3 paths.

Run artifacts upload in dry-run mode outside of Codebuild

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/expected_artifacts

Packer logging is enabled and the log file is also uploaded to S3, and is one of the expected artifacts.

Add packer log to list of expected artifacts

---

projects/kubernetes-sigs/etcdadm/CHECKSUMS
projects/kubernetes-sigs/etcdadm/patches/0011-Add-support-for-cipher-suites.patch

Added support for `--cipher-suites` flag for etcdadm. Used template FuncMap to pass in a `strings.Join` function to display as a comma delimited list. An empty value for `ETCD_CIPHER_SUITES` is the same as it not being specified, so it would default to using an auto-populated list from go as it does today.

Add support for cipher suites in etcdadm

---

Common.mk
build/lib/helm_build.sh

Follow up to #226, an attempt to improve the Attribution file handling.  Since we want to include the attribution in the helm chart, we can copy it into the output dir before calling helm just like we do for images.

eks-anywhere-test: cleanup attribution handling for helm chart

---

projects/mrajashree/etcdadm-bootstrap-provider/Makefile
projects/mrajashree/etcdadm-bootstrap-provider/expected_artifacts
projects/mrajashree/etcdadm-controller/Makefile
projects/mrajashree/etcdadm-controller/expected_artifacts

These were removed by mistake in a previous commit.

Mark etcdadm bootstrap provider and controller as producing S3 artifacts

---

Common.mk
UPSTREAM_PROJECTS.yaml
build/lib/common.sh

Ensuring OVAs go to S3 folders named after release-branches.

Fix OVA S3 upload destinations

---

Common.mk
UPSTREAM_PROJECTS.yaml
build/lib/common.sh
build/lib/fetch_binaries.sh
projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
projects/kubernetes-sigs/kind/Makefile
projects/kubernetes-sigs/kind/build/base-image-build-args.sh

Cherry pick of #240 on v1beta1-experimental.
#240: fetch-binaries: use latest tag when deciding s3 folder
For details on the cherry pick process, see the [cherry pick requests](https://github.com/aws/eks-anywhere-build-tooling/tree/main/docs/development/cherry-picks.md) page.
```release-note
```

Automated cherry pick of #240: fetch-binaries: use latest tag when deciding s3 folder

---

projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh

This was causing the crictl URL to be suffixed with a parenthesis at the end.

Remove trailing parenthesis in script

---

projects/kubernetes-sigs/etcdadm/CHECKSUMS
projects/kubernetes-sigs/etcdadm/Makefile
projects/kubernetes-sigs/etcdadm/README.md
projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh

We werent passing the expected ldflags to the build so the version subcommand would return nonsense.  This adds the flags using our common version.sh which roughly matches upstream kube projects.

etcdadm: fix version by setting proper ldflags

---

projects/jetstack/cert-manager/Makefile
projects/jetstack/cert-manager/docker/linux/cert-manager-webhook/Dockerfile

Cert-manager v1.5.3 [enables runAsNonRoot by default](https://github.com/jetstack/cert-manager/pull/4036/files). Cert-manager
webhook container runs as root and fails to get created. This
commit adds non root user to webhook container image.

Add user to cert-manager webhook container image

---

build/lib/common.sh

go-licenses is pretty conservative about copying code for projects with certain licenses since they "could" have been modified.  We know this is not the case since we are calling go mod vendor to pull from upstream before building.

licenses: no need to keep code

---

EKSD_LATEST_RELEASES

Cherry pick of #288 on release-0.6.
#288: bump eks-d release numbers
For details on the cherry pick process, see the [cherry pick requests](https://github.com/aws/eks-anywhere-build-tooling/tree/main/docs/development/cherry-picks.md) page.
```release-note
```

Automated cherry pick of #288: bump eks-d release numbers

---

EKSD_LATEST_RELEASES

Bumping up to corresponding Kubernetes versions in the releases file

Bump kube versions in EKS-D releases list

---

build/lib/common.sh

Cherry pick of #286 on release-0.6.
#286: licenses: no need to keep code
For details on the cherry pick process, see the [cherry pick requests](https://github.com/aws/eks-anywhere-build-tooling/tree/main/docs/development/cherry-picks.md) page.
```release-note
```

Automated cherry pick of #286: licenses: no need to keep code

---

Makefile
build/lib/generate_help_body.sh
build/update-attribution-files/make_attribution.sh

Should fix yesterdays failure due to a difference in bash on builder-base and mac.  This also
- separates checksum + attribution generation
- moves create_pr to be after each part (help, attribution, help) the script should still work for this and this would allow for anything that passes to still get checked in vs if one fails they all fail.

fix help generation on builder base

---

build/lib/generate_help_body.sh

Help in https://github.com/aws/eks-anywhere-build-tooling/pull/301 had extra make[2] output in the help files.  This should take care of that.

avoid make output in generated help

---

build/update-attribution-files/create_pr.sh

We havent been updating KINDNETD_ATTRIBUTION.txt when it needed. This also avoids the error when trying to added ignored files by using the check-ignore trick used for the Makefile git add.

handle nonstandard attribution file names and ignored files

---

Common.mk
build/lib/helm_push.sh

Change the helm build so
* Push helm chart to IMAGE_REPO (build doesn't have perms to get pub repo)
* Do not overlay the value of DOCKER_CONFIG
* Clean up the clean up

Use whatever repo we are supposed to and docker config.json

---

Common.mk
build/lib/common.sh
build/lib/helm_build.sh
projects/jetstack/cert-manager/Makefile
projects/jetstack/cert-manager/helm/patches/0003-Activate-digests-with-templates.patch
projects/jetstack/cert-manager/helm/sedfile.template

- Gathering licenses for helm charts and putting them in containers didn't make much sense, so I've reverted that.
- Gathered licenses just for the helm chart and put them in the helm chart. (works for cert-manager and flux)
- Removed attribute file from helm chart since that is really for the container image

Chart licenses

---

projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0003-Add-templateOverride-for-default-CAPT-template.patch

This patch adds a templateOverride field under `TinkerbellMachineTemplate`
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: TinkerbellMachineTemplate
metadata:
name: abhnvp-tinkerbell-worker-a
namespace: eksa-system
spec:
template:
spec:
templateOverride: |
<template to override the default CAPT template goes here>
```
If the templateOverride isn't set, the default CAPT template is used.

Add CAPT patch to override the default workflow template

---

build/lib/common.sh
build/lib/fetch_binaries.sh

This function will make the job sleep for 20 mins or until the project tarball is available under `latest/`, whichever is earlier.

Wait until tarball is available under latest before downloading

---

build/update-attribution-files/create_pr.sh

Isolates changes to Help.mk to their own branch.

Push generated Makefile changes to appropriately named branch

---

Common.mk

By default make's shell is sh, which doesn't support flags like -o pipefail

Set bash as shell for make in common makefile

---

projects/cilium/cilium/README.md

Add instruction to run make generate when updating Cilium

---

projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0004-Modifying-BMC-CRD-to-read-from-Secret.patch
projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0005-Adding-PBNJ-PowerAction-to-BMC-controller.patch
projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0006-Adding-PBNJ-BootDevice-to-BMC-CRD-and-client.patch
projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0007-Adding-BmcRef-to-hardware-and-PowerOn-machine.patch
projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0008-Deprovision-hardware-after-hardware-release.patch

The patches involve changes to CAPT for enabling Hardware-BMC correspondence. 
- When a hardware is made part of the cluster, the `bmcRef` object is patched to perform powerOn.
- When cluster is deleted and hardware is made available . `bmcRef` object is patched to perform Power Reset and setting PXE boot.
- The BMC credentials are now referenced from a k8s secret.
The commits are the top 5 commits on my fork
[pokearu/cluster-api-provider-tinkerbell](https://github.com/pokearu/cluster-api-provider-tinkerbell/commits/capt-pbnj-integration
)

Patches for CAPT BMC-Hardware Power and Deprovision

---

projects/tinkerbell/tink/CHECKSUMS
projects/tinkerbell/tink/Help.mk
projects/tinkerbell/tink/Makefile
projects/tinkerbell/tink/docker/linux/tink-cli/Dockerfile

Changed tink-cli binary name to tink

changed tink-cli binary name to tink

---

projects/kubernetes-sigs/cluster-api/build/create_manifests.sh

capd controller doesn't support namespace arg. 

Remove command to set unsupported namespace flag in docker provider

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/build_raw_image.sh

Avoid creating source directories recursively on destination when using `rsync`.

Avoid creating source directories on destination during rsync copy

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/build_raw_image.sh

Ensures unique EC2 keypair names during build jobs.

Ensure EC2 keys get created with unique name to avoid collisions

---

build/lib/validate_artifacts.sh
projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/build_raw_image.sh

Putting packer log under ova folder.

Put packer log in expected artifacts path

---

projects/jetstack/cert-manager/buildspec.yml
projects/redis/redis/buildspec.yml

This will enable the shell script `build/lib/helm_push.sh` to push the built helm charts to gallery, giving us a central location for testing.

Adding Image repo var to buildspec to push helm to gallery on builds.

---

projects/kubernetes-sigs/image-builder/build/build_raw_image.sh

This prevents an index value of `0` from being passed to `cut`.

Make subnet array one-indexed

---

build/lib/sign_file.sh

This will be a script used in Makefile's in the future when we are signing bundle's for addOns. This can leverage the KMS signingKey added from CDK in each build account.

Adding shell script to sign files for pipelines

---

projects/aws/eks-anywhere-build-tooling/Makefile
projects/aws/eks-anywhere-build-tooling/build/organize_binaries.sh

The previous PR (https://github.com/aws/eks-anywhere-build-tooling/pull/370) added the cloudmonkey project to be built in eks-a infrastructure. This PR enables the CLI to be available in the cli-tools Docker image.
`make generate` succeeded

Enabling cmk build for cli-tools

---

projects/tinkerbell/pbnj/Makefile
projects/tinkerbell/pbnj/docker/linux/Dockerfile

Cloning outside Docker build since we don't have AWS access inside docker build (to clone from CodeCommit).

Clone ipmitool repo outside docker build stage

---

Common.mk
projects/kubernetes-sigs/kind/Help.mk
projects/kubernetes-sigs/kind/Makefile
projects/kubernetes-sigs/kind/patches/0001-Switch-to-AL2-base-image-for-node-image.patch

https://github.com/aws/eks-anywhere/issues/1159
Per the ticket above when creating CAPD clusters there is a `agetty` process running which is attached (?) to the tty1 interface, but since it's in a container it's not really able to attach(?).  According to an (old) [issue](https://github.com/moby/moby/issues/4040) logged against docker this has to do something with privileged containers using `init` as their entrypoint, which the kind image def does.  Looking at some of the attached tickets there appears to be two approaches to solving the issue:
- masking, or removing, the getty@ttty1 service in /etc/systemd/system
- replacing `/bin/agetty` with `/bin/true`
This [issue](https://github.com/voxpupuli/beaker-hostgenerator/pull/138) went …

kind: fix high cpu agetty processes

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/buildspecs/build-1-20-ubuntu-ami.yml
projects/kubernetes-sigs/image-builder/buildspecs/build-1-21-ubuntu-ami.yml

Part of https://github.com/aws/eks-anywhere/issues/1165
This is the minimum changes to make this work (I think)
Once everything is working correctly, we'll refactor this to use the new build patterns (`release IMAGE_FORMAT=*`, etc.)

Fix ubuntu ami builds to work with new make targets

---

projects/kubernetes-sigs/kind/Makefile
projects/kubernetes-sigs/kind/expected_artifacts

For consistency with other projects building manifests.

Move kindnetd manifest to versioned folder

---

projects/tinkerbell/boots/Makefile

Attribution automation job is failing due to boots project. Adding ipxe copy to GATHER_LICENSES_TARGETS target.

Adding GATHER_LICENSES_TARGETS for ipxe copy target

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/ansible/roles/load_additional_files/defaults/main.yml
projects/kubernetes-sigs/image-builder/ansible/roles/load_additional_files/tasks/files.yml
projects/kubernetes-sigs/image-builder/ansible/roles/load_additional_files/tasks/main.yml
projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap-after.sh
projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap.sh
projects/kubernetes-sigs/image-builder/packer/ami/additional_files/generate-kube-vip-manifest.sh
projects/kubernetes-sigs/image-builder/packer/ami/ansible_extra_vars.yaml
projects/kubernetes-sigs/image-builder/packer/ami/packer.json

Part of https://github.com/aws/eks-anywhere/issues/1165
This adds 3 extra scripts that the Snow CAPI provider uses for node bootstrap.
I managed to do it without patching image-builder by:
* Creating a new ansible role and passing it to `image-builder` through [`custom_role_names`](https://image-builder.sigs.k8s.io/capi/capi.html#customization). This plugs it into the main packer build, right after the `load_additional_components` role (after provider and kubernetes roles have already been executed). This role simply iterates over a list of files and copies them in the designated destination paths.
* Creating a yaml file listing all the files we want to copy to the ami and passing it to ansible with `ansible_user_vars`.
Note: I'm exporting `BUILDER_ROOT` (it's …

Extra scripts for Snow provider in ubuntu ami

---

projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0009-Remove-requirement-for-machine.Spec.Version.patch

The CAPI machine crds for external etcd currently do not set `machine.Spec.Version` but CAPT makes it a required field. Etcd machines fail to reconcile as a result.
This patch removes this requirement allowing us to use external etcd with CAPT.

Add CAPT patch to remove requirement on machine.Spec.Version

---

projects/tinkerbell/pbnj/docker/linux/Dockerfile

pbnj: fix lanplus by adding openssl-dev when building ipmitool

---

projects/tinkerbell/pbnj/docker/linux/Dockerfile

This will make sure everything make install puts in place, is in the resulting image, including the license.

pbnj: use destdir when make installing impitool

---

projects/tinkerbell/hook/Makefile
projects/tinkerbell/hook/expected_artifacts

Since we set `SIMPLE_CREATE_TARBALLS=false` we need to create the artifacts path to copy the final OSIE files.

Creating ARTIFACTS_PATH before cp

---

projects/tinkerbell/hook/Makefile
projects/tinkerbell/hook/README.md

The release on `tinkerbell/hook` uses kernel `5.10.57`

Using kernel version 5.10.57

---

projects/tinkerbell/tink/Makefile
projects/tinkerbell/tink/docker/linux/tink-cli/Dockerfile
projects/tinkerbell/tink/docker/linux/tink-server/Dockerfile

`tink-server` requires wget to perform health checks.
`tink-cli` needs sleep to be a long running container.

Adding wget and sleep to tink images

---

projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap-after.sh
projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap.sh
projects/kubernetes-sigs/image-builder/packer/ami/additional_files/generate-kube-vip-manifest.sh

We don't want this image harcoded, we want to be able to pass it when bootstrapping clusters.
These changes mean that when generating the CAPI [template](https://github.com/aws/cluster-api-provider-aws-snow/blob/main/snow-cluster.yaml), we will need to change the kubeadm pre and post commands to include the image. Example:
[Control plane](https://github.com/aws/cluster-api-provider-aws-snow/blob/main/snow-cluster.yaml#L68-L71)
```yaml
preKubeadmCommands:
- /etc/eks/bootstrap.sh 192.168.1.111
postKubeadmCommands:
- /etc/eks/bootstrap-after.sh 192.168.1.111
```
```yaml
preKubeadmCommands:
- /etc/eks/bootstrap.sh public.ecr.aws/eks-anywhere/plunder-app/kube-vip:v0.3.7-eks-a-1 192.168.1.111
postKubeadmCommands:
- /etc/eks/bootstrap-after.sh …
```

Accept kube-vip image as input to bootstrap scripts in Snow ami

---

projects/tinkerbell/tink/docker/linux/tink-server/Dockerfile

Looks like wget needed `pcre` to run.

Adding back dependency pcre for wget

---

buildspec.yml

Each project folder has a buildspec, but they're all identical. So we should replace them with a single one at root. This change will be done as a blue-green deployment.

Add common buildspec for all projects

---

projects/aws/cluster-api-provider-aws-snow/manifests/infrastructure-components.yaml

This is a (hopefully) temporary workaround till we have public images for Snow.

Add image pull secrets to CAPAS controller deployment

---

projects/aws/eks-anywhere-test/buildspec.yml
projects/jetstack/cert-manager/buildspec.yml
projects/redis/redis/buildspec.yml

We will instead use a promotion process to push from private to public ECR. 

Remove ECR public env var from buildspecs

---

release/staging-build.yml

this caused the staging release to fail; removing as it should not be needed

remove openssl install, it's already on the base image for codebuild

---

Common.mk
build/lib/helm_copy.sh
build/lib/helm_replace.sh

I created this PR for two reasons
1. To address this concern https://github.com/aws/eks-anywhere-build-tooling/pull/440/files#r809427929 too many parameters to the helm_build.sh file. This doesn't completely resolve that, but it is a step to resolve that.
2. Break up the steps of helm/build so helm/push can get the shasums of the container images and helm/build can skip that step.

Break up helm build into components

---

projects/kubernetes-sigs/etcdadm/CHECKSUMS
projects/kubernetes-sigs/etcdadm/patches/0012-Allow-using-multiple-endpoints-for-etcd-client.patch

During etcd cluster creation, etcdadm first creates a single member etcd cluster through the `etcdadm init` command, and then the rest of the members can join the cluster using the `etcdadm join <endpoint>` command.
If this first member gets deleted, we need to decide on a new endpoint to be used for the join command. Instead if we pass in all etcd members to the join command we won't need to check if one of them is unavailable.
This endpoint is only used within etcdadm to generate the etcd client. Etcd client can be generated for multiple endpoints. This commit modifies the etcd client generation to use as many endpoints are passed in. 
*Testing*
Built etcdadm binary, and used it through the etcdadm-bootstrap-provider's logic to [install …

Add etcdadm patch to accept multiple endpoints

---

projects/kubernetes-sigs/kind/build/build-kind-node-image.sh

In the newest eks-d releases the version information that is embedded into the binaries has changed slightly.  This should cover both the older version style and the new.
/hold

kind: fix kubeadm version validation

---

EKSD_LATEST_RELEASES

Should be the last dev release of 1.22

eksd: bump to 1.22 dev release 6

---

projects/kubernetes-sigs/image-builder/packer/ami/packer.json

Until we don't have the option to dynamically set the VM disk size, this
is the only way to have enough disk space to download container images.

Increase eks-d AMI sice to 25GB

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/README.md
projects/kubernetes-sigs/image-builder/build/build_qemu_rhel_local.sh

This PR adds a make target to build a RHEL based qcow2 image for kvm/qemu locally. Also adds readme instructions for setting up the builder machine, and running the image build process.

Local RHEL Image Builder for Qemu

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_OVA_RELEASES

Bottlerocket released their latest ova with 1.22 support 🎉 
Also added latest BR version for the other versions

Add 1.22 builds for Bottlerocket

---

projects/aws/cluster-api-provider-aws-snow/Makefile

Fix CAPAS manager image name

---

projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0010-Adding-mutex-to-lock-hardware-selection.patch
projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0011-Temporary-comment-error-return.patch

Adding patches to CAPT for
1. Mutex lock for allocating hardware to machines in controller
2. Temporarily commenting error return for set boot dev

CAPT patches mutex lock and error return

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/export-ami-to-s3.sh
projects/kubernetes-sigs/image-builder/packer/ami/packer.json

This uses the AWS export image service to convert from AMI to raw
format. It then copies the generated raw image into the 'latest' folder
for easy consumption.
The export service creates the image in somewhere like `projects/kubernetes-sigs/image-builder/1-21/ami/d0e81f009fd0268afdb1525ff6e67335cc5ad452/kubernetes-1-21-eks-9-export-ami-0c41703223e6e598e.raw` and after the exporting is done we copy it to `projects/kubernetes-sigs/image-builder/1-21/ami/latest/ubuntu.raw` (overwriting whatever was the latest build).

Export EKS-D AMI to raw format after build

---

projects/kubernetes-sigs/cluster-api-provider-vsphere/CHECKSUMS
projects/kubernetes-sigs/cluster-api-provider-vsphere/patches/0003-set-user-agent-for-vsphere-api-calls.patch
projects/kubernetes/cloud-provider-vsphere/1-20/CHECKSUMS
projects/kubernetes/cloud-provider-vsphere/1-20/patches/0001-set-user-agent-for-vsphere-api-calls.patch
projects/kubernetes/cloud-provider-vsphere/1-21/CHECKSUMS
projects/kubernetes/cloud-provider-vsphere/1-21/patches/0001-set-user-agent-for-vsphere-api-calls.patch
projects/kubernetes/cloud-provider-vsphere/1-22/CHECKSUMS
projects/kubernetes/cloud-provider-vsphere/1-22/patches/0001-set-user-agent-for-vsphere-api-calls.patch

While trying to debug vsphere connections in CI we are seeing lots of requests with the generic go-client user agent. The [csi-driver](https://github.com/kubernetes-sigs/vsphere-csi-driver/blob/v2.2.0/pkg/common/cns-lib/vsphere/virtualcenter.go#L155) and gov properly set a useragent. This patches capv and cpi to set a user agent on the vm25client as well. As a note, capv is setting the useragent on some other session in their code, but that does not seem to come thru and it is after the login call.
Since we have patch directories for the specific versions of cpi, i went ahead and hardcoded the version in the source. I think longer term we could change that to be more dynamic.
By submitting this pull request, I confirm that you can use, …

capv + cpi: add user agents to vcenter api calls

---

Common.mk
build/lib/buildkit.sh

Call buildctl prune between image builds to avoid space issues in presubmit.
Only running prune during presubmit, it would probably be fine to always run it, but going this route to limit the risk of any issues.

Fix space issues in harbor presubmit

---

projects/helm/helm/CHECKSUMS
projects/helm/helm/patches/0001-Push-to-OCI-insecure-registry.patch

*Issue #, if available:* https://github.com/helm/helm/issues/6324
Adding commits from this upstream PR: https://github.com/helm/helm/pull/10408/commits
Tested locally and helm pull/push works as expected

Add helm patch to allow push to insecure OCI registry

---

release/staging-build.yml

CLI tools depends on tink CLI.

Build tink project as prequisite to CLI tools

---

build/lib/helm_push.sh
build/lib/helm_require.sh
projects/aws/eks-anywhere-test/eks-anywhere-test/Chart.yaml

In commit e09f316 we allowed helm charts to use semantic versioning,
however we made the wrong version semantic. It's not appVersion that
matters, but rather version. This also changes the generated filename.
I also escaped a shell echo that failed when it tried to run on my
machine.

Tweak helm chart semantic version generation.

---

projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0012-Update-tinkerbell-hardware-state-through-CAPT.patch

Patch CAPT to change the Tinkerbell hardware state in the following way:
* set it to `in_use` if the hardware has the `ownerName` label and has a corresponding workflow which is either running or successful
* set it to `provisioning` if the hardware does not have the `ownerName` label. In this case, CAPT also resets the hardware `userdata`
It also modifies the CAPT hardware state in the following way:
* If the hardware does not have the `ownerName` label, set `state` to `Available`
* If the hardware does have `ownerName` label and 
* hardware either doesn't have a corresponding workflow or has a workflow that's pending, then the `state` is set to `Pending`
* hardware has a workflow that's running, then the `state` is set to `Running`
* hardware has a workflow …

Add CAPT patch to update hardware state

---

projects/kubernetes-sigs/image-builder/Makefile

This is causing Ubuntu and RHEL to be built in the same pipeline. We need better logic around this.

Remove RHEL builds in CI

---

projects/tinkerbell/hook/docker/linux/tink-docker/Dockerfile

tink-docker has a reboot watch, that calls `/sbin/reboot`.  `reboot` is a symlnk to `systemctl` and its dependencies.
Hence installing `systemd` fully on tink-docker.

Install reboot in tink-docker

---

projects/tinkerbell/hook/docker/linux/tink-docker/Dockerfile

We need the reboot call from busybox binary instead of the systemctl. This enables reboots without an init daemon.

Adding busybox reboot to tink-docker

---

projects/tinkerbell/cluster-api-provider-tinkerbell/ATTRIBUTION.txt
projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0013-Updating-PBNJ-commit-version.patch

CAPT was using an older version of PBNJ that had a different proto API.
Update fixes issues with wrong API calls being triggered.

Adding CAPT patch to update PBNJ version

---

projects/kubernetes-sigs/image-builder/packer/ami/additional_files/generate-kube-vip-manifest.sh

Updating kube-vip manifest for AMIs to the one expected by the latest version
Relevant PRs:
https://github.com/aws/eks-anywhere-build-tooling/pull/534
https://github.com/aws/eks-anywhere/pull/1358

Update kube-vip manifest for AMIs

---

build/lib/validate_artifacts.sh
projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/expected_artifacts_ova
projects/kubernetes-sigs/image-builder/expected_artifacts_ova_bottlerocket

/hold
Putting OS images into OS-based folders.

Fix upload paths for imagebuilder targets

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh

Placing the packer config files at the appropriate location where packer builds look for them. Fixes image builds looking for missing files.

Put packer config files at the appropriate location where packer builds look for them

---

projects/kubernetes-sigs/image-builder/Makefile

This puts the packer log in a subfolder based on the OS - Ubuntu, RHEL, etc.

Fix packer log path for OVA builds

---

projects/kubernetes-sigs/cluster-api/patches/0001-Adding-capi-support-for-Bottlerocket.patch
projects/kubernetes-sigs/cluster-api/patches/0002-Add-unstacked-etcd-support.patch
projects/kubernetes-sigs/cluster-api/patches/0003-Unstacked-etcd-and-controlplane-upgrade.patch
projects/kubernetes-sigs/cluster-api/patches/0004-Patch-config-path-in-kubevip-manifest-for-kubeadm-co.patch
projects/kubernetes-sigs/cluster-api/patches/0005-Make-pause-and-bottlerocket-bootstrap-images-updatab.patch
projects/kubernetes-sigs/cluster-api/patches/0006-add-support-for-registry-mirror-for-bottlerocket.patch
projects/kubernetes-sigs/cluster-api/patches/0007-Fix-proxy-template-for-bottlerocket-bootstrap.patch
projects/kubernetes-sigs/cluster-api/patches/0008-Update-core-conversion-spoke-versions.patch
projects/kubernetes-sigs/cluster-api/patches/0009-Add-bottlerocket-changes-to-capbk-v1alpha4-api.patch
projects/kubernetes-sigs/cluster-api/patches/0010-Update-capbk-converions-spoke-version.patch
projects/kubernetes-sigs/cluster-api/patches/0011-Add-generated-manifest-changes-for-KCP.patch
projects/kubernetes-sigs/cluster-api/patches/0012-Add-status.version-to-list-of-fields-to-ignore-for-u.patch
projects/kubernetes-sigs/cluster-api/patches/0013-Add-node-labels-support-for-bottlerocket.patch
projects/kubernetes-sigs/cluster-api/patches/0014-Support-worker-node-taints.patch
projects/kubernetes-sigs/cluster-api/patches/0015-support-bottle-rocket-control-plane-taints.patch
projects/kubernetes-sigs/cluster-api/patches/0016-Support-configuring-bottlerocket-control-container-u.patch
projects/kubernetes-sigs/cluster-api/patches/0017-update-coredns-corefile-migration-to-support-1.8.7.patch
projects/kubernetes-sigs/cluster-api/patches/0018-Change-format-for-storing-etcd-machine-address.patch

Updates the patch adding BR support to include `bottlerocket` in the enum for `Format`. This got removed accidentally when updating capi tag to 1.1.3
*Testing*:
Generated components.yaml for clusterApi, controlplane and bootstrap. Used these components.yaml files in the latest bundle-release.yaml. Created BR cluster with bundles-override flag pointing to the modified bundle-release.yaml
```
kustomize build config/default | ./hack/tools/bin/envsubst > capi.yaml
➜  cluster-api git:(eksa-113) ✗ diff capi.yaml core-components.yaml
9844c9844,9845
<         - --feature-gates=MachinePool=false,ClusterResourceSet=false,ClusterTopology=false
---
>         - --feature-gates=MachinePool=${EXP_MACHINE_POOL:=false},ClusterResourceSet=${EXP_CLUSTER_RESOURCE_SET:=false},ClusterT …
```

Fix kcp components.yaml to include BR

---

projects/kubernetes-sigs/image-builder/patches/0009-Add-support-for-RHEL-8-OVA-builds.patch

We need to add rhel-8 to RHEL_VERSIONS list to be able to call the new RHEL 8 ova target.

Add RHEL 8 to RHEL versions list in image-builder Makefile

---

projects/kubernetes-sigs/image-builder/patches/0009-Add-support-for-RHEL-8-OVA-builds.patch

Using S3 URL for downloading RHEL ISO for image builds.

Use S3 URL for downloading RHEL ISO

---

projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0014-When-checking-availability-while-picking-hardware-to.patch

when assigning hardware to machines, along with checking the ownerName label

Check the 'State' field of Hardware object is set to 'HardwareAvailable"

---

Common.mk

Small ordering change to build targets. Most builds end up using the attribution files in the images or tarball builds.  By running the generation and deleting the checked in file first will help ensure we are still building to the correct filename.

generate attribution before building images

---

projects/replicatedhq/troubleshoot/Makefile

With the recent changes to the go mod handling and changing some of the common.mk targets to be % based, the ordering got shifted a bit. The normal build target is working fine, but when running gather-licenses directly there is an issue, which is breaking the attribution job.
This target should have always been dependent on the GO_MOD_DOWNLOAD_TARGETS, most of the other projects in this repo were already handling this proper except for troubleshoot. This was previously working because the GATHER_LICENSES_TARGETS which we were adding this as a pre-req for matched exactly the target in Common.mk, ie there were % usage. Now that the gather licenses target is % based, the one in the project …

troubleshoot: fix gather-licenses target

---

projects/aws/eks-anywhere-build-tooling/Makefile
projects/aws/eks-anywhere-build-tooling/build/organize_binaries.sh

We havent support capa in a while and arent updating it anymore.  This shouldnt be necessary in the cli tools image any more.

cli-tools: remove clusterawsadm

---

build/lib/fetch_binaries.sh
projects/aws/eks-anywhere-build-tooling/Makefile

We want to use tink-cli image from a previous commit instead of the latest one because of some of the breaking changes that went in to tink-cli because of the kubification. This is needed to temporarily allow the eks-anywhere workflows to still succeed while we work on updating it to account for kubification changes.

Specify commit for tink-cli binary instead of using latest

---

build/lib/common.sh
build/lib/fetch_binaries.sh

In case of downloading artifacts from an older commit instead of latest, we need to use the git tag of the artifact from that commit.

Use proper git tag for overriden artifacts

---

projects/tinkerbell/tink/Makefile
projects/tinkerbell/tink/build/create_manifests.sh

Add `tinkerbell/tink` in the image URI for tink manifest

Add 'tinkerbell/tink' in the image URI for tink manifest

---

projects/aws/eks-a-admin-image/Makefile
projects/aws/eks-a-admin-image/build/get_latest_eksa_version_by_date.sh
projects/aws/eks-a-admin-image/common.pkr.hcl

Part of https://github.com/aws/eks-anywhere/issues/1166
This image will be built from a pipeline. Such pipeline will run whenever the release manifest file in S3 changes (this happens every time we build a new version). But that doesn't tell us which is the version that just got built.
We could use the `latestVersion` in the manifest but that will be pointing to the latest release for the latest minor version. If we build a new patch release for the previous minor version (eg. `latestVersion` is `v0.8.2` and we build `v0.7.5` due to some vulnerability) then the `latestVersion` field won't change.
Instead, this just iterates over all the releases and picks the latest one, by date.
This is not ideal. If we trigger two releases in parallel very close in time, it's possible that we will build …

Add target to build latest snow raw admin image

---

Common.mk
build/lib/buildkit.sh

When building locally it can be useful to push built images to ecr
in our aws accounts to make testing easier. create-ecr-repos target
will create repos for each image defined in the project's IMAGE_NAMES.
This also adds a check during buildctl calls running locally for a
common EOF error that typically indicates a missing repo.

Adds new target to create ecr repos

---

projects/kubernetes-sigs/image-builder/build/build_raw_image.sh

It always chooses us-west-2b, which causes InsufficientCapacity issue as below
```
An error occurred (InsufficientInstanceCapacity) when calling the RunInstances operation (reached max retries: 2): We currently do not have sufficient i3en.metal capacity in the Availability Zone you requested (us-west-2b). Our system will be working on provisioning additional capacity. You can currently get i3en.metal capacity by not specifying an Availability Zone in your request or choosing us-west-2a, us-west-2c, us-west-2d.
```

Select Availability zone randomly for EC2 instance creation

---

build/lib/helm_copy.sh

When make images was re-run (like after a build failure somewhere in
the process), this step would try to replace existing files in the
destination .git directory that were read-only, and so it would fail.
Rather than using cp's -f flag or similar, I figured, why not just
exclude .git entirely? We don't want that going into the helm chart
anyway.
If rsync isn't available in the builder base, this could be a problem
I guess, but I think rsync is pretty standard, and the flags I'm using
have been around for a long time.

Use rsync to exclude git files in helm copy

---

Common.mk

If $IMAGE_REPO is determined to be a public ECR repo, then the
create-ecr-repos Makefile target will create public repos instead of
private ones.

Support creating ECR public repos too.

---

projects/tinkerbell/hegel/CHECKSUMS
projects/tinkerbell/hegel/GIT_TAG
projects/tinkerbell/hegel/Makefile

Bump up hegel GIT_TAG to the latest commit

Bump up hegel git tag to latest

---

Common.mk
build/lib/common.sh
build/lib/fetch_binaries.sh

For some projects, like bootconfig, we use a custom name for the tarball. Currently the fetch binaries helper script is unaware of this support and assumes it named a certain way.  This adds support for fetching these custom names tarballs.
In cases where we are not building arm versions, which should be avoided but is currently the case for bootconfig, we need to not try and pull arm tars.  This changes that to use the BINARY_PLATFORMS var as the source of truth for which tars to pull.  Instead we may want/need to introduce a FETCH_BINARIES_PLATFORMS, but id rather avoid it if we dont need it.

Supprt custom tar file prefixes when fetching dep binaries

---

Common.mk
Makefile
build/lib/setup.sh

Mitali ran into a couple issues during the staging build.
We got hit by the random tls handshake timeout when trying to pull
the qemu image and since the builder base had been updated with new
golang versions, the source controller build pulled the latest
builder base and the checksums did not match. Abhay had added the
builder base tag env var and config file, for code build and prow
respectively, but we never implemented using them. With this change
the source controller cgo build should always pull the same builder
base that the current build is running in, instead of the latest.

retries docker pull and use builder base tag

---

Common.mk

The env var in codebuild has the full image in it vs just the tag.

fix builder image for cgo in codebuild

---

projects/tinkerbell/hub/CHECKSUMS
projects/tinkerbell/hub/patches/0001-Get-user-data-from-Hegel-and-write-to-disk.patch

If Hegel URL is set, while contents and bootconfig are not, this action will get the user-data from Hegel service and write it to file on the specified path.

Patch writefile to pull user-data from hegel & write to disk

---

projects/tinkerbell/hub/Makefile

Bootconfig is a dependency for Writefile action. This is not a static binary and requires libraries that are found in the glibc base image.

Make glibc base image for writefile

---

projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap-after.sh
projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap.sh
projects/kubernetes-sigs/image-builder/packer/ami/additional_files/generate-kube-vip-manifest.sh
projects/kubernetes-sigs/image-builder/packer/ami/additional_files/logging.sh

Support reading compressed user-data in bootstrap scripts.
Related capas pr: https://github.com/aws/cluster-api-provider-aws-snow/pull/63
*Testing:*
Manually modified scripts and successfully provisioned a cluster using compressed user-data
```
[ec2-user@ip-34-223-14-194 ~]$ kubectl get machines -o wide
NAME                                     CLUSTER            NODENAME                PROVIDERID                                        PHASE     AGE     VERSION
capas-quickstart-control-plane-4p228     capas-quickstart   s-i-878f2d65582d41242   aws-snow:///10.111.60.195/s.i-878f2d65582d41242   Running   96m     v1.21.2-eks-1-21-3
capas-quickstart-md-0-7886fb76bf-l2zgl   capas-quickstart   s-i-81f717145fb7c1447 …
```

Support compressed user-data for Snow

---

projects/tinkerbell/rufio/docker/linux/Dockerfile
projects/tinkerbell/tinkerbell-chart/chart/templates/rufio-deployment.yaml

Fixes error: `starting container process caused: exec: "/manager": stat /manager: no such file or directory: unknown.` on pod creation.

Changing entrypoint for Rufio manager image

---

build/lib/common.sh
build/lib/setup.sh
projects/distribution/distribution/Makefile
projects/fluxcd/helm-controller/Makefile
projects/fluxcd/kustomize-controller/Makefile
projects/fluxcd/source-controller/Makefile
projects/goharbor/harbor/Makefile
projects/helm/helm/Makefile
projects/jetstack/cert-manager/Makefile
projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
projects/kubernetes-sigs/cluster-api/Makefile
projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
projects/kubernetes-sigs/kind/build/create-kind-cluster.sh
projects/kubernetes-sigs/kind/images/k8s.io/kubernetes/build/download-images.sh
projects/kubernetes-sigs/kind/patches/0001-Switch-to-AL2-base-image-for-node-image.patch
projects/kubernetes/cloud-provider-vsphere/Makefile
projects/replicatedhq/troubleshoot/Makefile

Couple things i notice when looking at recent flaky build failures.
- add retry around docker pulls
- retry wgets that get connection refused
- fix kind build that hasnt been any issue yet because dev/staging are build with a cache

Increases build stability when wget licenses and docker pull

---

projects/tinkerbell/hook/CHECKSUMS
projects/tinkerbell/hook/patches/0001-Download-registry-cert-only-if-tinkerbell_tls-is-tru.patch

Hook currently tries to pull the cert unconditionally and panics if the cert is not served from a hardcoded endpoint. 
This PR patches hook to only pull the cert if tls is enabled 

Patch hook to skip pulling registry cert

---

build/lib/helm_replace.sh
projects/aws-containers/hello-eks-anywhere/helm/files.txt
projects/aws/eks-anywhere-packages/helm/files.txt
projects/fluxcd/flux2/helm/files.txt
projects/goharbor/harbor/helm/files.txt
projects/jetstack/cert-manager/helm/files.txt

I'd like to discourage use of this except for the values.yaml and Chart.yaml file. We should be patching everything else. There are a couple cases where we are running this on the README, but those don't matter.
Closes: https://github.com/aws/eks-anywhere-packages/issues/193

Helm charts with no files.txt

---

projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0002-Adding-watch-on-Rufio-BMCJob.patch

Adding a CAPT patch to watch BMCJobs and mark machine ready only after job is completed. Similarly for delete cluster.

Adding a patch to add CAPT BMCjob watch

---

projects/kubernetes-sigs/image-builder/patches/0008-Add-support-for-RHEL-8-RAW-image-builds.patch
projects/kubernetes-sigs/image-builder/patches/0009-Add-support-for-RHEL-8-OVA-builds.patch

This should potentially solve the flaky EOF errors when Packer parses the var files.

Fix EOF errors occuring during Packer build

---

projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0004-Replace-poweroff-poweron-with-reset.patch

Upon testing it was noticed that doing a powerOff and then powerOn was at times being flaky. This could be due to the response time of the BMC.
Replacing with power reset call.

CAPT job power reset action

---

projects/tinkerbell/hub/CHECKSUMS
projects/tinkerbell/hub/patches/0001-Write-DHCP-offer-to-static-Netplan-file.patch

This allows a workflow to write a static netplan from a DHCP host reservation from Boots.

Patch writefile workflow template:

---

projects/kubernetes-sigs/etcdadm/CHECKSUMS
projects/kubernetes-sigs/etcdadm/patches/0014-Add-retry-on-listing-members-in-join-command.patch

When a new ETCD machine tries to join a cluster while the machine is not reachable the joining process fails at listing members without retrying. This PR adds the retry logic to this step so that the machine can join when it is reachable. 
Upstream PR: https://github.com/kubernetes-sigs/etcdadm/pull/316

Create a patch for retrying to list members in the join command

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
projects/kubernetes-sigs/image-builder/BOTTLEROCKET_OVA_RELEASES

/hold till the bottlerocket 1.8.0 release is out.
1.8.0 was released => https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.8.0

Add 1.23 builds for Bottlerocket

---

build/lib/run_target_docker.sh

Due to the new dependencies support the run in docker targets are broken because to avoid copying the entire repo into the docker builder container, the rsync was not including the dependency project source code.  This reads the deps from the makefile and copies those projects to the builder container as well.
This also fixes the .git HEAD warning to avoid confusion.

Fixes update checksum in docker target

---

build/lib/readme_check.sh
projects/cilium/cilium/README.md
projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
projects/tinkerbell/rufio/README.md
projects/tinkerbell/tink/README.md

Some projects have a dash in their Git tag, and we can't use these directly in the badge URL template. Using two dashes renders the badge properly.
`https://img.shields.io/badge/version-v0.4.5-rc3-blue`: ![Badge](https://img.shields.io/badge/version-v0.4.5-rc3-blue)
`https://img.shields.io/badge/version-v0.4.5--rc3-blue`: ![Badge](https://img.shields.io/badge/version-v0.4.5--rc3-blue)

Fix README version field for projects with dashes in tag

---

projects/kubernetes-sigs/image-builder/Makefile

BR does not have metal variant for Kubernetes version 1.20, so this step fails. Skipping it for non-existent versions.

Skip BR raw image operations for Kubernetes version 1.20

---

projects/metallb/metallb/Makefile
projects/metallb/metallb/docker/linux/speaker/Dockerfile
projects/metallb/metallb/helm/patches/0001-initial-patch.yaml
projects/metallb/metallb/helm/sedfile.template

Add metallb helm chart.
This chart removes FRR support and does not allow creating deprecated PodSecurityPolicy resources.
Only in-line configuration is allowed and should be configured in the package definition.

Metallb helm

---

UPSTREAM_PROJECTS.yaml
projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md

*Testing performed:*
E2e test with bundle overrides
```
--- PASS: TestCloudStackKubernetes121SimpleFlow (1766.35s)
PASS
```

Fixing CAPC affinity group deletion bug

---

UPSTREAM_PROJECTS.yaml
projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md

EKS-A e2e tests failed when using the commit hash with clusterctl init with error message
```
cluster.go:677: Command eksctl anywhere [create cluster -f release-i-06a23-1ff28bb/cluster.yaml -v 4 --bundles-override bin/local-bundle-release.yaml] failed with error: exit status 255: Error: failed to get provider components for the 
"cloudstack:c0d5e8d3735f2dace5997ed9515e437a5ec30a6a+e3b0c44" provider: failed to get repository client for the InfrastructureProvider with name cloudstack: error creating the local filesystem repository client: invalid version: 
"c0d5e8d3735f2dace5997ed9515e437a5ec30a6a+e3b0c44". Version must obey the syntax and semantics of the "Semantic Versioning" specification (http://semver.org/) and path format …
```

Replacing CAPC commit hash with tag

---

Common.mk
build/lib/run_target_docker.sh

Most builds with deps like this need them for their images. The way it was it would only run the target during the build target so if someone ran `make images` it would fail due to missing the deps.  

Runs handle_deps as prepreq for images

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/get_bottlerocket_artifacts.sh

Tuftool is now in builder-base so we don't need to install it prior to Bottlerocket downloads in CI.

Remove Tuftool install prerequisite for Bottlerocket downloads

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/get_bottlerocket_artifacts.sh

We override HOME to `/home/imagebuilder` in the buildspec.

Hardcode HOME env var to root directory

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/get_bottlerocket_artifacts.sh

Tuftool is now available at `/usr/bin`, so don't need these.

Revert changes to Imagebuilder Makefile and script

---

projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh

Codebuild output for `ip a show` did not include the broadcast address due to it being a Private subnet, hence using this technique.

Fix logic to get active interface for Packer HTTP server

---

projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap-volume.sh
projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap.sh
projects/kubernetes-sigs/image-builder/packer/ami/additional_files/logging.sh
projects/kubernetes-sigs/image-builder/packer/ami/ansible_extra_vars.yaml

25G default root volume size for eks-d AMI may not be enough to support larger containers.
Added a script to bootstrap additional volume, on detecting a new volume, the script will stop containerd, backup the data, mount the new volume to containerd data directory, move the backup data back and then restart containerd
*Testing:*
Manually built an ami with the script, and successfully provisioned a snow cluster with addition volume.
* provisioned a workload cluster with ContainersVolume set to 100G for worker nodes
```
[ec2-user@ip-34-223-14-194 ~]$ kubectl get machines -owide -A
NAMESPACE   NAME                                    CLUSTER            NODENAME                PROVIDERID                                        PHASE     AGE …
```

Added script to mount an additional volume for container data

---

projects/kubernetes-sigs/image-builder/README.md
projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
projects/kubernetes-sigs/image-builder/packer/config/common.json.tmpl

To make Ansible support proxy configuration the proxy settings are in one of the JSON files passed via `PACKER_VAR_FILES` environment variable 

Add proxy configuration to common.json

---

projects/tinkerbell/hook/CHECKSUMS
projects/tinkerbell/hook/Makefile

Linuxkit is in the 1.16 GOPATH, so need to get it from there.

Use Linuxkit binary from GOPATH

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES

Updating Bottlerocket to 1.9.0. Raw artifacts have been updated to follow same versioning nomenclature as ova artifacts.
No updates to admin container.
/approve

Update Bottlerocket release

---

projects/kubernetes-sigs/cluster-api-provider-cloudstack/build/create_manifests.sh

Changes to CAPC create_manifests.sh to alter kube-rbac-proxy image provided by CAPC make.
Confirmed by building make targets in docker and examining resulting file.

Overriding kube-rbac-proxy image repo provided by CAPC with EKS-A default repo.

---

projects/kubernetes-sigs/image-builder/build/build_ova_image_cli.sh
projects/kubernetes-sigs/image-builder/build/setup_image_builder_cli.sh

Setting up image-builder cli on /usr/bin requires root perms on CI. Changing the setup phase to take in an argument for download location to support CI process.

Fix OVA builds on CI

---

projects/envoyproxy/envoy/Makefile

Remove envoy image name override
Default name works okay

Remove envoy image name override

---

projects/helm/helm/CHECKSUMS
projects/helm/helm/patches/0002-Set-proxy-environment-in-HTTP-client.patch

Without passing proxy environment to http client again, proxy will not be honored.

Set proxy environment in HTTP client

---

projects/kubernetes-sigs/image-builder/build/build_image.sh
projects/kubernetes-sigs/image-builder/build/build_raw_image.sh

CI builds were failing on unbound $ARTIFACTS_BUCKET. This fixes to consume the env var as an argument instead of relying on the environment.

Fix Raw builds on CI

---

projects/kubernetes-sigs/image-builder/build/setup_image_builder_cli.sh

Instead of extracting and then moving the image-builder executable, directly extracting to location to make it neater and less error prone.

[ImageBuilder] Extracting tarball directly to download location

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/build_raw_image.sh

We are changing the builder-base for Image builder from AL2 to Ubuntu. These are script changes required to run the raw builds properly.

Change raw image-builder base from AL2 to Ubuntu

---

projects/kubernetes-sigs/image-builder/build/build_raw_image.sh

Properly set the env var CODEBUILD_CI in order for CI to pick up the path properly.

Fix exports on codebuild

---

projects/kubernetes-sigs/image-builder/Makefile

Skip Bottlerocket Raw release targets for 1-20 release branch.
/cherrypick release-0.11

Skip Bottlerocket Raw release targets for 1-20 release branch

---

projects/kubernetes-sigs/kind/Makefile
projects/kubernetes-sigs/kind/build/build-kind-node-image.sh
projects/kubernetes-sigs/kind/images/node/Dockerfile

When updating kind, to handle the change in the way 1.24 in kind supports a different cgroup, the containerd.toml config needed to be handled a bit differently. This caused the sed for the pause image to happen to early (or late depending on how you look at it) and therefore did not take affect in the final image. This meant images would pull pause from gcr instead of our ecr repos, which sorta break airgapped envs.

Fixes pause image baked into kind image

---

projects/kubernetes-sigs/image-builder/build/build_raw_image.sh

Raw builds on CI were failing with improper env variables being set. This overrides these variables to right values.
Changes were tested on my account.

Fix Ubuntu Raw builds on CI

---

Common.mk

The new builder-base updated Git from 2.34.3 to 2.37.1, which added [this commit](https://github.com/git/git/commit/4ce504360bc3b240e570281fabe00a85027532c3) to validate that the arguments to the `set` command are directories. The attribution job with the updated builder-base failed building the bootconfig binary with the error
```bash
git -C linux sparse-checkout set tools lib/bootconfig.c include/linux/bootconfig.h --cone
fatal: 'lib/bootconfig.c' is not a directory; to treat it as a directory anyway, rerun with --skip-checks
```
This should fix it for future usecases.

Add skip-checks argument to sparse-checkout for individual file support

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/builder.go
projects/kubernetes-sigs/image-builder/build/build_raw_image.sh

Instead of trying to deduce the pre-cloned directory use already set env variable to correctly figure out the proper path.

[ImageBuilder] Set codebuild env vars appropriately

---

Common.mk
build/lib/eksa_releases.sh
projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh

Re-use existing latest tag on repo instead of git branch. This helps out with the branch name/latest tag resolving properly in all environments.

Use latest tag instead of git branch

---

projects/tinkerbell/hook/CHECKSUMS
projects/tinkerbell/hook/patches/0003-Added-support-for-allowing-image-pull-from-local-reg.patch

This patch is for allowing pull from local registry for Tinkerbell provider. 

Added a patch of allowing insecure pull from local registry

---

Common.mk

*Issue #, if available:* N/A. This is for use cases where helm charts are created without images.
*Description of changes:* Debundled helm make targets with other image make targets for `build` and `release`. This should not impact any other existing make target.
*Testing:* With this change, project `ADOT` is able to avoid build_target and release_target override. I also randomly picked project `metallb` (that has both image build and helm chart build) and made sure it could still be built with original targets.

Debundle helm make targets with other image make targets for build and release

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/builder.go
projects/aws/image-builder/builder/utils.go

Image builder raw builds were running git commands outside the repo on CI. These changes ensure the commands are run inside the repo.

Fix git commands on CI

---

build/lib/helm_push.sh
projects/aws/eks-anywhere-packages/Makefile

`GIT_TAG?=$(shell cat GIT_TAG)` allows the var to be overwritten by codebuild
`${GIT_TAG#[^0-9:main]}"` makes it so the `m` won't get chopped off if the tag is main.

Changes for dev package build

---

projects/kubernetes-sigs/image-builder/build/build_image.sh

1. Setup vsphere connection json with rhsm creds.
2. Setup base iso for redhat image building along with checksum.

Support RHEL creds for RHSM in image-builder

---

projects/kubernetes-sigs/image-builder/Makefile

Fix makefile to use redhat instead of rhel string

---

projects/kubernetes/autoscaler/Makefile

Right now, all helm charts have the same tag, so helm_push.sh only ends up tagging the 1.24 helm chart with the 9.21.0 tag.
By suffixing the kubernetes version we can distinguish tags on the charts.

Create distinct tags for each helm chart

---

projects/aws/eks-a-admin-image/Makefile

This fixes the deletion of the _output directory during build.

Create actual path instead of parent path

---

build/lib/helm_push.sh

Fallback to HELM_TAG if not.
This fixes an issue we were experiencing where GIT_TAG was a hash, not a semver.
When the bundle promotion process tried to pull that helm chart tagged by the hash, the pull failed because it was not a valid semver.

Check if GIT_TAG is semver

---

projects/aws/eks-a-admin-image/provisioners/upgrade_linux.sh

This might prevent some apt issues arising due to shortage of space.

Clean up apt package cache before upgrade

---

Common.mk
projects/kubernetes/autoscaler/Makefile

Some projects like `kind` and `image-builder` are classified as release-branched, but don't have separate folders for release branch since they don't have release branch specific git tags or Golang versions like `cloud-provider-vsphere` or `autoscaler`. The current check was skipping the build for these projects since the directory pertaining to the release branch was non-existent. This PR modifies the check, introducing a new variable for skipped Kubernetes release branches that can be set at a project level.

Use more robust filtering for skipped release branches

---

build/lib/helm_push.sh

Epic: https://github.com/aws/eks-anywhere/issues/3187
Ticket: https://github.com/aws/eks-anywhere/issues/3414
Bug introduced in https://github.com/aws/eks-anywhere-build-tooling/pull/1326
We should fallback to the variable $SEMVER in `helm_push.sh`, not the literal string SEMVER, when a GIT_TAG value is not a valid semantic version.

Fallback to $SEMVER, not literal SEMVER

---

build/lib/eksd_releases.sh
build/lib/generate_projects_list.sh

Epic: https://github.com/aws/eks-anywhere/issues/3187
Ticket: https://github.com/aws/eks-anywhere/issues/3414
- Adds functionality to automatically pull latest EKS-D project tag
- Adds functionality to skip metrics-server project, our first EKS-D backed helm chart, when generating UPSTREAM_PROJECTS.yaml
Supports https://github.com/aws/eks-anywhere-build-tooling/pull/1331.

Support Building Helm Charts From EKS-D Images

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/build_raw_image.sh

Support multiple targets for raw builds. Add support for redhat image building for baremetal.

Support multiple targets + redhat for local raw builds

---

projects/aws/eks-a-admin-image/eks-a-admin-snow.pkr.hcl

This increases the maximum retry attempts for the AMI generation step so it doesn't time out. Timeout is effectively bumped to 2 hours with this change.

Bump Snow Admin AMI generation wait time to 2 hours

---

projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh

Packer's vsphere plugin does not work well in figuring our the ip address on our CI environment. There is currently no way to control this from the user. This change figures out the ip address in the image build workflows and sets the appropriate endpoint.

Redhat packer http endpoint for boot media

---

build/lib/helm_require.sh

Had a bug in build process that did not include schema.json in release-branched helm charts.
Manually tested by building metalb and autoscaler to verify that schema.json was properly included in both release branched and non release branched helm charts.

Include json schema for release branched helm charts

---

projects/kubernetes/autoscaler/1-21/helm/schema.json
projects/kubernetes/autoscaler/1-22/helm/schema.json
projects/kubernetes/autoscaler/1-23/helm/schema.json
projects/kubernetes/autoscaler/1-24/helm/schema.json

https://github.com/aws/eks-anywhere/issues/3186
Original schema.json had all fields as required. This is unnecessary.
I also updated the field defaults to reflect `values.yaml` defaults.

Fix Up Cluster Autoscaler Schema

---

build/lib/eksd_releases.sh
projects/kubernetes-sigs/metrics-server/Makefile

A bug in the previous implementation led to helm charts always being build with 1-22 images locally.

Build metrics-server With Correct Image Tags

---

projects/nutanix-cloud-native/cluster-api-provider-nutanix/ATTRIBUTION.txt
projects/nutanix-cloud-native/cluster-api-provider-nutanix/CHECKSUMS
projects/nutanix-cloud-native/cluster-api-provider-nutanix/Makefile

Update Makefile to set Go Version to 1.19
Generated checksums using `make update-attribution-checksums-docker`.

Update Golang version for CAPX

---

build/update-attribution-files/create_pr.sh
projects/fluxcd/source-controller/Makefile

* Add Prowjob log links to bot-authored PRs (same as aws/eks-distro-build-tooling#488)
* Add `-x` flag to Flux source-controller build invocation.

Add verbose logging to source-controller build

---

build/lib/generate_staging_buildspec.sh
projects/kubernetes-sigs/kind/Makefile
release/staging-build.yml

Kind is the long pole when it comes to builds in the staging batch build. This breaks the build up by release branch
*NOTE* The binaries will build and publish in each build and since they are not released branch it will overwrite, this shouldn't be an issue since the checksums will all guarantee the resulting builds are all the same, but something to keep in mind just in case.

Run release branch specific builds for kind in staging

---

Common.mk
projects/fluxcd/flux2/Makefile
projects/fluxcd/source-controller/Makefile
release/staging-build.yml

Due to common build failures in codebuild we are trying to see if using docker instead of buildctl to build the cgo binaries will be more consistent.
This also removes the source-controller dep from flux since we arent building that helm chart anymore.

Adds docker option for cgo builds

---

build/lib/generate_staging_buildspec.sh
release/staging-build.yml

Fix kind dependency for CLI tools image in staging build

Fix kind dependency for CLI tools image in staging build

---

projects/kubernetes-sigs/image-builder/patches/0010-Exclude-kernel-updates-for-Redhat.patch

Redhat updates for 8.6 includes kernel updates for which firmware drivers are not out yet. This causes failures in image-builds, cluster operations, etc. 

Patch to exclude kernel updates for Redhat

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/builder.go

step of patching is now automated.
ran following to test
<pre>
ubuntu@ubuntu:~/go/src/github.com/nutanix-cloud-native/aws-eks-anywhere-build-tooling/projects/aws/image-builder$ /home/ubuntu/go/src/github.com/nutanix-cloud-native/aws-eks-anywhere-build-tooling/projects/aws/image-builder/_output/bin/image-builder/linux-amd64/image-builder build --os ubuntu --hypervisor nutanix --nutanix-config ./nutanix-connection-1.20.json --release-channel 1-20
Creating builder config
2022/10/06 20:33:26 Using repo checked out from code commit
2022/10/06 20:33:26 Executing command: /usr/bin/git -C /home/ubuntu/go/src/github.com/nutanix-cloud-native/aws-eks-anywhere-build-tooling rev-parse --show-toplevel
2022/10/06 20:33:26 Initiating Image Build
Image …

now patching the repo before building nutanix image

---

projects/kubernetes/autoscaler/Makefile

Renames cluster-autoscaler's helm repo to align with convention.

Rename cluster-autoscaler helm destination repo

---

projects/kubernetes/autoscaler/1-21/helm/patches/0004-Use-eks-anywhere-default-registry.patch
projects/kubernetes/autoscaler/1-22/helm/patches/0004-Use-eks-anywhere-default-registry.patch
projects/kubernetes/autoscaler/1-23/helm/patches/0004-Use-eks-anywhere-default-registry.patch
projects/kubernetes/autoscaler/1-24/helm/patches/0004-Use-eks-anywhere-default-registry.patch

Default source registry was previously `public.ecr.aws` when it should have been `public.ecr.aws/eks-anywhere`. This PR corrects the issue.

Correct cluster-autoscaler Default Source Registry

---

projects/kubernetes-sigs/metrics-server/1-21/helm/schema.json

https://github.com/aws/eks-anywhere/issues/3187
metrics-server's schema.json contained null types, which does not allow a user to configure the fields with anything other than null.
This PR replaces those with appropriate integer types.

Remove null types from metrics-cluster schema.json

---

projects/kubernetes/autoscaler/Makefile

https://github.com/aws/eks-anywhere/issues/3186
To avoid overwriting tags, we need to add the git hash of the build tooling repo at build time.

Add git hash to cluster autoscaler helm tags

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/build_raw_image.sh

1. Handle unsupport os name and format combination on makefile.
2. Send the latest tag in for raw image builds.

Handle unsupported os and format combinations for Image Builder

---

projects/kubernetes/autoscaler/1-21/helm/sedfile.template
projects/kubernetes/autoscaler/1-22/helm/sedfile.template
projects/kubernetes/autoscaler/1-23/helm/sedfile.template
projects/kubernetes/autoscaler/1-24/helm/sedfile.template
projects/kubernetes/autoscaler/README.md

Previously, we were not updating the chart's default appVersion of `1.23.0`.
Unfortunately, we do not have access to the specific cluster autoscaler version tags because we tie our builds to git hashes.
We have to do this because the upstream project has messed up their tagging.
This is far from an ideal solution, and I am open to alternatives.
I tried generating a Major.Minor vesion based on the RELEASE_BRANCH, but passing that variable down into helm_require.sh is non trivial.

Specify correct appVersion in Cluster Autoscaler

---

projects/kubernetes-sigs/metrics-server/1-21/helm/schema.json
projects/kubernetes-sigs/metrics-server/1-22/helm/schema.json
projects/kubernetes-sigs/metrics-server/1-23/helm/schema.json
projects/kubernetes-sigs/metrics-server/1-24/helm/schema.json
projects/kubernetes/autoscaler/1-21/helm/patches/0005-Use-imagePullSecrets-instead-of-pullSecrets.patch
projects/kubernetes/autoscaler/1-21/helm/schema.json
projects/kubernetes/autoscaler/1-22/helm/patches/0005-Use-imagePullSecrets-instead-of-pullSecrets.patch
projects/kubernetes/autoscaler/1-22/helm/schema.json
projects/kubernetes/autoscaler/1-23/helm/patches/0005-Use-imagePullSecrets-instead-of-pullSecrets.patch
projects/kubernetes/autoscaler/1-23/helm/schema.json
projects/kubernetes/autoscaler/1-24/helm/patches/0005-Use-imagePullSecrets-instead-of-pullSecrets.patch
projects/kubernetes/autoscaler/1-24/helm/schema.json

We needed to update the metrics-server and cluster-autoscaler helm charts to accept imagePullSecrets argument in order to work with auth.

Align Image Pull Secrets to Convention

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES

Updated bottlerocket to v1.10.0 and updated bottlerocket-admin-container to v1.9.2

Update bottlerocket to v1.10.0 and update bottlerocket-admin-container to v1.9.2

---

build/lib/helm_require.sh
projects/metallb/metallb/Makefile

Pass the dependencies down to requires.yaml to be picked up by the bundle creation process.

Add support for dependencies in requires.yaml

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES

Bottlerocket released their latest ova with 1.24 support 🎉
https://github.com/bottlerocket-os/bottlerocket/releases

Add 1.24 BR ova release

---

projects/kubernetes-sigs/metrics-server/1-21/helm/patches/0002-Make-imagePullSecrets-top-level-value.patch
projects/kubernetes-sigs/metrics-server/1-21/helm/schema.json
projects/kubernetes-sigs/metrics-server/1-22/helm/patches/0002-Make-imagePullSecrets-top-level-value.patch
projects/kubernetes-sigs/metrics-server/1-22/helm/schema.json
projects/kubernetes-sigs/metrics-server/1-23/helm/patches/0002-Make-imagePullSecrets-top-level-value.patch
projects/kubernetes-sigs/metrics-server/1-23/helm/schema.json
projects/kubernetes-sigs/metrics-server/1-24/helm/patches/0002-Make-imagePullSecrets-top-level-value.patch
projects/kubernetes-sigs/metrics-server/1-24/helm/schema.json
projects/kubernetes/autoscaler/1-21/helm/schema.json
projects/kubernetes/autoscaler/1-22/helm/schema.json
projects/kubernetes/autoscaler/1-23/helm/schema.json
projects/kubernetes/autoscaler/1-24/helm/schema.json

The imagePullSecrets schema field was wrong before. It accepted an array of strings when it should have accepted an array of objects.
This PR resolves the issue.
There was another issue in the metrics-server helm chart where the imagePullSecrets key was under `image` instead of being a top-level key.
None of these things caused actual bugs because the controller overrides imagePullSecrets and injects it as a value to the helm chart. All the same, I'd like to make these changes to keep things tight.
I've manually verified the changes by generating a bundle locally and applying it to a cluster. With the dev bundle I've successfully applied package configs that specify `imagePullSecrets` …

Fix CA & Metrics Server imagePullSecrets Schema

---

projects/cert-manager/cert-manager/helm/patches/0005-Update-cert-manager-namespace-config.patch

- cert-manager webhook doesn't currently allow the quotes on the namespace. Fixing that issue.

Fix cert manager webhook

---

projects/metallb/metallb/helm/patches/0001-packages-patches.patch

Standardize namespace setting across the chart (with default to what's in the values.yaml file).
Add missing namespacing to webhook service.

Standardize namespace setting and add missing on webhook

---

projects/metallb/metallb/helm/patches/0001-packages-patches.patch

Remove autoAssign from l2adv as this is on ipAddressPool

Remove autoassign from l2adv

---

projects/metallb/metallb/helm/patches/0001-packages-patches.patch

Fix helm interpreting default of false as undefined, leading to true overrides.

Helm evaluates false as undefined, fix metallb autoAssign

---

projects/kubernetes-sigs/metrics-server/1-21/helm/patches/0003-Make-sourceRegistry-top-level-value.patch
projects/kubernetes-sigs/metrics-server/1-21/helm/schema.json
projects/kubernetes-sigs/metrics-server/1-22/helm/patches/0003-Make-sourceRegistry-top-level-value.patch
projects/kubernetes-sigs/metrics-server/1-22/helm/schema.json
projects/kubernetes-sigs/metrics-server/1-23/helm/patches/0003-Make-sourceRegistry-top-level-value.patch
projects/kubernetes-sigs/metrics-server/1-23/helm/schema.json
projects/kubernetes-sigs/metrics-server/1-24/helm/patches/0003-Make-sourceRegistry-top-level-value.patch
projects/kubernetes-sigs/metrics-server/1-24/helm/schema.json
projects/kubernetes/autoscaler/1-21/helm/patches/0006-Make-sourceRegistry-top-level-value.patch
projects/kubernetes/autoscaler/1-21/helm/schema.json
projects/kubernetes/autoscaler/1-22/helm/patches/0006-Make-sourceRegistry-top-level-value.patch
projects/kubernetes/autoscaler/1-22/helm/schema.json
projects/kubernetes/autoscaler/1-23/helm/patches/0006-Make-sourceRegistry-top-level-value.patch
projects/kubernetes/autoscaler/1-23/helm/schema.json
projects/kubernetes/autoscaler/1-24/helm/patches/0006-Make-sourceRegistry-top-level-value.patch
projects/kubernetes/autoscaler/1-24/helm/schema.json

Fixes a bug in cluster-autoscaler and metrics-server packages.
The previous registry key was image.sourceRegistry when it should have been sourceRegistry.
Additionally, the default image registry was set to a public AWS registry when it should have pointed to 7837 account.
Because of these two things together, the controller did not override the registry with the prod account and instead tried to pull images from the public eks-anywhere account, which did not contain the images.
Manually tested by building both packages locally and creating bundle locally. Successfully installed both packages on a dev cluster pointing to …

Make sourceRegistry Top Level Value

---

projects/metallb/metallb/helm/schema.json

remove BFD due to no FRR
Remove format int32 for testing with ajv

Sync ipaddresspool caps with upstream

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES

Bumping BR version to point to latest release https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.10.1

Bump BR release version

---

build/lib/generate_staging_buildspec.sh

For repo, we will take the entire substring after the first occurrence of underscore. This is to handle a use case of where the repo name itself contains an underscore.

Update staging_buildspec project name handling

---

projects/aws/eks-a-admin-image/Makefile

PR #1456 referenced a new Make target that is not available in the Makefile.

Use proper Make target for EKS-A admin image build

---

projects/aws/eks-a-admin-image/provisioners/download_eksa_artifacts.sh

Without the --all flag, it just prunes dangling images but there are no such images in the admin image. What we need is to prune all the unused images.

Prune all unused images, not just dangling ones

---

Makefile

While evaluating the PROJECT_PATH, instead of replacing all `_` with `/`, we will only replace the first instance of `_`. This is to help support project that contains `_` in the project name.

Update make add-generated-help-block and attribution-files logic

---

Common.mk
build/lib/simple_create_binaries.sh
build/update-attribution-files/create_pr.sh

- We started seeing git fetch being rate limited in presubmit
- Fix warning due to missing cgo var
- Fix building multiple binaries with one being `.`, this is needed for the snow br bootstrap changes coming

Fixes git fetch rate limit and build multiple binaries

---

projects/kubernetes-sigs/image-builder/.gitignore
projects/kubernetes-sigs/image-builder/packer/ami/share-ami.json

Fixing image-builder CLI for AMI builds in local environments.

Check in share AMI configuration to the repo

---

projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh

On some OS's like Ubuntu, the root `tmp` directory's permissions are scoped down for other users, and we run AMI builds as non-root (`imagebuilder`) so we're creating it in that user's home directory instead.

Create CNI temp directory in non-root user's home directory

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/constants.go
projects/aws/image-builder/cmd/build.go
projects/aws/image-builder/cmd/build_test.go
projects/kubernetes-sigs/image-builder/build/build_image.sh

Setting default opinionated values for AMI build configuration so customers can set only values for parameters they really want to control while letting the tool default to these values for other fields.

Set default input values for AMI build configuration

---

projects/aws/eks-a-admin-image/provisioners/download_eksa_artifacts.sh
projects/aws/eks-a-admin-image/provisioners/test/download_eksa_artifacts.sh

Changing the path extension to .tar.gz makes the CLI apply gzip compression on the artifacts archive to create a tarball which saves more on disk space. 

Use gzip compression when downloading images from bundle

---

projects/prometheus/prometheus/helm/patches/0005-json-schema-patch.diff
projects/prometheus/prometheus/helm/patches/0006-configmap-reload-patch.diff
projects/prometheus/prometheus/helm/patches/0007-values-patch.diff
projects/prometheus/prometheus/helm/schema.json

Add support for pod update strategy due to configmap changes, and tolerations for node-exporter

Update Prometheus helm charts

---

EKSD_LATEST_RELEASES

Bump the versions of eksd to match December 01, 2022 release.

Bump eksd versions

---

projects/kubernetes-sigs/image-builder/patches/0010-Pin-RHEL-to-8.6-version-to-avoid-cloud-init-bug.patch

RHEL 8.7 shipped with a cloud-init bug, where cloud-init tried to pull user-data from its data source before networking setup completes. Cloud-init fails to retry once networking is up, and defaults to nil user-data. This causes bootstrapping process to fail completely. This change pins image-building to 8.6 version till upstream fixes cloud-init issues.
https://bugs.launchpad.net/cloud-init/+bug/1998655
https://github.com/aws/eks-anywhere/issues/4282
/hold 

Pin RHEL version to 8.6

---

projects/kubernetes-sigs/image-builder/packer/ova/vsphere-library.json

If the VSphere content library name is hardcoded here, then users of the `image-builder` tool will not be able to override the variable for their OVA builds.

Remove hardcoded VSphere library name

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/types.go

Add library name to VSphere config, so that unmarshaling and re-marshaling preserves the field.

Add library name to VSphere config

---

Common.mk
projects/emissary-ingress/emissary/Makefile
projects/goharbor/harbor/Makefile

Adds clean-go-cache, which was recently added in the eks-distro repo, to be used for cleaning large go build and go mod cache folders. Adding to the emissary build to hopefully avoid the out of space issues that happen from time to time in presubmit. Harbor was already doing a version of this, standardized the two.

Cleans go-cache in presubmit for harbor/emissary

---

Common.mk
Makefile

Locales impact file ordering among other things for programs that are locale aware (most GNU programs are). Consequently, if 2 environments use different locales its possible generated files are inconsistent. This can cause the CI to fail unexpectedly without the ability to reproduce locally.
This change ensures we error with a clear message indicating how to create determinisim.

Patch locale disparities by explicitly erroring for unexpected locales

---

projects/kubernetes-sigs/metrics-server/1-25/HELM_GIT_TAG
projects/kubernetes-sigs/metrics-server/1-25/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
projects/kubernetes-sigs/metrics-server/1-25/helm/patches/0002-Make-imagePullSecrets-top-level-value.patch
projects/kubernetes-sigs/metrics-server/1-25/helm/patches/0003-Make-sourceRegistry-top-level-value.patch
projects/kubernetes-sigs/metrics-server/1-25/helm/schema.json
projects/kubernetes-sigs/metrics-server/1-25/helm/sedfile.template

Adds a 1-25 metrics-server helm chart build.

Add metrics-server 1-25

---

projects/kubernetes-sigs/image-builder/patches/0011-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch

With RedHat 8.7 cloud-init got updated which introduced a race condition where network manager and cloud-init starts around the same time. If cloud-init starts up first without network manager coming up, cloud-init will fail to fetch the datasource and the bootstrapping process will fail. This fix will patch cloud-init's systemd unit to wait for networking manager to come online before starting.
Fixes: https://github.com/aws/eks-anywhere/issues/4282

Patch cloud-init on RHEL to wait for network manager online systemd service

---

UPSTREAM_PROJECTS.yaml
build/lib/generate_staging_buildspec.sh
projects/fluxcd/source-controller/buildspecs/batch-build.yml
release/staging-build.yml

In the staging build we default to the giant instance type for amd which does not exist for arm. We have to specifically set the arm compute type to the normal large.

Sets compute type for arm code build instances

---

Common.mk
Makefile

Patch the locale warning so it only shows when its known to cause an issue, namely on Linux.

Patch locale warning so it only shows when relevant

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/builder.go
projects/aws/image-builder/builder/constants.go
projects/aws/image-builder/builder/types.go
projects/aws/image-builder/cmd/build.go

Adding subnet ID field to configure the subnet/VPC in which Packer launches the builder EC2 instance.

Add subnet ID field to AMI build config

---

build/lib/eksa_releases.sh

https://github.com/aws/eks-anywhere/issues/4724
The curl output should be piped into yq, not the other way around.
Paired with @vignesh-goutham on this fix.
This simply pipes the curl output into yq as intended. At this time, it is unclear why the script just stops at this location, but this fixes it.

Fix for setup-packer-configs-ova error

---

projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh

Require imdsv2 on bare metal build instances.

Add imdsv2 Flags for Bare Metal Image Build

---

projects/kubernetes-sigs/image-builder/patches/0012-Add-instance-metadata-options-to-Packer-config.patch

IMDS configuration options are available for the Packer Amazon EBS builder instance but not exposed as part of upstream image-builder's Packer config. So we need to patch it to make it configurable.

Patch image-builder to add IMDS configuration support for Packer builds

---

Common.mk

[Kustomize](https://github.com/kubernetes-sigs/kustomize) released a new version v5.0.0 today which caused some issues in generating manifests, specifically setting `creationTimestamp` to `"null"` (with quotes). So pinning to an older version to avoid this. 

Pin kustomize version to v4.5.7

---

EKSD_LATEST_RELEASES

* Update to latest release of EKS-D 1.25 (v1.25-eks-5), which upgrades Kubernetes from 1.25.5 to 1.25.6 and includes updates to patches
Side note: release 4 is skipped because it included a minor bug

Updated EKS-D to 1.25-eks-5

---

Common.mk
projects/emissary-ingress/emissary/Makefile
projects/goharbor/harbor/Makefile

Adds cache cleaning to presubmits to help with out-of-space issues as the builder base gets larger

Add cache cleaning target

---

projects/kubernetes-sigs/image-builder/patches/0012-Add-instance-metadata-options-to-Packer-config.patch
projects/kubernetes-sigs/image-builder/patches/0013-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch

This PR adds the option to rename the AMI that gets created by image-builder. The default name is `capa-ami-<OS name>-<kubernetes_semver>-<timestamp>`, changing it to reference CAPAS.

Patch image-builder to rename Snow node AMI

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/builder.go

If the build is running in Codebuild, there is no cloned repo so we don't need to run the cleanup.

Cleanup repo only in non-Codebuild environments

---

projects/tinkerbell/tinkerbell-chart/chart/templates/tink-server/deployment.yaml

TLS is effectively unsupported in Tinkerbell as there's no secure way to establish root of trust. This means we always want to deploy with tls=false.

Add --tls=false to Tinkerbell chart

---

projects/aws/eks-a-admin-image/eks-a-admin-snow.pkr.hcl

Ensuring that [IMDSv2 is enabled](https://developer.hashicorp.com/packer/plugins/builders/amazon/ebs#metadata-settings) in the source AMI that gets launched when building the EKS-A Admin image.

Enforce IMDSv2 in EKS-A Admin image builder AMI

---

projects/kubernetes-sigs/cluster-api-provider-cloudstack/docker/linux/Dockerfile

*Description of changes:* cluster-api-provider-cloudstack cannot run on arm machine because the binary inside the container is wrong

Fix binary format on arm

---

Common.mk
projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
projects/kubernetes-sigs/image-builder/patches/0002-Install-containerd-from-apt-for-Ubuntu.patch
projects/kubernetes-sigs/image-builder/patches/0003-Output-vsphere-builds-to-content-library-instead-of-.patch
projects/kubernetes-sigs/image-builder/patches/0004-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
projects/kubernetes-sigs/image-builder/patches/0005-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
projects/kubernetes-sigs/image-builder/patches/0006-Additional-EKS-A-specific-goss-validations.patch
projects/kubernetes-sigs/image-builder/patches/0007-Tweak-Product-info-in-OVF.patch
projects/kubernetes-sigs/image-builder/patches/0008-Add-support-for-RHEL-8-RAW-image-builds.patch
projects/kubernetes-sigs/image-builder/patches/0009-Support-crictl-validation-from-input-checksum.patch
projects/kubernetes-sigs/image-builder/patches/0010-Exclude-kernel-and-cloud-init-from-yum-updates.patch
projects/kubernetes-sigs/image-builder/patches/0011-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
projects/kubernetes-sigs/image-builder/patches/0012-Add-instance-metadata-options-to-Packer-config.patch
projects/kubernetes-sigs/image-builder/patches/0013-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
projects/kubernetes-sigs/image-builder/patches/0014-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch

Along with the Goss post-build validations included in upstream image-builder, we also have our own validations which verify some EKS-A specific build changes and configurations.  The inline variables for these Goss validations are passed in only for OVA builds (since they were the only images we were building when the patch was added) but they are being set to empty for other providers which caused incorrect var resolutions and false positive errors such as
```
File: /var/cache/etcdadm/etcd//etcd--linux-amd64.tar.gz: exists:Expected <bool>: false to equal <bool>: true
```
This happened because the `etcd` tarball template is `/var/cache/etcdadm/etcd/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz` but `etcd_version` is not passed to the Goss vars list.
This PR fixes this by …

Patch image-builder to fix Goss validations for all EKS-A infra provider image builds

---

projects/kubernetes-sigs/kind/Makefile
projects/kubernetes-sigs/kind/build/create-kind-cluster.sh
projects/kubernetes-sigs/kind/images/kindnetd/Dockerfile

We recently added the iptables-wrapper to the iptables minimal image so we can support iptables-nft as well as iptables-legacy. This changes the kindnetd image to use this new wrapper alternative.
I made a couple small changes to the kind build to facilitate to my testing of this and for next time we need to run similar tests.
I had thought I would need to make changes to the kind image as well to use the wrapper, however turns out we can't use the wrapper for that case. The kind [entrypoint](https://github.com/kubernetes-sigs/kind/blob/main/images/base/files/usr/local/bin/entrypoint#L364) actually uses a version of the old way of detecting iptables mode by counting the number of iptables rules.  I do not think they can use the new style …

Small changes to kind to support iptables-nft

---

projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
projects/kubernetes-sigs/image-builder/patches/0002-Output-vsphere-builds-to-content-library-instead-of-.patch
projects/kubernetes-sigs/image-builder/patches/0003-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
projects/kubernetes-sigs/image-builder/patches/0004-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
projects/kubernetes-sigs/image-builder/patches/0005-Additional-EKS-A-specific-goss-validations.patch
projects/kubernetes-sigs/image-builder/patches/0006-Tweak-Product-info-in-OVF.patch
projects/kubernetes-sigs/image-builder/patches/0007-Add-support-for-RHEL-8-RAW-image-builds.patch
projects/kubernetes-sigs/image-builder/patches/0008-Support-crictl-validation-from-input-checksum.patch
projects/kubernetes-sigs/image-builder/patches/0009-Exclude-kernel-and-cloud-init-from-yum-updates.patch
projects/kubernetes-sigs/image-builder/patches/0010-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
projects/kubernetes-sigs/image-builder/patches/0011-Add-instance-metadata-options-to-Packer-config.patch
projects/kubernetes-sigs/image-builder/patches/0012-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
projects/kubernetes-sigs/image-builder/patches/0013-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch
projects/kubernetes-sigs/image-builder/patches/0014-Use-tar.gz-extension-for-CNI-plugins-tarball.patch

Adding back part of a patch removed in #1958.

Re-add patch to use tar.gz extension for CNI plugins tarball

---

build/lib/common.sh
projects/aws/eks-a-admin-image/build/export-ami-to-s3.sh
projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh

The upstream image-builder AMI packer.json has a throughput field by default in the block device mappings section but this field is valid only for `gp3` volumes type. Hence, when specifying any non-gp3 volume in the AMI config for image-builder, the image build fails throwing an error that throughput is not valid for non-gp3 volume types. This occurs even if we override throughput to `null` or `""` via Packer var-files. The only solution is to remove the throughput field from the Packer config. This PR adds logic to conditionally remove or add back the throughput field depending on the volume type.
This approach is used in upstream image-builder as well and was confirmed by one of their maintainers. Refer to kubernetes-sigs/image-builder#1102 for the original issue I raised regarding …

Support non-gp3 volumes in AMI image builds

---

projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh

Bash fails the check `[[ "gp3" != \g\p\3 ]]`.

Get raw string from jq

---

Common.mk
build/lib/common.sh
build/lib/create_release_checksums.sh
build/lib/upload_artifacts.sh
build/lib/validate_artifacts.sh
projects/kubernetes-sigs/image-builder/.gitignore
projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
projects/kubernetes-sigs/image-builder/build/get_bottlerocket_artifacts.sh
projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
projects/kubernetes-sigs/image-builder/build/upload_bottlerocket_artifacts.sh
projects/kubernetes-sigs/image-builder/buildspecs/ami.yml
projects/kubernetes-sigs/image-builder/buildspecs/cloudstack.yml
projects/kubernetes-sigs/image-builder/buildspecs/ova.yml
projects/kubernetes-sigs/image-builder/buildspecs/raw.yml

We issues in codebuild when building release branches which do not have the newer versions of kube. This is an attempt to check for that, like we do for project_path for new projects, so we can bail out early
~https://github.com/aws/eks-distro-prow-jobs/pull/491~
https://github.com/aws/eks-anywhere-prow-jobs/pull/273

Adds guard around image builds for newer kube versions

---

Makefile
projects/aws/bottlerocket-bootstrap/Help.mk
projects/aws/bottlerocket-bootstrap/Makefile
projects/emissary-ingress/emissary/Makefile
projects/fluxcd/source-controller/Makefile
projects/kubernetes-sigs/image-builder/Help.mk
projects/kubernetes-sigs/kind/Help.mk
projects/kubernetes/autoscaler/Help.mk
projects/kubernetes/cloud-provider-vsphere/Help.mk
projects/metallb/metallb/Makefile
projects/prometheus/node_exporter/Makefile
projects/prometheus/prometheus/Makefile
projects/tinkerbell/hegel/Makefile
projects/tinkerbell/rufio/Makefile

Kind of a weird thing, but doesnt affect too much what version is in the help, we just need a version.

Use 1.26 for generated help.mk files

---

projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
projects/kubernetes-sigs/image-builder/patches/0002-Output-vsphere-builds-to-content-library-instead-of-.patch
projects/kubernetes-sigs/image-builder/patches/0003-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
projects/kubernetes-sigs/image-builder/patches/0004-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
projects/kubernetes-sigs/image-builder/patches/0005-Additional-EKS-A-specific-goss-validations.patch
projects/kubernetes-sigs/image-builder/patches/0006-Tweak-Product-info-in-OVF.patch
projects/kubernetes-sigs/image-builder/patches/0007-Add-support-for-RHEL-8-RAW-image-builds.patch
projects/kubernetes-sigs/image-builder/patches/0008-Support-crictl-validation-from-input-checksum.patch
projects/kubernetes-sigs/image-builder/patches/0009-Exclude-kernel-and-cloud-init-from-yum-updates.patch
projects/kubernetes-sigs/image-builder/patches/0010-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
projects/kubernetes-sigs/image-builder/patches/0011-Add-instance-metadata-options-to-Packer-config.patch
projects/kubernetes-sigs/image-builder/patches/0012-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
projects/kubernetes-sigs/image-builder/patches/0013-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch
projects/kubernetes-sigs/image-builder/patches/0014-Use-tar.gz-extension-for-CNI-plugins-tarball.patch
projects/kubernetes-sigs/image-builder/patches/0015-bump-containerd-to-1.6.19.patch

Backported from upstream. We use containerd from upstream now for ubtunu to match rhel builds so we need to keep this update to ourselves.

Bumps containerd for image builds

---

projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
projects/kubernetes-sigs/image-builder/patches/0002-Output-vsphere-builds-to-content-library-instead-of-.patch
projects/kubernetes-sigs/image-builder/patches/0003-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
projects/kubernetes-sigs/image-builder/patches/0004-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
projects/kubernetes-sigs/image-builder/patches/0005-Additional-EKS-A-specific-goss-validations.patch
projects/kubernetes-sigs/image-builder/patches/0006-Tweak-Product-info-in-OVF.patch
projects/kubernetes-sigs/image-builder/patches/0007-Add-support-for-RHEL-8-RAW-image-builds.patch
projects/kubernetes-sigs/image-builder/patches/0008-Support-crictl-validation-from-input-checksum.patch
projects/kubernetes-sigs/image-builder/patches/0009-Exclude-kernel-and-cloud-init-from-yum-updates.patch
projects/kubernetes-sigs/image-builder/patches/0010-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
projects/kubernetes-sigs/image-builder/patches/0011-Add-instance-metadata-options-to-Packer-config.patch
projects/kubernetes-sigs/image-builder/patches/0012-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
projects/kubernetes-sigs/image-builder/patches/0013-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch
projects/kubernetes-sigs/image-builder/patches/0014-Use-tar.gz-extension-for-CNI-plugins-tarball.patch
projects/kubernetes-sigs/image-builder/patches/0015-Ensure-the-correct-Packer-binary-is-used-for-image-b.patch

Ref: kubernetes-sigs/image-builder#1108

Add patch to ensure correct Packer binary is used for image builds

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
projects/kubernetes-sigs/image-builder/BOTTLEROCKET_CONTROL_CONTAINER_METADATA
projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES

v1.13.0 disables udp offloading in vSphere, which was causing udp packets to be dropped in some vSphere environments.
BR Release: https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.13.0
BR Release tracking ticket: https://github.com/bottlerocket-os/bottlerocket/issues/2760
PR with fix: https://github.com/bottlerocket-os/bottlerocket/pull/2850

Update BR Images to v1.13.0

---

projects/kubernetes/autoscaler/1-23/CHECKSUMS
projects/kubernetes/autoscaler/1-23/patches/0002-Fix-CVE-2022-1996-for-1.23.patch

Fixes https://nvd.nist.gov/vuln/detail/CVE-2022-1996, present in Cluster Autoscaler v1.23.

Fix CVE-2022-1996 for Cluster Autoscaler 1-23

---

projects/torvalds/linux/Makefile

We ran into an issue yesterday when we switched our builder instance platform for this build in codebuild to arm.  Because its a native build, the compile step is always going to compile based on the current arch.  We only caught this after trying to boot a machine on amd using a bootconfig bin built for arm.  This small change will force it to always build to a platform folder which matches the current host and therefore when creating the tar will have the proper arch.  If we had this in place yesterday, instead of overwriting the amd bin with an arm based on, we would have just pushed a new arm one.
On one hand that scenario may have been harder to catch, however, we never would have broke anything instead we would have noticed the next …

Small improvement to bootconfig build to ensure arch is expected

---

projects/kubernetes-sigs/cluster-api-provider-vsphere/CHECKSUMS
projects/kubernetes-sigs/cluster-api-provider-vsphere/patches/0004-Fix-vCenter-session-leaks.patch
projects/kubernetes-sigs/cluster-api-provider-vsphere/patches/0005-Fixup-Fix-vCenter-session-leaks.patch

Applies patch from this fix for leaky sessions: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1767
Fixes a problem with leaky sessions in capv.

Fix Leaky capv vSphere Sessions

---

projects/kubernetes/autoscaler/1-22/ATTRIBUTION.txt
projects/kubernetes/autoscaler/1-22/CHECKSUMS
projects/kubernetes/autoscaler/1-22/patches/0002-Fix-CVE-2022-1996-for-1.22.patch
projects/kubernetes/autoscaler/1-22/patches/0003-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
projects/kubernetes/autoscaler/1-22/patches/0004-Remove-Deps-for-Other-Cloud-Providers.patch
projects/kubernetes/autoscaler/1-23/ATTRIBUTION.txt
projects/kubernetes/autoscaler/1-23/CHECKSUMS
projects/kubernetes/autoscaler/1-23/patches/0003-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
projects/kubernetes/autoscaler/1-23/patches/0004-Remove-Deps-for-Other-Cloud-Providers.patch
projects/kubernetes/autoscaler/1-24/CHECKSUMS
projects/kubernetes/autoscaler/1-24/patches/0004-Fix-CVE-2022-1996-for-1.24.patch
projects/kubernetes/autoscaler/1-24/patches/0005-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
projects/kubernetes/autoscaler/1-24/patches/0006-Remove-Deps-for-Other-Cloud-Providers.patch
projects/kubernetes/autoscaler/1-25/CHECKSUMS
projects/kubernetes/autoscaler/1-25/patches/0002-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
projects/kubernetes/autoscaler/1-25/patches/0003-Remove-Deps-for-Other-Cloud-Providers.patch
projects/kubernetes/autoscaler/1-26/CHECKSUMS
projects/kubernetes/autoscaler/1-26/patches/0001-Remove-Cloud-Provider-Builders-Except-Cluster-API.patch
projects/kubernetes/autoscaler/1-26/patches/0002-Update-go.mod-Dependencies.patch
projects/kubernetes/autoscaler/Makefile
projects/kubernetes/autoscaler/README.md

https://github.com/aws/eks-anywhere-build-tooling/issues/2084
https://github.com/aws/eks-anywhere-build-tooling/issues/2092
This PR strips out unused cloud providers from cluster autoscaler.
The immediate benefit is that https://github.com/aws/eks-anywhere-build-tooling/issues/2084 is resolved.
Longer term, this should reduce our surface area for future CVEs.
This PR also includes fixes for https://github.com/aws/eks-anywhere-build-tooling/issues/2092 in 1-22 and 1-24 autoscaler images. I can separate this into a different PR if we want.

Remove Unused Autoscaler Cloud Providers

---

projects/tinkerbell/rufio/CHECKSUMS
projects/tinkerbell/rufio/patches/0001-Adding-Using-to-select-bmc-lib-drivers-for-client.patch

bmc-lib tries to establish a connection to check compatible protocols (redfish, ipmi etc) for all supported implementations. These changes modify Rufio to only use `Redfish` and `IPMI` protocols for all hardware.
Rufio opens a new connection via bmc-lib for every reconcile loop. In the latest version of bmc-lib support for IntelAMT protocol was added. It was noticed that on older hardware when users try to run Rufio, IntelAMT takes too long to establish a connection and hence blocks the reconcile thread. This was causing timeouts of Rufio Tasks when it exceeded 3 mins to hit the connection timeout. 
Fixes:
Timeout issues on older hardware due to Rufio reconcile threads getting blocked when bmc-lib provider open connection calls hang and timeout. 
`make docker-build` and tested the …

Adding a patch to limit rufio bmclib drivers

---

projects/kubernetes-sigs/kind/images/base/kubeadm.config.tmpl

In 1.27 `kubeadm.k8s.io/v1beta2` is removed, after being deprecated since 1.22.  Luckily we are only supporting 1.22+ at this point so we can just bump to beta3 and still support all versions, vs needing some kind of conditional.  
For reference, this particular config is only used during image build time to get the list of kube images that need to be downloaded and embedded in the kind image.  Before the build is over, this config is removed from the final image.
Similar to https://github.com/aws/eks-anywhere/pull/3014 but we can't just remove the api version in this case.  The reason we could remove it during the cli flow is because it calls kind instead of kubeadm directly and the kind code augments the config we pass with additional …

Removes kubeadm config version during kind build

---

projects/aws/eks-a-admin-image/eks-a-admin-snow.pkr.hcl

Most public AMIs matching the filter `amzn2-ami-kernel-5.*-hvm-2*` come in both AMD64 and ARM64 variants, where the build chooses the AMD64 variant. However filtering for the latest AL2 Kernel 5.10 AMI returned only one source AMI (`ami-0ae285eae0f72f673`) which was ARM64, and caused the build to fail with the message
```
Error launching source instance: InvalidParameterValue: The architecture 'x86_64' of the specified instance
type does not match the architecture 'arm64' of the specified AMI. Specify an instance type and an AMI that
have matching architectures, and try again. You can use 'describe-instance-types' or 'describe-images' to
discover the architecture of the instance type or AMI.
```
So we need to filter for an AMD64 source AMI even if it means we get a slightly older AMI.
By …

Ensure source AMI architecture is AMD64

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
projects/kubernetes-sigs/image-builder/BOTTLEROCKET_CONTROL_CONTAINER_METADATA
projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES

- Updating BR version to 0.14.0
Based on https://github.com/bottlerocket-os/bottlerocket/blob/develop/sources/models/shared-defaults/public-host-containers.toml:
- Updating admin container to 0.10.1
- Updating host container to 0.7.2

Update BR release version and admin container

---

EKSD_LATEST_RELEASES

Automatic cherry pick from https://github.com/aws/eks-anywhere-build-tooling/pull/2160 failed due to main having 1.27. Simple cherry-pick, removing the 1.27 block since 0.15 does not have 1.27 support.

Updated EKS-D to latest releases (#2160)

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh

Copy cloudstack artifacts from metal EC2 instance to codebuild job to finally upload it on the s3 bucket.

copy cloudstack artifacts from metal EC2 instance to codebuild job

---

projects/tinkerbell/hub/CHECKSUMS
projects/tinkerbell/hub/patches/0009-Use-MAC-address-in-Bottlerocket-network-config.patch

This adds flexibility across hardware machines for the Bottlerocket network config.
This has been manually tested against HPE ProLiant DL160 Gen10 and have been successfully provisioning.
Fixes: https://github.com/aws/eks-anywhere/issues/3411

Use MAC addr in Bottlerocket net conf

---

projects/kubernetes/autoscaler/1-27/helm/patches/0007-Authorize-MachinePool-Operations.patch

https://github.com/kubernetes/autoscaler/pull/4676 introduced a bug to the cluster autoscaler clusterapi reconciler.
The cluster autoscaler executable attempts to reconcile MachinePool resources, but does not have sufficient permissions to do so in its ClusterRole.
Adds a patch to the helm chart's ClusterRole to properly list and watch MachinePool resources.
*Testing*
Manually applied these changes to a deployed helm chart and saw cluster autoscaler begin properly reconciling.

Fix 1-27 Cluster Autoscaler Reconciling Error

---

build/lib/create_release_checksums.sh
build/lib/validate_artifacts.sh

During the artifact validation phase of the build, there are a couple spots where we use realpath --relative-base which is not support on mac.  This adds a fallback to `grealpath` which comes with `brew install coreutils` similar to how we handle `find` in a few places where we rely on behavior that does not exist on mac's version of these utils.

adds support for grealpath on mac

---

build/lib/common.sh
build/lib/fetch_binaries.sh
projects/aws/eks-anywhere-packages/Makefile
projects/aws/eks-anywhere-packages/docker/linux/credentialprovider/Dockerfile
projects/aws/eks-anywhere-packages/docker/linux/eks-anywhere-packages/Dockerfile
release/checksums-build.yml
release/staging-build.yml

`eks-anywhere-packages` has a dependency `eksa/kubernetes/cloud-provider-aws` which is K8 version specific. Therefore, we need to modify `eks-anywhere-packages` to support branches, and also able to read dependencies that are K8 version specific, which requires an update to `build::common::get_latest_eksa_asset_url()`

Split eks-anywhere-packages to have K8 version specific builds

---

build/lib/common.sh
build/lib/fetch_binaries.sh
projects/aws/eks-anywhere-packages/Makefile
projects/aws/eks-anywhere-packages/docker/linux/credentialprovider/Dockerfile
projects/aws/eks-anywhere-packages/docker/linux/eks-anywhere-packages/Dockerfile
release/staging-build.yml

After further evaluation, we have decided to revert the changes on making eks-anywhere-packages k8 version specific, and instead adding two different versions of ecr-credential-provider into the credential-provider image.

Make eks-anywhere-packages k8 version agnostic

---

projects/tinkerbell/hub/CHECKSUMS
projects/tinkerbell/hub/patches/0010-Handle-non-200-status-codes-from-metadata-service.patch

Fixes https://github.com/aws/eks-anywhere/issues/5564
When the Hegel metadata service doesn't have a Hardware record it returns 404. Our writefile Tinkerbell action treats the 404 as OK resulting in invalid metadata being written to disk and ultimately consumed by kubelet on launch, causing it to fail.
This change treats non-200 responses as errors ensuring we move to query any additional metadata endpoints.

Fix metadata service queries treating 404s as OK

---

EKSD_LATEST_RELEASES

The Kubernetes version corresponding to the latest EKS-D v1.24 release is `v1.24.15`.
```bash
curl -sL https://distro.eks.amazonaws.com/kubernetes-1-24/kubernetes-1-24-eks-20.yaml | yq ".status.components[] | select(.name==\"kubernetes\")".gitTag
v1.24.15
```

Fix Kubernetes version for EKS-D v1.24 latest release

---

EKSD_LATEST_RELEASES

Backporting #2260 and #2262 to release-0.16.

Backport EKS-D kube version updates

---

projects/emissary-ingress/emissary/patches/0001-patching_helm_charts_packages.patch

Fixing config issue emissary helm chart

---

Makefile
build/lib/validate_eksd_releases.sh

adds validation for eks-d releases file

---

build/lib/common.sh
build/lib/simple_create_tarballs.sh

We needed this that was reverted in the kind update PR [revert](https://github.com/aws/eks-anywhere-build-tooling/pull/2277/files#diff-a5ed650d97e91497a26f14a346a388676aba4e377ea1efff495154c860b3171b)

brings back fix for kind tarballs due to license file overwrites

---

projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
projects/kubernetes-sigs/image-builder/patches/0002-Output-vsphere-builds-to-content-library-instead-of-.patch
projects/kubernetes-sigs/image-builder/patches/0003-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
projects/kubernetes-sigs/image-builder/patches/0004-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
projects/kubernetes-sigs/image-builder/patches/0005-Additional-EKS-A-specific-goss-validations.patch
projects/kubernetes-sigs/image-builder/patches/0006-Tweak-Product-info-in-OVF.patch
projects/kubernetes-sigs/image-builder/patches/0007-Support-crictl-validation-from-input-checksum.patch
projects/kubernetes-sigs/image-builder/patches/0008-Exclude-kernel-and-cloud-init-from-yum-updates.patch
projects/kubernetes-sigs/image-builder/patches/0009-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
projects/kubernetes-sigs/image-builder/patches/0010-Add-instance-metadata-options-to-Packer-config.patch
projects/kubernetes-sigs/image-builder/patches/0011-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
projects/kubernetes-sigs/image-builder/patches/0012-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch
projects/kubernetes-sigs/image-builder/patches/0013-Use-tar.gz-extension-for-CNI-plugins-tarball.patch
projects/kubernetes-sigs/image-builder/patches/0014-uses-latest-ubuntu-22.04-iso.patch
projects/kubernetes-sigs/image-builder/patches/0015-Shrink-qemu-ubuntu-image-size.patch
projects/kubernetes-sigs/image-builder/patches/0016-adds-support-for-raw-ubuntu-22.04-builds.patch
projects/kubernetes-sigs/image-builder/patches/0017-sets-OS_VERSION-for-goss-validation-on-raw-image-bui.patch
projects/kubernetes-sigs/image-builder/patches/0018-adds-disable-udp-service-for-redhat-on-vmware.patch

When updating to cilium 1.12 we ran into the udp overload issue on vmware with Redhat 8. We have seen this problem off an on, seems to depend on the specific version of vpshere, with BR for a while due to their use are pretty new kernels.  Recently they implemented a [solution](https://github.com/bottlerocket-os/bottlerocket/pull/2850) by disabling udp offloading.  There is also potentially some official [guidance](https://github.com/cilium/cilium/issues/21801) coming from the cilium community on this issue for vmware environments. 
This patches our build of image builder to add a similar systemd unit to the Redhat build for vmware.  @taneyland has tested this manually.
By submitting this pull request, I confirm that you can use, modify, …

disables udp offload on redhat for vwmare

---

build/lib/eksa_releases.sh
projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/utils.go

*Issue #, if available:* `build --os ubuntu --hypervisor baremetal --release-channel 1-24` cannot run because it fails to fetch git commit
*Description of changes:* fix the command to fetch git commit

Fix getting git commit from bundle cmd

---

projects/kubernetes-sigs/etcdadm/CHECKSUMS
projects/kubernetes-sigs/etcdadm/patches/0004-Support-pulling-etcd-from-EKS-D.patch

Etcdadm defaults to github.com to pull etcd binaries when the input etcd version and the version available in the cache dir doesn't match. This change allows etcdadm to pull from EKS-D as well as support pulling from a complete etcd release url as opposed to deriving complete full path url from hostname + etcd version. This will help EKS-A set complete full url to etcd release from EKS-D.
*Test runs*
Without release url
```
ubuntu@ip-172-31-7-153:~$ sudo ./etcdadm init --init-system systemd --version 3.5.7 --install-dir /usr/bin
2023-07-12 16:10:31.205303 I | [install] Artifact not found in cache. Trying to fetch from upstream: https://distro.eks.amazonaws.com/kubernetes-1-27/releases/7/artifacts/etcd
INFO[0000] [install] Downloading & installing etcd …
```

Support etcdadm pulling from EKS-D

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/builder.go

Provide full absolute path to additional files config so that Packer doesn't prefix it with the upstream path.

Provide full path to additional files config

---

projects/kubernetes-sigs/image-builder/build/build_image.sh

Remove default additional files params for AMI builds.

Remove default additional files params for AMI builds

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/constants.go

These were getting prefixed with the image-builder project path so we don't need those folders in this path.

Fix absolute path for Snow AMI scripts

---

projects/kubernetes-sigs/kind/Makefile
projects/kubernetes-sigs/kind/README.md
projects/kubernetes-sigs/kind/manifests/kindnetd.yaml

When we split the build for kind out between binaries and images we actually broke the kindnetd manifest since that is only produced during the image build. This switches to having it hardcoded, like cert-manager. As a follow, we can automate this again.

fix kindnetd manifest

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/utils.go

Backportting from main so we can produce a 0.16.x build that actually works.

Backport image-builder cli fix for getting bundle

---

build/lib/eksa_releases.sh

Removing the readonly flag at variable declaration.

Make EKS-A release version mutable in script

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/builder.go
projects/aws/image-builder/builder/constants.go
projects/aws/image-builder/builder/utils.go
projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh

This feature was added in #2312 but inadvertently removed in the refactor done in #2361.

Support dev release image builds from prod image-builder

---

projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
projects/kubernetes-sigs/image-builder/packer/nutanix/nutanix.json
projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
projects/kubernetes-sigs/image-builder/patches/0002-Output-vsphere-builds-to-content-library-instead-of-.patch
projects/kubernetes-sigs/image-builder/patches/0003-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
projects/kubernetes-sigs/image-builder/patches/0004-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
projects/kubernetes-sigs/image-builder/patches/0005-Additional-EKS-A-specific-goss-validations.patch
projects/kubernetes-sigs/image-builder/patches/0006-Tweak-Product-info-in-OVF.patch
projects/kubernetes-sigs/image-builder/patches/0007-Support-crictl-validation-from-input-checksum.patch
projects/kubernetes-sigs/image-builder/patches/0008-Exclude-kernel-and-cloud-init-from-yum-updates.patch
projects/kubernetes-sigs/image-builder/patches/0009-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
projects/kubernetes-sigs/image-builder/patches/0010-Add-instance-metadata-options-to-Packer-config.patch
projects/kubernetes-sigs/image-builder/patches/0011-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
projects/kubernetes-sigs/image-builder/patches/0012-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch
projects/kubernetes-sigs/image-builder/patches/0013-Use-tar.gz-extension-for-CNI-plugins-tarball.patch
projects/kubernetes-sigs/image-builder/patches/0014-uses-latest-ubuntu-22.04-iso.patch
projects/kubernetes-sigs/image-builder/patches/0015-Shrink-qemu-ubuntu-image-size.patch
projects/kubernetes-sigs/image-builder/patches/0016-adds-support-for-raw-ubuntu-22.04-builds.patch
projects/kubernetes-sigs/image-builder/patches/0017-sets-OS_VERSION-for-goss-validation-on-raw-image-bui.patch
projects/kubernetes-sigs/image-builder/patches/0018-Disable-UDP-offload-service-for-Redhat-and-Ubuntu.patch
projects/kubernetes-sigs/image-builder/patches/0019-Pin-packer-plugin-nutanix-to-v0.7.1.patch

* Providing default value for EKSA_USE_DEV_RELEASE variable so that we don't get unbound variable errors.
* Pinning packer-plugin-nutanix to version v0.7.1 so that we avoid including [this change](https://github.com/nutanix-cloud-native/packer-plugin-nutanix/pull/142) that breaks presubmits due to empty configs.

Provide default value for EKSA_USE_DEV_RELEASE variable

---

projects/kubernetes-sigs/image-builder/patches/0014-uses-latest-ubuntu-22.04-iso.patch
projects/kubernetes-sigs/image-builder/patches/0016-adds-support-for-raw-ubuntu-22.04-builds.patch

Ubuntu released 22.04.3 today 3 hours ago and they migrated version 22.04.2 to the old-releases CDN, hence 22.04 builds can't find the 22.04.2 ISO image to pull from the current URL. Hence configuring the `iso_url` to be the old releases URL.
```bash
$ curl -sIo /dev/null  -w "%{http_code}" https://releases.ubuntu.com/22.04/ubuntu-22.04.2-live-server-amd64.iso
404
$ curl -sIo /dev/null -w "%{http_code}" https://old-releases.ubuntu.com/releases/jammy/ubuntu-22.04.2-live-server-amd64.iso  
200
```

Point ISO URL to Ubuntu old releases CDN

---

build/lib/eksa_releases.sh
projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh

Backport image-builder script enhancements to release-0.16 that would allow building images for older EKS-A releases from newer versions of image-builder.

Backport script changes to support cross-version image builds

---

projects/kubernetes-sigs/kind/CHECKSUMS
projects/kubernetes-sigs/kind/patches/0005-TEMP-lock-containerd-and-runc-version.patch

Follow up to https://github.com/aws/eks-anywhere-build-tooling/pull/2406
Tested this on Al2 and the newer containerd version does not seem to be a problem.  This makes sense because the issue we looks very much like the runc 1.1.6/1.1.7 misc controller issue seen in kind/kubernetes.

do not lock containerd version

---

projects/tinkerbell/hub/CHECKSUMS
projects/tinkerbell/hub/patches/0012-Allow-BOOTCONFIG_CONTENTS-and-CONTENTS-to-be-checked.patch

Add patch for writefile action to fix issue when `CONTENTS` is not set but `BOOTCONFIG_CONTENTS` is set.

Add patch for writefile action

---

projects/aws/eks-a-admin-image/build/export-ami-to-s3.sh

Enabling Inspector V2 scan for EKS-A Admin AMI by first launching an EC2 instance from the AMI and then running the scan on the running instance.

Enable Inspector V2 scan for EKS-A Admin AMI

---

projects/aws/eks-a-admin-image/build/export-ami-to-s3.sh

Fix loop in export AMI script.

Fix loop in export AMI script

---

projects/kubernetes-sigs/image-builder/patches/0020-Add-dracut-cmd-to-generate-initramfs-with-all-driver.patch

*Issue* #2462 
Raw builds are run on KVM vms. RHEL 8.x ships with dracut that builds initramfs with default host-only mode set to true. This causes the initramfs to only include drivers that are required to run kvm infrastructure. When the disks are exported and booted on a metal server, the OS fails to boot up due to this missing drivers.
This change runs dracut with --no-hostonly to rebuild initramfs to include all drivers
This PR also fixes another issue that bubbled up during testing the dracut changes. The build_type was not set to raw in the rhel json file, causing providers role to run qemu tasks as opposed to raw tasks.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

Add dracut cmd to generate initramfs with drivers for RHEL raw builds

---

projects/kubernetes-sigs/image-builder/README.md
projects/kubernetes-sigs/image-builder/patches/0021-Add-proxy-register-with-satellite-and-pull-packages-.patch

#2466, #2467, #2468 
[Subscription module](https://docs.ansible.com/ansible/latest/collections/community/general/redhat_subscription_module.html) doesnt consume the proxy environment vars. This change make image-builder provide a specific proxy input for subscription module.
Change also adds support to register build vm against RedHat Satellite as opposed to reaching out to RedHat CDNs, and pull packages from the Satellite vs pulling from public repositories.

Add proxy, register & pull packages from RedHat Satellite

---

projects/aws/image-builder/builder/builder.go
projects/aws/image-builder/builder/constants.go
projects/aws/image-builder/builder/types.go
projects/aws/image-builder/builder/utils.go
projects/aws/image-builder/cmd/build.go

https://github.com/aws/eks-anywhere-build-tooling/issues/2466, https://github.com/aws/eks-anywhere-build-tooling/issues/2467, https://github.com/aws/eks-anywhere-build-tooling/issues/2468
Image builder cli changes to pass values for proxy and redhat Satellite use. Refer image-builder PR https://github.com/aws/eks-anywhere-build-tooling/pull/2485 for more details

Image builder proxy and redhat satellite changes for RedHat Subscription Management

---

projects/aws/image-builder/builder/types.go

*Issues addressed:*
* #2301 
* #2372
As per https://github.com/kubernetes-sigs/image-builder/issues/894 issue upstream project opened to use custom Ansible roles pre/post boot of the node and also pre/post node provisioning.
This opens doors to customize image built for custom requirements, for example if deployment needs to happen in offline environment that has no access to the internet and would require to update system with required changes to look for packages on internal proxies instead.
Also allows to provide extra updates to the system before Kubernetes is installed along with extra tweaks after.

Adds pre/post boot and node roles

---

projects/kubernetes-sigs/image-builder/patches/0022-Ubuntu-switch-to-offline-install-when-mirrors-are-un.patch

Image builder tries Ubuntu mirrors when installing the OS from ISO onto vm. This change prevents failing the install when mirrors are unreachable, and proceeds to install only from the ISO.

Install Ubuntu offline when mirrors are unreachable

---

projects/kubernetes-sigs/image-builder/patches/0023-Default-Flatcar-version-to-avoid-pulling-from-intern.patch

On every image-builder make command, make pulls the manifest json to determine the latest Flatcar version. This is an issue when trying to run airgapped builds. This change defaults the version to the current latest.

Default Flatcar version to avoid polling internet on all make commands

---

config/docker-ecr-config.json

Add packages ECR to `credHelpers` list for `amazon-ecr-credential-helper` to use for authentication to ECR.

Add packages ECR to credHelpers list

---

Common.mk

`make check-for-release-branch-skip` uses `SKIP_ON_RELEASE_BRANCH` from a project's makefile, but metric-server's makefile has `HELM_GIT_TAG:=$(shell cat $(RELEASE_BRANCH)/HELM_GIT_TAG)`, so this make target always fails. 
Added `check-for-release-branch-skip` target to TARGETS_ALLOWED_WITH_NO_RELEASE_BRANCH

Fix Build Metrics Server 1-28

---

Common.mk
Makefile

Small change, but I am going thru and trying to make as many shell calls as possible to deferred vars in Common.mk.  We end up calling make quite a lot, like when generating staging configs and the shell execs add up.

improves local check by turning into a prereq

---

Common.mk

skips buildkit check in codebuild

---

Common.mk
Makefile
build/lib/make_shell_trace.sh

To help track usage of shell exec's via our common.mk/makefiles, adds a SHELL_TRACE variable to override the shell to a bash script which just echos args before exec-ing.

adds shell trace to common.mk

---

projects/aws/image-builder/builder/builder.go
projects/aws/image-builder/builder/constants.go
projects/aws/image-builder/builder/manifests.go
projects/aws/image-builder/builder/utils.go
projects/aws/image-builder/cmd/download.go
projects/aws/image-builder/cmd/downloadmanifests.go

Adds a download manifest command that will pull down all the latest eks-d manifests as well as the eks-a release manifest and all the bundles manifest. Command will create a tarball from all the manifests and finally cleanup.
```
image-builder download manifest
```
Last few lines of output
```
2023/10/09 18:58:01 Downloading eks-a bundles manifest for eks-a version: v0.16.4
2023/10/09 18:58:01 Downloading eks-a bundles manifest for eks-a version: v0.16.5
2023/10/09 18:58:01 Downloading eks-a bundles manifest for eks-a version: v0.17.0
2023/10/09 18:58:01 Downloading eks-a bundles manifest for eks-a version: v0.17.1
2023/10/09 18:58:01 Downloading eks-a bundles manifest for eks-a version: v0.17.2
2023/10/09 18:58:02 Downloading eks-a bundles manifest for eks-a …
```

[Image Builder] Add download manifest command for airgapped builds

---

projects/aws/image-builder/builder/builder.go

Fix output image glob pattern for CloudStack image builds.
```
==> Builds finished. The artifacts of successful builds are:
--> qemu: VM files in directory: ./output/rhel-8-kube-v1.28.1
--> qemu: VM files in directory: ./output/rhel-8-kube-v1.28.1
--> qemu: VM files in directory: ./output/rhel-8-kube-v1.28.1
```

Fix output image glob pattern for CloudStack image builds

---

projects/aws/image-builder/builder/builder.go

The "fix" in #2565 actually failed Cloudstack builds because these builds, unlike OVA and Raw image builds, output their final build artifacts in the location `output/build-name/build-name`. OVA and Raw also generate similar files in a nested `build-name` directory but due to post processing (compression/archival), the final artifacts end up as `output/build-name.ova` and `output/build-name.gz`. No such post-processing occurs for cloudstack, so the output artifact is the QCOW2 image in `output/build-name/build-name` (without extension).

Revert changes to CloudStack output glob

---

build/lib/eksa_releases.sh

Setting `EKSA_BUNDLE_MANIFEST_URL` environment variable overrides url found by parsing eks-a release manifest. Removing readonly flag from the variable in order set the override manifest url.

Fix readonly variable for bundles url override

---

Common.mk
build/lib/common.sh
projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh

- stop showing s3 upload progress. for image uploading it overloads the logs and its unnecessary
- extract the br raw image requires lz4
- avoid removing the downloaded files because they are intermediate targets. the fix is a bit ugly and this is a pretty minor case, it really only comes up when running locally multiple times, but feels like a low risk to avoid some "strange" behavior that I have to re-remember every time.
- improve the host interface for the packer host IP detection

minor image builder improvements

---

Makefile
build/lib/generate_staging_buildspec.sh
projects/aws/bottlerocket-bootstrap/buildspecs/batch-build.yml
projects/aws/rolesanywhere-credential-helper/Makefile
projects/containerd/containerd/buildspecs/batch-build.yml
projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
projects/kubernetes/cloud-provider-aws/Makefile
projects/kubernetes/cloud-provider-vsphere/buildspecs/batch-build.yml
projects/opencontainers/runc/buildspecs/batch-build.yml
projects/torvalds/linux/buildspecs/batch-build.yml
release/checksums-build.yml
release/staging-build.yml

The `buildspec` field in each build task of the batch build definition is an optional parameter, and if not provided, the current buildspec file is used to determine the phases, commands, etc. This PR adds the default buildspec definition in each batch buildspec so that we don't need to specify it again and again. The change is especially noticeable in the staging and checksums buildspecs which have 60+ build tasks each referencing the same buildspec file. Instead we can add the default phases/commands in the batch buildspec itself.

Add default buildspec definition to batch buildspecs

---

projects/tinkerbell/hub/CHECKSUMS
projects/tinkerbell/hub/patches/0013-Fix-net-interface-lookup.patch

#2217 
This is a patch that fixes an issue configuring static network interfaces when multiple configured interfaces exist when the action is run (on HookOS).  The current behavior is to take the first configured interface. This might not be the one tracked by the Tinkerbell stack. As a consequence of that, the static network configs will not be populated accurately and cause the system to either not boot or boot with the incorrect IP info.
This change was successful when tested manually.

Fix interface determination in Tinkerbell writefile action

---

projects/aws/image-builder/builder/builder.go

From EKSA version - 0.18, template specified in the spec is expected to contain the corresponding K8s version as a pre-flight validation. For a smooth transition, this change patches the image-builder to add Kube version and the os release information in the output file.  

Add kube version and os version info in the output file

---

projects/aws/image-builder/README.md
projects/aws/image-builder/builder/builder.go
projects/aws/image-builder/builder/constants.go
projects/aws/image-builder/builder/manifests.go
projects/aws/image-builder/builder/types.go
projects/aws/image-builder/builder/utils.go
projects/aws/image-builder/cmd/build.go

Support for air gapped image building. This change includes image builder cli changes to build an airgapped OS.
- Extracts the manifest tarball generated with internet availability
- Replaces the domains in the extracted manifests pointing to the internal artifact endpoints
- Ensures airgapped packer vars are set 
- extra_repos
- iso_url
- iso_checksum
- iso_checksum_type
- disable_public_repos
- Sets the right env var to point to the extracted manifests for EKS-D release bundle for provided release channel
Changes are actively being tested.

Support for Air-gapped Image building

---

projects/aws/image-builder/cmd/build.go

We should validate the airgapped configuration only if running builds in airgapped mode

Validate airgapped configs only if running in airgapped mode

---

Makefile
build/lib/validate_release_buildspecs.sh

Add validations for staging buildspec to prevent duplicate identifier names and invalid `depend-on` values.

Add validations for staging buildspec

---

projects/kubernetes-sigs/image-builder/buildspecs/ami.yml
projects/kubernetes-sigs/image-builder/buildspecs/ova.yml

Make Python site-packages folder readable to non-root users so that AMI and OVA builds that run within CodeBuild as `imagebuilder` user can access these packages.

Make Python site-packages folder readable to non-root users

---

Common.mk
build/lib/common.sh
build/lib/fetch_binaries.sh
build/lib/upload_artifacts.sh
projects/kubernetes-sigs/kind/build/base-image-build-args.sh

We do not need to use this for anything right during our build process, but we may eventually want to enable building in CI without marking all build artifacts public.
I was using this to test building the entire stack in my aws account pointed at a private s3 bucket. I was able to build the entire stack this way without needing to pull anything from the build account bucket.

support pushing/pulling from private s3

---

projects/kubernetes-sigs/image-builder/buildspecs/ami.yml
projects/kubernetes-sigs/image-builder/buildspecs/ova.yml
projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
projects/kubernetes-sigs/image-builder/patches/0002-Output-vsphere-builds-to-content-library-instead-of-.patch
projects/kubernetes-sigs/image-builder/patches/0003-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
projects/kubernetes-sigs/image-builder/patches/0004-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
projects/kubernetes-sigs/image-builder/patches/0005-Additional-EKS-A-specific-goss-validations.patch
projects/kubernetes-sigs/image-builder/patches/0006-Tweak-Product-info-in-OVF.patch
projects/kubernetes-sigs/image-builder/patches/0007-Support-crictl-validation-from-input-checksum.patch
projects/kubernetes-sigs/image-builder/patches/0008-Exclude-kernel-and-cloud-init-from-yum-updates.patch
projects/kubernetes-sigs/image-builder/patches/0009-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
projects/kubernetes-sigs/image-builder/patches/0010-Add-instance-metadata-options-to-Packer-config.patch
projects/kubernetes-sigs/image-builder/patches/0011-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
projects/kubernetes-sigs/image-builder/patches/0012-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch
projects/kubernetes-sigs/image-builder/patches/0013-Use-tar.gz-extension-for-CNI-plugins-tarball.patch
projects/kubernetes-sigs/image-builder/patches/0014-uses-latest-ubuntu-22.04-iso.patch
projects/kubernetes-sigs/image-builder/patches/0015-adds-support-for-raw-ubuntu-22.04-builds.patch
projects/kubernetes-sigs/image-builder/patches/0016-sets-OS_VERSION-for-goss-validation-on-raw-image-bui.patch
projects/kubernetes-sigs/image-builder/patches/0017-Disable-UDP-offload-service-for-Redhat-and-Ubuntu.patch
projects/kubernetes-sigs/image-builder/patches/0018-Add-dracut-cmd-to-generate-initramfs-with-all-driver.patch
projects/kubernetes-sigs/image-builder/patches/0019-Add-proxy-register-with-satellite-and-pull-packages-.patch
projects/kubernetes-sigs/image-builder/patches/0020-Ubuntu-switch-to-offline-install-when-mirrors-are-un.patch
projects/kubernetes-sigs/image-builder/patches/0021-Default-Flatcar-version-to-avoid-pulling-from-intern.patch
projects/kubernetes-sigs/image-builder/patches/0022-TEMP-skip-python-3.9-check-if-ansible-already-instal.patch
projects/kubernetes-sigs/image-builder/patches/0023-Nutanix-RHEL-support-for-AWS-image-builder.patch
projects/kubernetes-sigs/image-builder/patches/0024-Fix-redhat-9-cloud-init-feature-flags-bug.patch
projects/kubernetes-sigs/image-builder/patches/0025-Fix-ensure-iptables-present-for-rhel.patch
projects/kubernetes-sigs/image-builder/patches/0026-adds-retries-and-timeout-to-packer-image-builder.patch

This adds retries to initial ansible tasks as well as changes the ssh_timeout, which we do see run forever sometimes, to 20 mins which matches the nutanix config.  I *think* this may (automatically?) retry in the cases where we see timeouts and failures today. It may just make the failure quicker, in which case we can add a followup PR to add retries.  
Want to try this first and see what happens.

adds retries and timeout to packer image-builder

---

projects/kubernetes-sigs/image-builder/patches/0026-adds-retries-and-timeout-to-packer-image-builder.patch

bumps ssh timeout to 40m for raw and qemu image builds

---

Makefile
projects/aws/image-builder/Makefile
projects/fluxcd/flux2/Makefile
projects/goharbor/harbor/Makefile
projects/kubernetes-sigs/cluster-api/Makefile
projects/kubernetes-sigs/kind/Makefile
projects/kubernetes/autoscaler/Makefile

There was a weird issue last night generating the kind help due the logging around one of the targets. Im not 100% sure why this isnt consistent, but this should clean it up.
Last night's PR: https://github.com/aws/eks-anywhere-build-tooling/pull/2622

fixex help generation for kind project

---

projects/kubernetes-sigs/image-builder/.gitignore
projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/build_image.sh
projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh

In CI we ocassionally will see a timeout in qemu when it tries to download the iso, for either redhat or ubuntu. This changes the flow a bit to download the iso first before calling qemu.

downloads iso before calling qemu

---

projects/kubernetes-sigs/image-builder/build/build_image.sh

One of our image builds failed waiting on a provisioner, the retry logic was borked and created an infinite loop. This fixes that and retries if we get that specific messsage.

fixes image builder retry logic

---

build/lib/common.sh
build/lib/run_target_docker.sh
docs/development/building-locally.md
projects/kubernetes-sigs/kind/build/build-kind-node-image.sh

In the case of cross-compiling, we use the builder base but the platform may not always match the host.  For this to work you need qemu installed, which we do all over and have in the docs.  This adds a check for this and a message to guide the user.
Interestingly, I was going to do the same for buildctl and buildx, but buildkit (which powers both) seems to ship with its own qemu and so you do not actually have to run the binfmt install... this is news to me....
I also updated the building locally doc a bit, reorg mainly but a few update items.

adds check for qemu and updates docs a bit

---

projects/aws/image-builder/builder/manifests.go
projects/aws/image-builder/builder/utils.go
projects/aws/image-builder/builder/utils_test.go

Ansible Redhat subscription module does not support a `no_proxy` field. If the user wants to use proxy, but wants to avoid using proxy to access the Redhat Satellite for registration, they can do so by providing the satellite hostname on the provider configuration json using the `no_proxy` field.
This change, checks if the redhat satellite hostname matches with one of the no_proxy endpoints and if so, skips setting proxy on the subscription module.

Skip setting proxy on subscription module, if satellite is part of no_proxy

---

build/lib/common.sh
build/lib/helm_push.sh

I *think* I had originally changed this because for some reason tee itself does not work for me on my mac, or my linux instances. It appears that without using tee it does not work in codebuild.. not sure if its a difference in the helm version?

use tee to fix digest to tmpfile

---

build/lib/common.sh
build/lib/fetch_binaries.sh

When building privately or in the case of staging bundle build, wed like to be able to push to and pull from a clean folder on s3. This will allow us to ensure that when we build the entire stack we are building all the deps as needed and not potentially pulling older builds.
The way this is setup is to support supplying a path/prefix in ARTIFACTS_BUCKET. for ex
`export ARTIFACTS_BUCKET=s3://my-bucket/staging/release/1`
Another option would be to introduce a new var, ARTIFACTS_BUCKET_PREFIX.  This approach may be slightly more clear, but there are a number of places wed have to handle this in the code today.  If we really wanted to have a second var we could something like:
```
export ARTIFACTS_BUCKET=s3://my-bucket
export …
```

supports s3 path prefixes in bucket variable

---

Common.mk

The new upgrader project is a bit unique in that it is a release branch'd project, but has release branch folders nor git_tag files since we arent building any bins. This is a bit odd, but the simplest fix is to just allow the attribution through the release branch required check.

fixes nightly attribution for upgrader projeect

---

Makefile
build/lib/readme_check.sh
projects/emissary-ingress/emissary/README.md
projects/kubernetes/autoscaler/README.md
projects/tinkerbell/tinkerbell-chart/README.md

* Allow passing project name to readme update script to update version for single project
* Fix bug in echo command that caused the `generate` Make target to be run during in case of error.
* Block merge when project README is not up to date.

Support release-branched projects and passing project name in README version check

---

Makefile
build/lib/readme_check.sh

This allows running the script from anywhere, which will be useful for the automation where we can run it against the cloned repo.

Use absolute paths during README check

---

build/lib/common.sh

fixes building kind in codebuild

---

projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
projects/kubernetes-sigs/image-builder/patches/0027-disable-gpg-for-extra-rpms.patch

The megaraid drivers we install, the rpm was not signed by Dell.  The new version of ansible validates the gpg key and is now failing.  This patches the extra_rpms target to skip this check.

fix raw rhel builds

---

build/lib/buildkit.sh
build/lib/helm_push.sh
build/lib/helm_require.sh
build/lib/image_shasum.sh

This is a further attempt at cleaning up the helm building process.  This removes (almost) all the ecr/public specific logic in favor of using skopeo where possible to support any registry, including local ones.
This simplifies the logic when looking for images down:
- for the actual images associated with whatever project is building, it tries to find and pull them from whatever image_regi is configured. It no longer is checking other regi, like ecr-public.
- for images that come from other projects, it also pulls them from the current regi, but it has to use the `latest` tag to try and find it vs the specific tag, since those images would have been built previous and have different specific tags.
- for images found via `latest`, it will …

cleans up helm chart building and pushing

---

tools/version-tracker/pkg/commands/display/display.go
tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/github/github.go

This PR fixes the logic of determining the latest release for a project on GitHub. Previously, we were simply taking the first element in the releases or tag list as the latest revision. But this could lead to false positives if the project released a patch from an older release branch, which would make it appear at the top of the list, below the true latest version.
**Before**
```bash
$ version-tracker display --project cert-manager/cert-manager
ORGANIZATION  REPOSITORY    CURRENT VERSION  LATEST VERSION  
cert-manager  cert-manager  v1.13.2          v1.12.7
$ version-tracker display --project goharbor/harbor 
ORGANIZATION  REPOSITORY  CURRENT VERSION  LATEST VERSION  
goharbor      harbor      v2.9.1           v2.7.4
```
**After**
```bash
$ version-tracker display --project …
```

Fix logic to get latest GitHub release for a project

---

buildspecs/upgrade-buildspec.yml
tools/version-tracker/buildspecs/upgrade.yml

Upgrades for some projects, such as containerd, runc, etc. are done in a separate CodeBuild job for amd64 and arm64 to leverage the same architecture for the build instance as the binary we're compiling. However, since both of these push to the same branch/PR, the checksums file on the branch gets overwritten by the job that runs second. In order to avoid that, we're using the `union` merge strategy for the CHECKSUMS files.

Merge checksums when building for different architectures separately

---

build/lib/buildkit.sh
build/lib/common.sh

We have a similar warning like this when building via docker, mainly for cgo projects because when running docker containers for a different platform qemu is required.   When running buildkit and needing qemu, there is a builtin version included with buildkit.  However, I have noticed that the later versions of qemu, 7+, do not appear as stable as 6.  @vivek-koppuru was running into issues locally building the upgrader image due to the version of qemu included with buildkit.  Running the install of 6 manually solves the issue.
As a bit of background, building container images for other platforms does not ALWAYS require qemu. If a dockerfile is just a bunch of ADD/COPY layers, then no code is actually being executed.  If there is a RUN …

adds platform warning when building images

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_CONTROL_CONTAINER_METADATA

Fix image tag for bottlerocket control container. v0.11.1 is the admin container tag that got copied over mistakenly and checked in when #2765 merged.

Fix image tag for bottlerocket control container

---

projects/kubernetes-sigs/image-builder/patches/0028-Remove-old-kernels.patch

Image builder was excluding kernel updates till now. With this change, image builder will update kernels and reboot into the new kernel. Post reboot, if the OS has more than 1 kernel, this change will remove all non-live kernels running on the RHEL machine.
*Testing*
Running image builder with changes output
```
qemu: TASK [node : Get the list of installed kernels] ********************************
qemu: changed: [default]
qemu:
qemu: TASK [node : Get the current running kernel] ***********************************
qemu: changed: [default]
qemu:
qemu: TASK [node : Set the number of kernels to keep] ********************************
qemu: ok: [default]
qemu:
qemu: TASK [node : Filter out the current kernels] ***********************************
qemu: ok: [default] …
```

Image-builder: Update kernel and keep only 1 kernel on redhat machines

---

EKSD_LATEST_RELEASES

EKS-D has completed their v1.29 production launch so we should start using those artifacts instead of the dev ones.

Use EKS-D v1.29 prod release assets

---

projects/kubernetes-sigs/image-builder/patches/0029--Export-ova-file-independently-to-ignore-nvram-file-t.patch

During `govc library.export <template-name>` vSphere downloads the ovf, vmdk and nvram. After the latest update to vSphere, govc fails to download nvram file. Since we do not consume the nvram file, the changes here are a workaround where we download the required files individually. 

Ignore nvram when downloading from vSphere content libraries

---

buildspecs/combine-images.yml

Some packages projects like harbor and emissary build their AMD64 and ARM64 images separately using the standard top-level buildspec and then combine the images into an image manifest in the third stage using the combine-images buildspec. The packages projects are not built for release branch and this is enforced in the standard buildspec by running the `check-for-release-branch-skip` Make target, but this is not present in the combine-images buildspec which causes it to try to pull down images that were never pushed in the first place because they got skipped on the release branch. This PR adds this check to the combine-images buildspec as well.

Check for release branch in combine-images buildspec

---

projects/kubernetes-sigs/image-builder/patches/0030-Download-and-include-the-nvram.patch

govc library.import is failing without this.
"Unable to parse disk image while uploading"

Download and include the nvram in OVAs:

---

projects/aws/upgrader/upgrade.sh

Update the if condition to use the right comparison operater for strings. `-ne` only works for integers and throws and error when used with strings.
Also change the shebang to use `bash` instead of `sh`

Fix in-place upgrade script to properly upgrade etcd

---

projects/kubernetes-sigs/image-builder/buildspecs/ova.yml

Run OVA image builds against dev vCenter till CI issues are fixed.

Run OVA image builds against dev vCenter

---

projects/kubernetes-sigs/image-builder/Makefile

Add CloudStack dependency version Make target to list so it can be run without the release branch.

Add CloudStack dependency version Make target to list

---

projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch

This PR reverts the changes in a previous [PR](https://github.com/aws/eks-anywhere-build-tooling/pull/2770/commits/21e0cc86732138454c33cc2f595bf4ffb83e6a30), excluding kernel updates from the RHEL yum updates because newer kernel versions seem to introduce some unidentified networking issues in a k8s cluster

Exclude kernel updates from yum updates in RHEL support and improvements patch

---

projects/kubernetes-sigs/metrics-server/1-25/helm/schema.json
projects/kubernetes-sigs/metrics-server/1-26/helm/schema.json
projects/kubernetes-sigs/metrics-server/1-27/helm/schema.json
projects/kubernetes-sigs/metrics-server/1-28/helm/schema.json
projects/kubernetes-sigs/metrics-server/1-29/helm/schema.json

N/A
EKS Anywhere Curated Packages accept configuration parameters that are passed in to the underlying helm chart as values.
The packages controller validates these parameters using the schema.json, which is base64 encoded, compressed, and published
as a package attribute in the packagebundle object.
This change was verified by building the helm chart locally and grabbing the schema field from `requires.yaml`.
I then plugged this schema value into the [TestPackageValidate unit test](https://github.com/aws/eks-anywhere-packages/blob/cb5c9870ca6c1ce306db7e479392e29249df8484/pkg/webhook/package_webhook_test.go#L12-L12) in eks-anywhere-packages repo.
By verifying that the test passed, I was able to confirm that the schema was valid.
By …

Fix Bad Metrics Server Schema

---

projects/aws-observability/aws-otel-collector/helm/patches/0003-default-values-patch.yaml

ADOT is built upon opentelemetry-collector with customized logging and configuration handling logic that only supports the selected components which have been verified by AWS from the opentelemetry-collector list
This patch updates the ADOT helm chart to use logging exporter rather than debug exporter as debug exporter is not supported in v0.36.0 of ADOT
Related issue on ADOT github:
https://github.com/aws-observability/aws-otel-collector/issues/2470

Update ADOT patch to use logging instead of debug exporter

---

projects/kubernetes-sigs/image-builder/patches/0008-Disable-UDP-offload-service-for-Redhat-and-Ubuntu.patch

Recent updates with vmxnet3 to support udp offloading for Vxlan and geneve introduced bugs with TCP checksum offloading that computes incorrect checksum for packets when TCO is enabled. Multiple fixes and subsequent bugs from those fixes where introduced which lead to enabling TCO on RHEL when using vmware drops packets due to incorrectly computed checksums. This changes disables TCO explicitly for RHEL + vSphere combination.

Disable TCP Checksum Offloading(TCO) on RHEL for vSphere

---

EKSD_LATEST_RELEASES
projects/aws/eks-a-admin-image/build/export-ami-to-s3.sh
projects/aws/eks-a-admin-image/build/validate-release-manifest-version.sh
projects/kubernetes-sigs/image-builder/build/build_image.sh
projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch

We were facing issues with importing the Ubuntu 22.04 OVAs built in CI, with the most common error being
```console
Reason: Error transferring file ubuntu-2204-kube-v1.28.4-1.vmdk to ds:///vmfs/volumes/vsan:.... Reason: Unable to parse disk image while uploading to: ds:///vmfs/volumes/vsan:...
```
This pointed to an issue with the VMDK itself. To build the OVA, we download the OVF, VMDK and NVRAM from the vCenter Content Library in the Packer post-processor step and then pass them as inputs to a script which packages them into an OVA. Since December 15 or so, we noticed that the OVAs being uploaded to S3 had shrunk in size compared to previous uploads (~6 GB before vs ~2 GB after). Upon downloading the OVA, extracting the VMDK and inspecting it, we encountered the following error. …

Monitor govc session to ensure full VMDK downloads

---

tools/version-tracker/pkg/constants/constants.go

Adding release notes to the upgrade PRs that the bot opens.

Add release notes to PR description

---

projects/metallb/metallb/helm/patches/0001-packages-patches.patch

New version of metallb requires some volumes to be mounted to the speaker pods that the patch was removing.
This PR updates the patch to keep the volume/volumeMounts

Fix metallb patch

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES

Backporting #2879 to release-0.18 branch.

Bump Bottlerocket release version to latest

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES

Bottlerocket [dropped](https://github.com/bottlerocket-os/bottlerocket/commit/f1be358629beccaf3dc4bd18d4939ffec04a2de8) the 1.24 metal and vmWare variants in the latest release but we still need them for our 0.18 releases.

Revert Bottlerocket release update for 1.24 OVA and raw images

---

projects/aws/upgrader/upgrade.sh

https://github.com/aws/eks-anywhere-internal/issues/2159
`KubeletCredentialProviders` support became GA in k8s v1.26, and the feature gate was removed in k8s v1.28.
When upgrading nodes in-place from 1.25 -> 1.26 -> 1.27 -> 1.28, the 1.28 upgrade will fail with unrecognized feature flag.
Therefore, we should remove this feature gate if it exists on nodes running k8s v1.26 and above.
in 1.25 node: 
```
capv@tneyla-ub-25-hvcvf:~$ cat /etc/sysconfig/kubelet 
KUBELET_EXTRA_ARGS= --feature-gates=KubeletCredentialProviders=true --image-credential-provider-config=/eksa-packages/credential-provider-config.yaml --image-credential-provider-bin-dir=/eksa-packages/
```
After in-place upgrade to 1.26:
```
capv@tneyla-ub-25-hvcvf:~$ cat …
```

Handle KubeletCredentialProviders extraargs for in-place upgrades

---

build/lib/eksa_releases.sh
projects/aws/image-builder/Makefile
projects/aws/image-builder/builder/constants.go
projects/aws/image-builder/builder/utils.go

Fix image-builder builds in dev release mode by supporting the new release manifest versioning scheme.

Fix image-builder builds in dev release mode

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
projects/kubernetes-sigs/image-builder/build/get_bottlerocket_artifacts.sh

Add 1-29 release branch Bottlerocket artifacts for VMWare and AWS variants.

Add 1-29 release branch Bottlerocket artifacts

---

projects/aws/upgrader/upgrade.sh

As part of InPlace upgrades, [Eksa controller](https://github.com/aws/eks-anywhere/pull/7595) mounts a config map onto the upgrader pod to expose the latest kube-vip manifest. This change copies the latest kube-vip manifest from the volume mount used by the config map and replaces the existing kube-vip in the static pod path. As a fallback option, change also backs up the existing kube-vip manifest. 
Tested the changes locally in conjunction with the Eksa controller changes. 

Handle kube-vip manifest update in the upgrader script

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES

Use production release of Kubernetes v1.29 Bottlerocket OVA from v1.19.1, which was released just today.

Use production release of Kubernetes v1.29 Bottlerocket OVA

---

build/lib/setup.sh
projects/kubernetes-sigs/kind/build/node-image-build-args.sh

This PR enforces legacy iptables on builder-base to fix Docker daemon startup issues and updates Kind dependency image tags.

Enforce legacy iptables, fix Kind dependency image tags

---

projects/aws/upgrader/upgrade.sh

We added a fix in https://github.com/aws/eks-anywhere-build-tooling/pull/2891 to remove kubelet extra args when upgrading to k8s >= 1.26 as that kubelet extra args is deprecated/removed. The problem is that config file is created by one of the `eksa-packages` pods. So the packages wasn't deployed or failed to deploy, this file wouldn't exist and the in-place upgrade would fail.
This PR adds a check to see if this kubelet config file exists before trying to modify it.

Fix upgrader script to check if kubelet config exists before updating it

---

projects/kubernetes-sigs/image-builder/buildspecs/ami.yml
projects/kubernetes-sigs/image-builder/buildspecs/cloudstack.yml
projects/kubernetes-sigs/image-builder/buildspecs/ova.yml
projects/kubernetes-sigs/image-builder/buildspecs/raw.yml

This PR removes the IMAGE_OS_VERSION from image-builder buildspecs because all the individual image build projects set the IMAGE_OS_VERSION env var, but we dont set it in the staging buildspec so it causes issues. We don't need to set it in the staging buildspec since we only build Bottlerocket, which defaults to `1`.

Remove IMAGE_OS_VERSION command-line Make variable

---

projects/kubernetes-sigs/image-builder/Makefile

Allow overriding Make variables related to image OS and OS version so these can be read in from the environment.

Allow overriding Make variables related to image OS and OS version

---

projects/kubernetes/autoscaler/README.md

Add some documentation to reduce friction in the process of developing and testing curated packages helm charts.
Note that this does not test the helm chart's schema, as that would require generating a bundle and installing
in a cluster running the package controller.
However, this does verify that the helm chart itself is valid yaml and install as expected.

Add Instructions for Validating Helm Chart

---

projects/kubernetes-sigs/image-builder/buildspecs/cloudstack.yml

We need to set this so that correct ISO URL and ISO checksum are assigned for constructing the Cloudstack configuration file for image-builder.

Add back IMAGE_OS_VERSION in Cloudstack buildspec

---

tools/version-tracker/pkg/ecrpublic/ecrpublic.go
tools/version-tracker/pkg/github/github.go
tools/version-tracker/pkg/util/tar/tar.go

We only require the Go binary to check the Go version information, so we can skip extracting all other files in the GitHub release tarball.

Extract only the Go binary from GitHub release tarball

---

projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch

In our content library patch, we had explicitly set the nested `destroy` field in the content library configuration section to `"true"`, so Packer builder VMs were getting deleted when the build finishes. When we removed the patch in #2988, the build fell back to image-builder's default behavior of leaving around VMs. In this PR, I am patching image-builder so we get the old behavior back.

Always delete the Packer builder VM at the end of the build

---

EKSD_LATEST_RELEASES

Fix kubeversion formatting in EKSD_LATEST_RELEASES file.

Fix kubeversion formatting in EKSD_LATEST_RELEASES

---

tools/version-tracker/pkg/commands/display/display.go
tools/version-tracker/pkg/commands/listprojects/listprojects.go
tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/constants/constants.go
tools/version-tracker/pkg/github/github.go

Whenever the project upgrader encounters a project that has patches, it doesn't try to apply them because it could lead to conflicts with the new Git tag. So it just updates the Git tag, Go version and README files for the project and opens a PR with only these changes, which it then marks as an incomplete PR because patches, attribution and checksums need to be updated. 
However, sometimes patches do get cleanly applied across Git tags, especially if they're smaller patches. This PR adds the logic to always apply patches and decide the flow based on the outcome of the patch application. If patches were successfully applied, it proceeds with the generation of attribution and checksums and includes them in the PR, else it does what it does today, i.e., an incomplete PR with a warning, but …

Attempt to apply patches and generate checksums/attribution if successful

---

tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/github/github.go

The Kubernetes tag file on GitHub has a trailing newline, so we need to remove it before putting it in the EKS-D latest releases file. Also added logic to update the PR description on an existing PR, in case a new version gets released again when the PR is still open.

Remove newlines from kubeVersion field

---

EKSD_LATEST_RELEASES

Backporting EKS-D release versions for release v0.19.1

Backporting EKS-D release versions for release v0.19.1

---

tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/github/github.go

The checksums and attribution generation was under the incorrect `if` block, which caused it to get executed only for projects with patches. This PR fixes the conditions to get the desired upgrade flow.

Fix checksums and attribution generation during upgrade

---

projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-RHEL-support-for-AWS-image-builder.patch
projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
projects/kubernetes-sigs/image-builder/patches/0008-Disable-UDP-offload-service-for-Redhat-and-Ubuntu.patch
projects/kubernetes-sigs/image-builder/patches/0009-Default-Flatcar-version-to-avoid-pulling-from-intern.patch
projects/kubernetes-sigs/image-builder/patches/0010-Revert-updates-to-Ubuntu-2004-ISO-URLs.patch

Adding https://github.com/kubernetes-sigs/image-builder/pull/1432 as a patch until it's merged and included in a new release. Instead of adding it as a new patch, I included it in the `0005-RHEL-support-and-improvements.patch` file.

Place RHEL kickstart files for raw builds in `http` directory

---

projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22-support-and-improvements.patch

Updating Ubuntu 22.04 ISO URL for raw builds to latest. This aligns it with the OVA builds.

Update ISO URL for Ubuntu 22.04 raw builds

---

EKSD_LATEST_RELEASES

Backporting #3020 to release-0.19 branch.

Bump EKS-D releases to latest

---

projects/kubernetes-sigs/image-builder/Makefile

Adding makefile changes for Image builder CI to support raw redhat 9 builds.

Add CI changes for Raw Redhat 9 Builds

---

projects/helm/helm/CHECKSUMS
projects/helm/helm/patches/0001-bug-add-proxy-support-for-oci-getter.patch
projects/helm/helm/patches/0002-Set-proxy-in-registry-client.patch

We removed our patches adding support for the flag --insecure-skip-tls-verify, as the functionality had been added to upstream helm. However, upstream has a bug when using proxy with the --insecure-skip-tls-verify flag so the helm commands fails.
This PR adds a patch to fix this bug
*Testing*
Manually ran helm commands with the `--insecure-skip-tls-verify` flag with proxy and verified the commands work.
Built EKS-A controller to use the patched helm and verified cluster creation worked.

Add patch for insecure proxy support for helm

---

tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/constants/constants.go

This PR fixes the logic for deciding if the patch application was successful.

Fix attribution and checksum generation for successful patch application

---

docs/development/building-locally.md

add note to building locally about skopeo

---

projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-RHEL-support-for-AWS-image-builder.patch
projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
projects/kubernetes-sigs/image-builder/patches/0008-Disable-UDP-offload-service-for-Redhat-and-Ubuntu.patch
projects/kubernetes-sigs/image-builder/patches/0009-Default-Flatcar-version-to-avoid-pulling-from-intern.patch
projects/kubernetes-sigs/image-builder/patches/0010-Revert-updates-to-Ubuntu-2004-ISO-URLs.patch
projects/kubernetes-sigs/image-builder/patches/0011-Update-Ubuntu-22.04-ISO-URLs-to-use-stable-URLs.patch

Adding a patch for https://github.com/kubernetes-sigs/image-builder/pull/1438. This will be removed when we move to image-builder v0.1.26
/cherrypick release-0.19

Add patch to update Ubuntu 22.04 ISO URLs to latest stable release

---

EKSD_LATEST_RELEASES

Bump Eks-d release to latest on main.

Bump Eks-d release to latest on main

---

build/lib/buildkit.sh

The current remediation logic greps for a hardcoded string from the error received from `docker buildx` command. Ideally we want to suggest creating a multiarch driver as a workaround if the buildx uses the default driver. To accomplish this, we could just grep for the key words on the error message instead of the entire string as it might change between different docker versions.
Tested locally by building on the default driver on docker version:  25.0.3

Improve build fail remediation logic to factor in newer docker versions

---

tools/version-tracker/pkg/github/github.go

This PR adds logic to handle cases where GitHub release does not exist for tag.

Handle cases where GitHub release does not exist for tag

---

tools/version-tracker/pkg/constants/constants.go

This PR fixes the Go mod location for cluster-autoscaler.

Fix Go mod location for cluster-autoscaler

---

projects/aws/eks-a-admin-image/Makefile
projects/aws/eks-a-admin-image/build/get_latest_eksa_version_by_date.sh
projects/aws/eks-a-admin-image/ova/linux/ubuntu/vsphere.ubuntu.pkrvars.hcl
projects/aws/eks-a-admin-image/provisioners/install_golang.sh

Allow running EKS-A admin image build on Darwin, by making the `date` command dynamic. 

Allow running EKS-A admin image build on Darwin, update Ubuntu ISO URL

---

tools/version-tracker/pkg/commands/display/display.go
tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/github/github.go

This PR adds the logic for upgrading projects tracked with commits. In this case, the upgrade is done to the latest commit of the repo.

Allow upgrading projects tracked with commits

---

tools/version-tracker/pkg/constants/constants.go
tools/version-tracker/pkg/github/github.go

This PR fixes the pre-release detection logic when fetching the latest revision from GitHub.

Fix pre-release detection logic when fetching latest GitHub revision

---

tools/version-tracker/pkg/constants/constants.go

New releases of cert-manager have changed the asset name for the cert-manager cmctl tarballs, so updating our code to handle that.

Fix cert-manager GitHub release tarball name

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES

Add release branch support for 1-30 for BottleRocket OVA template builds.

Add br ova support for release branch 130

---

tools/version-tracker/pkg/constants/constants.go
tools/version-tracker/pkg/github/github.go

This PR adds the logic to allow certain projects, governed by a list, to upgrade to pre-release tags. This is because some of the projects we consume have functional changes in release-candidate (RC) tags.

Allow projects to selectively upgrade to pre-release tags

---

projects/vmware/govmomi/CHECKSUMS
projects/vmware/govmomi/patches/0001-Revert-zero-value-change-for-capacityInKB.patch

If the `capacityInKB` in the new virtual disk spec is zeroed out, it causes the following error when trying to reconfigure the VM disk size 
```console
govc: error resizing main disk
Logged Item:  Invalid operation for device '0'.
```
So we are adding a patch to set the `capacityInKB` to its actual value, converting from `capacityInBytes`.

Add patch to revert deprecation of disk size capacityInKB field

---

projects/kubernetes-sigs/image-builder/patches/0001-Force-delete-Nutanix-builder-VMs-on-failure.patch

Nutanix build failures leave behind running VMs on Nutanix Prism central, so this PR adds a patch that force-deletes these VMs even on failure. 

Add patch to force-delete Nutanix builder VMs

---

projects/kubernetes-sigs/image-builder/build/build_image.sh

Nutanix image builds sometimes fail with the flaky issue of image size mismatch. This PR adds a retry for the case when such a failure occurs.

Add retries in case of Nutanix image size mismatch

---

projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
projects/kubernetes-sigs/cluster-api-provider-cloudstack/patches/0001-Support-re-assignment-of-another-failure-domain-when.patch

Issue https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/issues/352
**Description of changes:** CAPC chooses a [random failure domain](https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/blob/d597e8056e82ac6418171e66fa2532b2daaef987/controllers/cloudstackmachine_controller.go#L185) to deploy worker machines. When this VM deploy fails, irrespective of the type of error, CAPC will keep re-attempting to deploy a VM until CAPI replaces the owner machine. This change introduces a failure domain balancer with fallback mechanism, primary balancer selects failure domain from network with most free IPs and if it fails it fallbacks to random failure domain selection.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Add patch for failure domain reassignment for CAPC

---

build/lib/generate_staging_buildspec.sh
tools/version-tracker/buildspecs/upgrade.yml

The `kubernetes-sigs/image-builder` project uses the same Git tag for all release branches so we do not need to run the upgrade flow separately for every branch. Hence we're modifying the upgrade batch buildspec to have a single entry for the image-builder upgrade job.

Make image-builder upgrade flow non-release-branched

---

EKSD_LATEST_RELEASES

The latest field on `EKSD_LATEST_RELEASES` should ideally be maintained at least on par with the minimum Kubernetes version supported for the release as that will help us in maintaining a reasonably decent version skew with the max K8s version supported in the release. Trying to bump this to a more recent K8s version has resulted in issues in the past as this field essentially decides the kubectl version that get installed on cli-tools and the later recent versions might not be backward compatible with the older versions we support. 

Bump latest version to 1-26 on EKD_LATEST_RELEASES 

---

Makefile
tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/constants/constants.go
tools/version-tracker/pkg/github/github.go

This PR adds logic to set the RELEASE_BRANCH env var always to support cloning and patching image-builder as it's a release-branched build. It also contains logic to fall back to GitHub source of truth files to retrieve the Go version in case the GitHub release does not exist for a particular tag.

Use latest release branch by default if not defined, fall back to Github file for Go versions

---

tools/version-tracker/pkg/commands/upgrade/upgrade.go

The `MAKEFLAGS` are not preserved when calling `make` through Go code, so the release branch variable ends up including the `Entering directory ...` and `Leaving directory ...` statements printed by `make`. 
```
RELEASE_BRANCH=make[1]: Entering directory `/codebuild/output/src2154812656/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere-build-tooling/tools/version-tracker/eks-anywhere-build-tooling'
1-26
make[1]: Leaving directory `/codebuild/output/src2154812656/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere-build-tooling/tools/version-tracker/eks-anywhere-build-tooling'
```
Thus we need to explicitly pass in the `--no-print-directory` option.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Avoid printing directory name for Make command

---

projects/kubernetes-sigs/image-builder/buildspecs/nutanix.yml

Adding buildspec for Nutanix image builds to `release-0.19` branch in order to fix the missing buildspec issue.

Add buildspec for Nutanix image builds

---

tools/version-tracker/pkg/constants/constants.go

From cert-manager v0.15.0 onwards, the `cmctl` binaries are no longer included in the GitHub releases and are released separately in another project `cert-manager/cmctl`. So we're just using the go.mod file to retrieve the Go version to use for cert-manager.

Use go.mod file to retrieve cert-manager Go version

---

UPSTREAM_PROJECTS.yaml
projects/kubernetes/autoscaler/1-27/CHECKSUMS
projects/kubernetes/autoscaler/1-27/GIT_TAG
projects/kubernetes/autoscaler/1-28/CHECKSUMS
projects/kubernetes/autoscaler/1-28/GIT_TAG
projects/kubernetes/autoscaler/1-28/HELM_GIT_TAG
projects/kubernetes/autoscaler/1-28/helm/patches/0002-Add-image-values.patch
projects/kubernetes/autoscaler/1-28/patches/0002-Update-go.mod-Dependencies.patch
projects/kubernetes/autoscaler/1-29/CHECKSUMS
projects/kubernetes/autoscaler/1-29/GIT_TAG
projects/kubernetes/autoscaler/1-29/patches/0002-Update-go.mod-Dependencies.patch
projects/kubernetes/autoscaler/1-30/ATTRIBUTION.txt
projects/kubernetes/autoscaler/1-30/CHECKSUMS
projects/kubernetes/autoscaler/1-30/GIT_TAG
projects/kubernetes/autoscaler/1-30/patches/0003-Update-go.mod-Dependencies.patch
projects/kubernetes/autoscaler/README.md

This change bumps autoscaler to latest version for release branches 1-27,1-28,1-29 and 1-30. It also adds a patch for branch 1-28 to update the go mod dependencies to remove any package that's not used by provider cluster-api to reduce our risk to vulnerabilities. During the 1-28 [bump](https://github.com/aws/eks-anywhere-build-tooling/pull/3130) we had not updated the helm-chart to latest version and this change also addresses the helm chart bump for release branch 1-28. 

Bump autoscaler version to latest

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/make_fake_image.sh
projects/kubernetes-sigs/image-builder/build/validate_ova_kubelet.sh

We ran into a case where the image build somehow produced a 1.27 image with 1.25 artifacts in it.  Based on the logs we could find root cause why this happened.  We are thinking it could be something on the vsphere export side.  Adding this should at least tell us during the build if something strange like this happens again.

adds ova validation to check kubelet version

---

projects/kubernetes-sigs/metrics-server/1-25/HELM_GIT_TAG
projects/kubernetes-sigs/metrics-server/1-25/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
projects/kubernetes-sigs/metrics-server/1-25/helm/patches/0002-Remove-Addon-Resizer.patch
projects/kubernetes-sigs/metrics-server/1-26/HELM_GIT_TAG
projects/kubernetes-sigs/metrics-server/1-26/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
projects/kubernetes-sigs/metrics-server/1-26/helm/patches/0002-Remove-Addon-Resizer.patch
projects/kubernetes-sigs/metrics-server/1-27/HELM_GIT_TAG
projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0002-Remove-Addon-Resizer.patch
projects/kubernetes-sigs/metrics-server/1-28/HELM_GIT_TAG
projects/kubernetes-sigs/metrics-server/1-28/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
projects/kubernetes-sigs/metrics-server/1-28/helm/patches/0002-Remove-Addon-Resizer.patch
projects/kubernetes-sigs/metrics-server/1-29/HELM_GIT_TAG
projects/kubernetes-sigs/metrics-server/1-29/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
projects/kubernetes-sigs/metrics-server/1-29/helm/patches/0002-Remove-Addon-Resizer.patch
projects/kubernetes-sigs/metrics-server/1-30/HELM_GIT_TAG
projects/kubernetes-sigs/metrics-server/1-30/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
projects/kubernetes-sigs/metrics-server/1-30/helm/patches/0002-Remove-Addon-Resizer.patch
projects/kubernetes-sigs/metrics-server/README.md

This PR updates metrics server helm chart from version 3.11.1 to 3.12.1 
Upstream IMAGE TAG: https://github.com/kubernetes-sigs/metrics-server/releases/tag/v0.7.1  Upstream HELM_GIT_TAG: https://github.com/kubernetes-sigs/metrics-server/releases/tag/metrics-server-helm-chart-3.12.1 
Fixed merged conflicts for Remove Addon resizer patch
Changes were tested on Kubernetes version 1.29 by doing Helm install of the updated chart.

Update metrics-server helm chart to 3.12.1

---

Common.mk

We added this check for cases where newer branches, like main, supported newer versions of kube than previous release branches. In those cases we want builds for say 1.30 to be skipped on release-0.19 which does not support 1.30
This adds support for checking the supported list so we can not build 1.25 on main, but still build it on release-0.19

fixes release branch check for older kube versions

---

tools/version-tracker/pkg/github/github.go

When determining the latest GitHub release, we need to filter out GitHub releases corresponding to Helm charts. This check is not exhaustive but works for the projects we currently maintain.
```console
$ RELEASE_BRANCH=1-30 bin/version-tracker display --project kubernetes/cloud-provider-vsphere
ORGANIZATION  REPOSITORY              CURRENT VERSION  LATEST VERSION            
kubernetes    cloud-provider-vsphere  v1.30.0          vsphere-cpi-chart-1.30.1
```
```console
$ RELEASE_BRANCH=1-30 bin/version-tracker display --project kubernetes/cloud-provider-vsphere
ORGANIZATION  REPOSITORY              CURRENT VERSION  LATEST VERSION  
kubernetes    cloud-provider-vsphere  v1.30.0          v1.30.1 
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …

Exclude GitHub Helm chart release tags

---

projects/tinkerbell/charts/helm/patches/0001-Load-stream-model-for-nginx-and-update-http2-command.patch
projects/tinkerbell/charts/helm/patches/0002-Use-smee-default-values-for-flags-when-running-in-ho.patch
projects/tinkerbell/tink/docker/linux/nginx/Dockerfile

Fix downloading awk, as it was not found in the current nginx image.
Also added a patch to the nginx.conf in the tinkerbell chart to fix residual errors coming from using our nginx image.

Fix nginx image and nginx.conf files

---

tools/version-tracker/pkg/commands/display/display.go
tools/version-tracker/pkg/commands/listprojects/listprojects.go
tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/constants/constants.go
tools/version-tracker/pkg/git/git.go
tools/version-tracker/pkg/github/github.go

This PR adds logic to perform project upgrades on branches other than main. This will be used to upgrade projects on release branches such as `release-0.19`, `release-0.20` etc, where the latest GitHub patch release will be considered for each project instead of the absolute latest GitHub release. The branch name is obtained from the `BRANCH_NAME` environment variable, and if there's no such variable set, it uses `main` as the branch.
```console
$ BRANCH_NAME=main bin/version-tracker display --project goharbor/harbor        
ORGANIZATION  REPOSITORY  CURRENT VERSION  LATEST VERSION  
goharbor      harbor      v2.10.2          v2.11.0 
```
```console
$ BRANCH_NAME=release-0.19 bin/version-tracker display --project goharbor/harbor
ORGANIZATION  REPOSITORY  CURRENT VERSION  LATEST VERSION …
```

Allow project upgrades on release branch

---

projects/kubernetes-sigs/image-builder/Makefile

Switch to t3.micro instances for raw image build presubmits.

Switch to t3.micro instances for raw image build presubmits

---

build/lib/common.sh
projects/torvalds/linux/Makefile

The gather-nongolang-licenses was introduced for helm charts, and then later used for the linux build.  The intention is to make sure our produced artifacts, including charts, have the proper upstream license included.  What we were doing makes sense, however, we end up including all the licenses in the `vendor` directory(s).  This we def do not to include all these.  The problem here is the chart ends up getting put into a secret and the recent update to cert manager puts it over the size limit.
This changes the find to only look in the root directory, which should be all we need for the helm repos. I checked each build to ensure we were getting a license file for each helm chart.
By submitting this pull request, I confirm that you can …

only search for nongolang licenses in root

---

tools/version-tracker/pkg/commands/upgrade/upgrade.go

Project upgrades on release branches was added in [#2375](https://github.com/aws/eks-anywhere-build-tooling/pull/3275). This PR includes the build tooling branch name in the `kubernetes-sigs/image-builder` project version bump branch.

Include branch name for kubernetes-sigs/image-builder project

---

tools/version-tracker/pkg/commands/upgrade/upgrade.go

Project upgrades on release branches was added in https://github.com/aws/eks-anywhere-build-tooling/pull/3275. This PR includes the build tooling branch name in the `kubernetes-sigs/image-builder` project for bottlerocket releases version bump branch as a follow-up to https://github.com/aws/eks-anywhere-build-tooling/pull/3483.

Include branch name for bottlerocket releases

---

tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/constants/constants.go

Packages presubmits are made to run only on main in https://github.com/aws/eks-anywhere-prow-jobs/pull/402 as the packages are build/release only off of main in codebuild. This PR skips upgrading the packages projects on branches other than main.

Skip project upgrade for packages on release branches

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/README.md
projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch

* Update RHEL8 to 8.10 for CI builds
* Update RHEL9 to 9.4 for CI builds
* Use same RHEL versions for all hypervisors
* Use separate `kmod-megaraid` RPMs for RHEL 8 and 9

Update RHEL8 ISO to 8.10, simplify RHEL config generation

---

projects/tinkerbell/tink/Help.mk
projects/tinkerbell/tink/Makefile
projects/tinkerbell/tink/docker/linux/tink-relay-init/Dockerfile
projects/tinkerbell/tink/docker/linux/tink-relay/Dockerfile
projects/tinkerbell/tink/docker/linux/tink-server/Dockerfile
release/staging-build.yml

Add Dockerfiles for dhcp-relay and relay-init images and updates the Makefiles to add targets to build these images. We need to add these images to enable dhcp-relay with the tink-stack.

Add dhcp relay images to tinkerbell tink repo

---

tools/version-tracker/pkg/constants/constants.go

The `rancher/local-path-provisioner` project did not publish release binary assets for their latest release, so the upgrade job was failing. Hence we are using the project Dockerfile to determine the Go version used to build the binary.

Retrieve Go version for local-path-provisioner project from Dockerfile

---

projects/tinkerbell/tink/docker/linux/tink-server/Dockerfile

Tink builds started failing due to a seg fault after a change to the tink-server Dockerfile. Reverting the tink-server Dockerfile to how it was before.

Revert tink-server Dockerfile to use clean_install

---

tools/version-tracker/pkg/constants/constants.go

Adding the Go version source of truth file for `nutanix-cloud-native/cloud-provider-nutanix`.

Add Go version source file for cloud-provider-nutanix

---

projects/tinkerbell/tink/buildspecs/batch-build.yml

CDK changes have been made to the tinkerbell/tink project to run as batch builds. In order to ensure the builds don't break in previous releases, we need to add this build spec file.

Add buildspec file for tink project

---

projects/tinkerbell/tink/Makefile

We need to set IMAGE_BUILD_ARGS in the Makefile to empty. Since combine-images has images as prereq target, the ?= does not really behavior as one might expect and resets to empty causing build failures.

Set IMAGE_BUILD_ARGS in tinkerbell tink Makefile

---

projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0009-Revert-fix-Update-preseed-and-cloud-init-to-use-CD-f.patch

This PR adds a patch to the `kubernetes-sigs/image-builder` project which reverts [this](https://github.com/kubernetes-sigs/image-builder/commit/e49a35f6ecd4f3eb10c53df610f83606e1c36ab4) commit on the upstream repo. The upstream commit added a change to use CD for Ubuntu >=22 preseed/cloud-init boot files. Enabling that feature required adding a dependency on a tool called [xorriso](https://www.gnu.org/software/xorriso/) supposed to be used by Packer but that tool doesn't exist on our builder-base image. So our ova builds for ubuntu 22.04 started failing with the following error:
```
could not find a supported CD ISO creation command (the supported commands are: xorriso, mkisofs, hdiutil, oscdimg)
```
The above change was made in this …

Add patch to revert using CD for preseed and cloud-init boot files

---

projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0009-Revert-fix-Update-preseed-and-cloud-init-to-use-CD-f.patch
projects/kubernetes-sigs/image-builder/patches/0010-Remove-swap-partition-in-rhel9-efi.patch

Rhel 9 EFI image has a partition with swap enabled https://github.com/kubernetes-sigs/image-builder/blob/main/images/capi/packer/raw/linux/rhel/http/9/ks-efi.cfg#L37
when using this image to create EKS-A cluster the kubelet cannot start due to the swap partition.
This PR patches the rhel9 ks-efi.cfg file by removing the swap partition from ks-efi.cfg

Image-builder patch: remove swap partition from RHEL 9 EFI

---

tools/version-tracker/pkg/constants/constants.go

BottleRocket refactored their folder [structure](https://github.com/bottlerocket-os/bottlerocket/tree/1.21.x/sources) on release 1.21. Consequently, our upgrade job failed for BottleRocket searching for the `BottlerocketHostContainersTOMLFile` in the wrong location. 
```
2024/08/13 08:07:57 Error upgrading project version: updating Bottlerocket version and metadata files: updating Bottlerocket host containers metadata files: getting contents of Bottlerocket host containers file: getting contents of file [sources/models/shared-defaults/public-host-containers.toml]: GET https://api.github.com/repos/bottlerocket-os/bottlerocket/contents/sources/models/shared-defaults/public-host-containers.toml?ref=v1.21.0: 404 Not Found []
```
This change updates the above location …

Update BottleRocket Host Container file path to match upstream

---

tools/version-tracker/pkg/constants/constants.go

`Tinkerbell/hook` project was recently added to upstream projects as part of Tinkerbell stack updates. The upgrader project tracks the go version for a project based on the source of truth it has to look which is supplied through `ProjectGoVersionSourceOfTruth`. This change adds the Go version source of truth and derives it from the hook-bootkit docker [file](https://github.com/tinkerbell/hook/blob/9dc7c7d39742b4d98699848cb57306edb42fd2fa/images/hook-bootkit/Dockerfile#L4).

Add Go version source of truth for tinkerbell hook project

---

tools/version-tracker/pkg/constants/constants.go

Add fallback configuration to retrieve Go version from GitHub source-of-truth files for all projects, so that if the GitHub releases approach doesn't work, the upgrade flow will still be able to determine the Go version and proceed with its flow.

Add fallback Go version truth files for all projects

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES

Bottlerocket dropped support for 1-25 kube version from v0.20.x Bottlerocket release. Downgrading version for 1-25 to use a supported Bottlerocket version.

[release-0.19] Downgrade bottlerocket version for 1.29 k8s

---

projects/metallb/metallb/helm/patches/0001-packages-patches.patch
projects/metallb/metallb/helm/schema.json

**Description of changes:**
* Update schema.json for MetalLB to align with upstream repository.
* Removed chart corresponding to [frr-k8s-0.0.14.tgz](https://github.com/metallb/metallb/blob/main/charts/metallb/charts/frr-k8s-0.0.14.tgz) in the patch
**Why we are doing this?**
Customer wants to be able to configure interfaces and other attributes which are supported in upstream repository.
Testing
- `helm install -f  values.yaml metallb oci://public.ecr.aws/g0y6o3v0/metallb/metallb --version  0.14.8-3047eee74b2d54f6406a0f469cb3c72fde300822 --set sourceRegistry=public.ecr.aws/g0y6o3v0`
- Tested package installation by generating local bundle with override to registry `public.ecr.aws/g0y6o3v0`.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Update schema.json for MetalLB to align with upstream repository

---

build/update-attribution-files/create_pr.sh

The most recent [PR](https://github.com/aws/eks-anywhere-build-tooling/pull/3639) created by `eks-distro-pr-bot` to update ATTRIBUTION.txt files on `release-0.20` branch did not include the branch name in the PR title. We follow the convention to prepend "[BRANCH_NAME] " to the PR title for most of the other automated PRs created by the bot when the PR is being created for any release branch in order to quickly identify the base branch. This PR updates the `create_attribution` function to follow this convention. The `-r` argument is removed for the `pr_title` local variable to allow updating it else it would be a read-only variable and throw an error.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …

Include branch name other than main in the PR title

---

projects/kubernetes-sigs/image-builder/patches/0009-Image-builder-patch-remove-unwanted-partitions-from-RHEL-9.patch

The swap partition and the /boot partition are both not needed for RHEL 9 efi image. This patch removes them.
*Testing:
Built RHEL 9 image with these 2 partitions removed and successfully created eks-a cluster on Tinkerbell using the RHEL 9 image.

[Patch] Remove unwanted partitions from RHEL 9

---

projects/metallb/metallb/Makefile

This PR updates base image for metallb to `eks-distro-minimal-base`
*Testing*
Tested package installation by generating local bundle with override to personal registry.

Update metallb to pull minimal base image

---

projects/tinkerbell/hook/CHECKSUMS
projects/tinkerbell/hook/Makefile
projects/tinkerbell/hook/docker/linux/hook-docker/Dockerfile
projects/tinkerbell/hook/patches/0001-patches-build.sh-flow-for-linuxkit.patch
projects/tinkerbell/hook/patches/0002-builds-kernel-from-al2.patch
projects/tinkerbell/hook/patches/0003-use-tmpfs-for-var-lib-docker.patch

Codebuild was failing to build because the dind container we launch to pull images to create the embed cache was running with the `vfs` storage driver instead of overlay2.  
We have a similar problem in prow presubmits which run on fargate where because the buildkit process that is running can not create a overlay2 fs for the build layers/stages, it ends up using vfs as well which results in each layer basically be a full copy/duplicate of all previous layers.  In presubmits this is kind of whatever as long as we have the space available.
The codebuild job much like the fargate job are themselves a running container whose rootfs is overlay2.  When we launch the dind container, that docker process on boot attempts to create a overlay2 fs …

fixes dind overlayfs in codebuild

---

buildspecs/combine-images.yml

A quirk about this build is it uses the dockerfiles from upstream.  The few places we use combine have never done this and therefore not needed the repo to be cloned.  Adding this checkout should be fine for those cases and fix the linuxkit build.

fixes combine for linuxkit by checking the repo

---

projects/prometheus/prometheus/README.md

[#3683](https://github.com/aws/eks-anywhere-build-tooling/pull/3683/files#r1742884008) updated the `prometheus/prometheus` version in the README which caused the [validate-generated-presubmit](https://github.com/aws/eks-anywhere-prow-jobs/blob/main/jobs/aws/eks-anywhere-build-tooling/validate-generated-presubmit.yaml) prow job to fail on the open PRs like [#3694](https://github.com/aws/eks-anywhere-build-tooling/pull/3694) and [#3706](https://github.com/aws/eks-anywhere-build-tooling/pull/3706) with the following error:
```
Error: Generated files, UPSTREAM_PROJECTS.yaml README.md release/staging-build.yml release/checksums-build.yml batch-build.yml, do not match expected. Please run 'make generate' to update
diff --git a/projects/prometheus/prometheus/README.md …
```

Fix prometheus/prometheus version in the README

---

tools/version-tracker/pkg/commands/display/display.go
tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/ecrpublic/ecrpublic.go

Project upgrades on release branch was supported in [#3275](https://github.com/aws/eks-anywhere-build-tooling/pull/3275) but it didn't handle getting the latest patch version on release branches for Cilium. Cilium is a special case as the Isovalent team cuts EKS-A specific builds of Cilium which are accessible in our ECR:  https://gallery.ecr.aws/isovalent/cilium
Currently, the eks distro PR bot opens PR for Cilium on release branches for the absolute latest version which could also be a minor version upgrade. We only want to update the patch versions for release branches. This PR updates the logic in the upgrade tool to handle this scenario.
*Testing:*
```
➜  bin/version-tracker display --project cilium/cilium 
ORGANIZATION  REPOSITORY  CURRENT VERSION  LATEST …
```

Upgrade only the patch versions for cilium on release branch

---

projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
projects/kubernetes-sigs/cluster-api-provider-cloudstack/patches/0001-Support-re-assignment-of-another-failure-domain-when.patch

CloudStack tests are failing with the following error after [#3409](https://github.com/aws/eks-anywhere-build-tooling/pull/3409) bumped CAPC version to v0.5.0:
```
Error: initializing capi resources in cluster: executing init: Fetching providers
Using Override="core-components.yaml" Provider="cluster-api" Version="v1.7.2+9e7aabb"
Using Override="bootstrap-components.yaml" Provider="bootstrap-kubeadm" Version="v1.7.2+9cf3afa"
Using Override="bootstrap-components.yaml" Provider="bootstrap-etcdadm-bootstrap" Version="v1.0.13+6519b1e"
Using Override="bootstrap-components.yaml" Provider="bootstrap-etcdadm-controller" Version="v1.0.22+782ca1f"
Using Override="control-plane-components.yaml" Provider="control-plane-kubeadm" Version="v1.7.2+5724915"
Using …
```

Update patch and CHECKSUMS for CAPC v0.5.0

---

tools/version-tracker/pkg/constants/constants.go

This PR changes the upgrader to only use major and minor versions in the Go version search semver.

Use only major and minor versions for Go version semver

---

tools/version-tracker/pkg/constants/constants.go

Backport https://github.com/aws/eks-anywhere-build-tooling/pull/3625 and https://github.com/aws/eks-anywhere-build-tooling/pull/3751 to release-0.19 branch

Backport Go version detection improvements to release-0.19

---

tools/version-tracker/pkg/constants/constants.go

Backport #3625 and #3751 to release-0.20 branch

Backport Go version detection improvements to release-0.20

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
projects/kubernetes-sigs/image-builder/BOTTLEROCKET_CONTROL_CONTAINER_METADATA
projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES

[#2399](https://github.com/aws/eks-anywhere-internal/issues/2399)
- Updated bottlerocket version to latest `v1.22.0`
- Updated bottlerocket admin container to latest `v0.11.11`
- Updated bottlerocket control container to latest `v0.7.15`
*NOTE:*
Bottlerocket 1.27 VMWare variant is no longer supported from v1.21.0 onwards.
PR: https://github.com/bottlerocket-os/bottlerocket/pull/4079

Update bottlerocket release version and host containers

---

projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0009-Support-and-improvements-for-RHEL-9-EFI.patch

Update Ubuntu 22.04 ISO URL for image builds to point to the latest Ubuntu 22.04 image. We needed to do this because they released version 22.04.5 recently and migrated the older 22.04.4 image to the `old-releases.ubuntu.com` endpoint.

Update Ubuntu 22.04 ISO for image builds

---

projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0009-Support-and-improvements-for-RHEL-9-EFI.patch
projects/kubernetes-sigs/image-builder/patches/0010-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
projects/kubernetes-sigs/image-builder/patches/0011-Remove-containerd-configuration-for-hosts.toml-paths.patch
projects/kubernetes-sigs/image-builder/patches/0012-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch

This PR
* Brings back [this](https://github.com/aws/eks-anywhere-build-tooling/commit/3047eee74b2d54f6406a0f469cb3c72fde300822#diff-a1179b5f7cbfbe758c70dfad87aeeecdc87853c41b381b18defd56180b02f7c2) image-builder patch that was necessary for image-builder >= 0.1.31, but was removed when we moved back to v0.1.30. This change fixes Ubuntu 22.04 OVA builds
* Adds [this](https://github.com/kubernetes-sigs/image-builder/pull/1569) upstream image-builder fix as a patch to fix RHEL 8/0 QEMU/raw builds.

Add patches to fix Ubuntu 22.04 OVA and RHEL 8/9 QEMU/raw builds

---

tools/version-tracker/pkg/constants/constants.go

Adding Go version configuration for Linuxkit project. This will be used to detect the correct Go version to use when upgrading to the latest upstream release.

Add Go version configuration for Linuxkit project

---

projects/aws/image-builder/Makefile
projects/aws/image-builder/builder/builder.go
projects/aws/image-builder/builder/utils_test.go
projects/aws/image-builder/cmd/build.go
projects/aws/image-builder/cmd/build_test.go

We only support efi for rhel 9 and currently if firmware is set to efi when calling image-builder it will end up getting the efi appended again.  This changes the image builder to only support firmware efi for rhel 9 raw.
~We need a change to the codebuild job to set this when building rhel 9 raw.~

fixes support for efi on rhel 9 raw builds

---

projects/kubernetes-sigs/image-builder/build/validate_required_deps.sh

We have run into an issue a couple times now where on Ubuntu 24.04 a version of yq is included but it is not the correct yq.  The noticable issue is that return values are double quoted.  The -r tells yq to remove the double quotes, which works with both the correct and incorrect version of yq.
We probably should add a more complete fix here where we validate the source of yq, but I *think* this will avoid the current pain during the image-builder flow since we dont use yq too much.

fix yq usage to support fake yq

---

projects/tinkerbell/boots/CHECKSUMS
projects/tinkerbell/boots/Help.mk
projects/tinkerbell/boots/Makefile
projects/tinkerbell/boots/docker/linux/Dockerfile
release/staging-build.yml

Once we are building ipxedust, this will download it as an artifact from our s3 bucket and use the built ipxe bins instead of the embedded from ipxedust.
This does not currently do anything with the golang src files from ipxedust, those will continue to be pulled via go mods.
Follow up to: #3530 

boots uses eksa ipxedust

---

projects/kubernetes-sigs/image-builder/build/build_image.sh

This PR configures image build retries in case of Ansible SSH timeout since we have observed these usually succeed on the next run when re-triggered.

Retry image builds in case of Ansible SSH timeout

---

projects/linuxkit/linuxkit/CHECKSUMS
projects/linuxkit/linuxkit/Makefile
projects/linuxkit/linuxkit/patches/0001-add-moby-config-to-dockerfiles-for-packages-used-by-.patch

When linuxkit builds their images upstream, most images have a [build.yml](https://github.com/linuxkit/linuxkit/blob/master/pkg/ip/build.yml) file. The config section of these files are added to the docker image as the value of the `org.mobyproject.config` label.  When a linuxkit built image, in our case hook, runs these containers if the template, ex [hook-template](https://github.com/tinkerbell/hook/blob/main/linuxkit-templates/hook.template.yaml), does not include these config values such as capbilities in the template for that image, the linuxkit containerd runtime pulls this label from the final image and uses the config as the default.
Without these our hook will not actually work since it relies on these defaults.
By submitting …

adds moby_config to linuxkit images

---

projects/linuxkit/linuxkit/Makefile

I broke the combine-images in codebuild...  I'll take a pass as a follow up to see if we can test this target in presubmit so it doesn't break it in codebuild.

fixes combine-image phase for linuxkit

---

projects/tinkerbell/hook/Makefile
projects/tinkerbell/hook/README.md
release/staging-build.yml

Changes the hook build to pull eksa builds of linuxkit images instead of from upstream.
https://github.com/aws/eks-anywhere-prow-jobs/pull/425

changes hook to pull eksa linuxkit images

---

projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0009-Support-and-improvements-for-RHEL-9-EFI.patch
projects/kubernetes-sigs/image-builder/patches/0010-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
projects/kubernetes-sigs/image-builder/patches/0011-Remove-containerd-configuration-for-hosts.toml-paths.patch
projects/kubernetes-sigs/image-builder/patches/0012-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
projects/kubernetes-sigs/image-builder/patches/0013-Revert-Optionally-source-etc-default-kubelet-in-kube.patch

Packages tests started failing two weeks ago for vSphere and Nutanix providers on Ubuntu nodes but they passed for Docker, CloudStack and Tinkerbell tests on RHEL and bottlerocket nodes. This was because image-builder was bumped from v0.1.30 to v0.1.35 in [#3627](https://github.com/aws/eks-anywhere-build-tooling/pull/3627) which introduced this upstream [commit](https://github.com/kubernetes-sigs/image-builder/commit/7295eeb19fa4b2408b8c4b9cf64708ab21f7f44c) in the new OS templates. For configuring ECR credentials for packages through kubelet, we always updated `/etc/sysconfig/kubelet` to set the extra args for ubuntu but due to the upstream commit, this file started getting ignored and the credentials couldn't be configured for the packages. This led all the …

Add patch to revert optionally sourcing /etc/default/kubelet in kubelet service

---

projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0009-Support-and-improvements-for-RHEL-9-EFI.patch
projects/kubernetes-sigs/image-builder/patches/0010-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
projects/kubernetes-sigs/image-builder/patches/0011-Remove-containerd-configuration-for-hosts.toml-paths.patch
projects/kubernetes-sigs/image-builder/patches/0012-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
projects/kubernetes-sigs/image-builder/patches/0013-Revert-Optionally-source-etc-default-kubelet-in-kube.patch

This is a manual cherry-pick of [#3850](https://github.com/aws/eks-anywhere-build-tooling/pull/3850).

[release-0.20] Add patch to revert optionally sourcing /etc/default/kubelet in kubelet service

---

projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0009-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
projects/kubernetes-sigs/image-builder/patches/0010-Remove-containerd-configuration-for-hosts.toml-paths.patch
projects/kubernetes-sigs/image-builder/patches/0011-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
projects/kubernetes-sigs/image-builder/patches/0012-Revert-Optionally-source-etc-default-kubelet-in-kube.patch

This is a manual cherry-pick of https://github.com/aws/eks-anywhere-build-tooling/pull/3850.

[release-0.19] Add patch to revert optionally sourcing /etc/default/kubelet in kubelet service

---

projects/tinkerbell/boots/Makefile

Skipping checksums validation for Boots project since we override the ipxedust Go mod with the ipxe binaries we build, and these binaries cannot be built reproducibly, thus changing the checksum each time.

Skip checksums validation for Boots project

---

tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/constants/constants.go

We have the `cert-manager.yaml` cert-manager manifest checked into the repo, but this is tied to a particular cert-manager version, so we need to update the manifest when bumping the cert-manager Git tag.

Update cert-manager manifest when bumping Git tag

---

projects/isc-projects/dhcp/CHECKSUMS
projects/isc-projects/dhcp/Makefile
projects/tinkerbell/ipxedust/CHECKSUMS
projects/tinkerbell/ipxedust/Makefile
projects/torvalds/linux/.gitignore
projects/torvalds/linux/CHECKSUMS
projects/torvalds/linux/Makefile
release/checksums-build.yml

Set build time based on the ipxedust repo commit timestamp to make builds reproducible.
Going to keep boots set to ignore checksums because updating boots due to a update in ipxe will get a bit problematic.  I started to code out a way for the boots presubmit to build ipxe and then use it so that we can use presubmits to validate checksums like we do for other projects.  That would have made it so whenever ipxe changes the boots pre would fail, cluing us into the need to update the checksum.  The issue is that the boots bin, both the amd and the arm, needs to include the amd and arm versions of ipxe.  We do not have a good way to build both arm and amd in the same prow job so we could build just the amd or just arm, depending on the job, …

adds source epoch to ipxe build for reproducibility

---

projects/linuxkit/linuxkit/Makefile

In code-build where we run combine-images, the dockerfile was not getting overridden to the combine-images [dockerfile](https://github.com/aws/eks-anywhere-build-tooling/blob/main/build/lib/docker/linux/combine/Dockerfile).  This is because of how the dockerfile_folder was overridden local to the target, this was not allowing the combine-images to override it.  
This changes move the variable macro to a higher spot which can be overridden later by combine-images.

fixes combine images for linuxkit

---

projects/distribution/distribution/Makefile
release/staging-build.yml

Remove distribution project from staging buildspec since we only need it for the Harbor build which we don't run in staging build.

Remove distribution from staging buildspec

---

tools/version-tracker/pkg/constants/constants.go

Use Dockerfile to retrieve Rufio Go version since the CI yaml isn't regularly updated upstream.

Use Dockerfile to retrieve Rufio Go version

---

buildspecs/combine-images.yml

In the linuxkit makefile we default image_platforms to the local host arch. We probably dont have to do this, but it makes it a bit easier when working locally.  Because of this we were combining the amd and arm images in codebuild but only including the arm image.  This sets the image platforms in the combine-images buildspec to override this.  There would not be a case, at least right now, where we wouldnt want both platforms during combine so this feels like a reasonable change.

forces combine-images flow to build both platforms

---

projects/kubernetes-sigs/image-builder/patches/0014-Set-SSH-password-dynamically-during-auto-install.patch

Fix typo in password env var in autoinstall script

Fix typo in password env var in autoinstall script

---

tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/constants/constants.go

Sometimes patch application can fail not only due to merge conflicts but also because the file that the patch is applying doesn't exist on the target repo. For example, we saw this happening for the kubernetes-sigs/image-builder project's v0.1.39 tag which includes kubernetes-sigs/image-builder#1607, which renames some files to templates with `.tmpl` extension. The upgrade command needs to handle this specific error message so that it adds the proper patch warning comment on PRs.

Include files not in index in patch application failure comment

---

tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/constants/constants.go

We have the `IMAGE_DIGEST` ADOT image digest checked into the repo, but this is tied to a particular ADOT version, so we need to update the image digest when bumping the ADOT Git tag.
*Testing:*
`make -C tools/version-tracker build`

Update ADOT image digest when bumping Git tag

---

projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
projects/kubernetes-sigs/metrics-server/1-27/helm/patches/0002-Remove-Addon-Resizer.patch
projects/kubernetes-sigs/metrics-server/1-28/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
projects/kubernetes-sigs/metrics-server/1-28/helm/patches/0002-Remove-Addon-Resizer.patch
projects/kubernetes-sigs/metrics-server/1-29/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
projects/kubernetes-sigs/metrics-server/1-29/helm/patches/0002-Remove-Addon-Resizer.patch
projects/kubernetes-sigs/metrics-server/1-30/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
projects/kubernetes-sigs/metrics-server/1-30/helm/patches/0002-Remove-Addon-Resizer.patch
projects/kubernetes-sigs/metrics-server/1-31/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
projects/kubernetes-sigs/metrics-server/1-31/helm/patches/0002-Remove-Addon-Resizer.patch

This PR fixes 'remove-addon-resizer' patch and removes `rolebinding_nanny.yaml` file
*Testing*
* helm install of built chart on existing cluster
`helm install metrics-server oci://public.ecr.aws/registry_alias/metrics-server/charts/metrics-server --version 0.7.2-eks-1-29-23-8c6cb61c206f03c401b2799fc1291054eac7fb9d --set sourceRegistry=public.ecr.aws/registry_alias`

Fix remove-addon-resizer patch for metrics-server

---

projects/tinkerbell/hook/Makefile

We currently include the hook-kernel in the bundle as well as hook-docker and hook-bootkit.  This adds it to the list for combine and changes the DOCKERFILE_FOLDER handling to support it.

add kernel to hook combine-images list

---

projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
projects/kubernetes-sigs/cluster-api-provider-cloudstack/patches/0001-Support-re-assignment-of-another-failure-domain-when.patch
projects/kubernetes-sigs/cluster-api-provider-cloudstack/patches/0002-Add-latest-CAPC-minor-release-v0.5.0-to-metadata.yam.patch

[#2399](https://github.com/aws/eks-anywhere-internal/issues/2399)
A patch to update the minor version in metadata.yaml was added in [#3741](https://github.com/aws/eks-anywhere-build-tooling/pull/3741) to fix the CloudStack tests failing with a version validation error. But that fixed only the cluster creation tests. In order to fix the cluster upgrade tests, we need to have both the minor release version 4 and 5 in the metadata.yaml to pass the validations as currently the CloudStack OIDC tests fail with the following error:
```
Error: invalid provider metadata: version v0.4.10-rc1+d263e1a (the current version) for 
the provider capc-system/infrastructure-cloudstack does not match any release series
```
This PR adds a new patch updating …

Update patches and CHECKSUMS for CAPC v0.5.0

---

projects/kubernetes-sigs/image-builder/build/build_image.sh

This PR adds the logic to retry Nutanix image builds in case of internal server errors, since we have observed that these usually pass when retried.

Retry Nutanix image builds in case of internal server errors

---

tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/constants/constants.go

We have observed in the past that CAPI sometimes introduces breaking changes even for patch releases. Due to this, all our tests failed when we upgraded the CAPI patch version on a release branch. So, we decided not to upgrade CAPI anymore on release branches unless some customer requires some critical fix and they are still on a supported release branch. This PR updates the project upgrader tool to skip upgrading CAPI on release branches.
*Testing:*
```
make -C tools/version-tracker build
```

Skip CAPI upgrade on release branches

---

tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/constants/constants.go

Add identifying label `sig/curated-packages` to pull requests that upgrade curated packages.

Add identifying label to PRs upgrading curated packages

---

tools/version-tracker/pkg/commands/upgrade/upgrade.go

Fix labels assignment on pull requests

Fix labels assignment on pull requests

---

projects/kubernetes-sigs/kind/README.md
projects/kubernetes-sigs/kind/build/node-image-build-args.sh

Updating kindnetd and storage provisioner/helper images for Kind node image build. In the future, we should have the automation do this.

Update kindnetd and storage helper images for Kind node image build

---

projects/replicatedhq/troubleshoot/CHECKSUMS

The troubleshoot presubmit on #4042 first failed stating incorrect checksums, and then the checksums in the failure logs were used to update the CHECKSUMS file, but these failed in CodeBuild. This PR fixes the checksums with the correct ones reported in CodeBuild.

Fix checksums for replicatedhq/troubleshoot

---

projects/kubernetes-sigs/kind/Makefile
projects/kubernetes-sigs/kind/build/update_manifest_images.sh
tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/constants/constants.go

We maintain a [list of images](https://github.com/aws/eks-anywhere-build-tooling/blob/main/projects/kubernetes-sigs/kind/build/node-image-build-args.sh#L52-L61) that are referenced upstream in Kind's CNI and PV storage manifests and containerd config file. We use this list for [find-and-replace operations](https://github.com/aws/eks-anywhere-build-tooling/blob/main/projects/kubernetes-sigs/kind/build/build-kind-node-image.sh#L189-L194) on certain files on the Kind node image, to replace them with EKS-A kindnetd and local-path-provisioner/local-path-helper images and EKS-D pause image. When bumping Kind versions, the upstream tags may change, which requires us to update the image tags list otherwise the find-and-replace will fail.
This PR adds logic to update this image list whenever we …

Update kind manifest image tags during upgrade flow

---

projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0009-Support-and-improvements-for-RHEL-9-EFI.patch
projects/kubernetes-sigs/image-builder/patches/0010-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
projects/kubernetes-sigs/image-builder/patches/0011-Remove-containerd-configuration-for-hosts.toml-paths.patch
projects/kubernetes-sigs/image-builder/patches/0012-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
projects/kubernetes-sigs/image-builder/patches/0013-Revert-Optionally-source-etc-default-kubelet-in-kube.patch

I observed this in all the RedHat raw and CloudStack image builds
```console
qemu: TASK [sysprep : Remove subscriptions] ******************************************
qemu: fatal: [default]: FAILED! => {"changed": false, "msg": "value of state must be one of: enabled, disabled, got: absent"}
```
This task is defined [here](https://github.com/kubernetes-sigs/image-builder/blob/main/images/capi/ansible/roles/sysprep/tasks/redhat.yml#L58-L61).
The `community.general.rhsm_repository` is provided by the Ansible collection `community.general` and in version v10.0.0 of this collection, they removed the state `absent` and instead we need to use `disabled`.
In our builder-base image used in CI we have version `v9.4.0` of `community.general` collection which still supports `absent` state (although …

Add patch to fix state for Ansible RHSM repository module

---

projects/aws/image-builder/builder/types.go
projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0009-Support-and-improvements-for-RHEL-9-EFI.patch
projects/kubernetes-sigs/image-builder/patches/0010-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
projects/kubernetes-sigs/image-builder/patches/0011-Remove-containerd-configuration-for-hosts.toml-paths.patch
projects/kubernetes-sigs/image-builder/patches/0012-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
projects/kubernetes-sigs/image-builder/patches/0013-Revert-Optionally-source-etc-default-kubelet-in-kube.patch

Configuring Nutanix builds to always download the source images and delete them after build so that each build doesn't leave behind a copy of it.

Always download Nutanix source images and delete them after build

---

projects/tinkerbell/charts/helm/sedfile.template

In order for the `sed` command to work correctly, the sedfile should not have a leading `v` in the semver.

Fix Helm sedfile template for Tinkerbell charts

---

Common.mk
build/lib/generate_staging_buildspec.sh
projects/kubernetes-sigs/kind/Makefile
projects/kubernetes-sigs/kind/build/node-image-build-args.sh
projects/kubernetes-sigs/kind/buildspecs/base-images.yml
projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
projects/kubernetes-sigs/kind/buildspecs/binaries.yml
projects/kubernetes-sigs/kind/buildspecs/node-images.yml
release/checksums-build.yml
release/staging-build.yml
tools/version-tracker/buildspecs/upgrade.yml

We appear to be hitting some kind of qemu issue in codebuild when building the arm kind node image on an amd host. This attempts to work around this by breaking the builds out even further.  Instead of just by kube version, they are now by kube version and platform...

breaks kind batch build up even more

---

projects/replicatedhq/troubleshoot/CHECKSUMS

Fix ARM64 checksum for replicatedhq/troubleshoot to match the ones generated by Prow.

Fix ARM64 checksum for replicatedhq/troubleshoot

---

tools/version-tracker/SKIPPED_PROJECTS

Add containerd, CAPX, runc projects to upgrade skip list since the latest versions are not compatible.

Add containerd, CAPX, runc projects to upgrade skip list

---

projects/cert-manager/cert-manager/helm/patches/0001-Use-sourceRegistry-and-digest-in-chart.patch
projects/cert-manager/cert-manager/helm/patches/0002-Add-cert-manager-CRDs.patch
projects/cert-manager/cert-manager/helm/patches/0003-Remove-namespace-from-chart.patch
projects/cert-manager/cert-manager/helm/patches/0004-Update-cert-manager-namespace-config.patch
projects/cert-manager/cert-manager/helm/patches/0005-Update-values.schema.json-for-schema-validation.patch
projects/cert-manager/cert-manager/helm/schema.json

PR adds the helm patch to update the values.schema.json for schema validation.
In recent release of [cert-manager](https://github.com/cert-manager/cert-manager/tree/v1.16.1/deploy/charts/cert-manager), `values.schema.json` was added for schema validation, which caused package installation to fail as the properties needed by EKSA curated package(sourceRegistry, defaultNamespace, imagePullSecrets, imagePullPolicy) were missing, added the required properties in  `values.schema.json`.
Testing:
```
helm install cert-manager oci://public.ecr.aws/<personal-registry-alias>/cert-manager/cert-manager --version 1.16.1-67dc5c81b9313417ea3c285b3f4828b872df9b3c --set sourceRegistry=public.ecr.aws/<personal-registry-alias>
```
By submitting this pull request, I confirm that you …

Updated helm patch to include properties for eksa-packages in values.schema.json.

---

projects/tinkerbell/tink/docker/linux/tink-relay-init/Dockerfile

In the Tinkerbell Stack, `host_interface.sh` script is used to let smee serve dhcp traffic on host network. The script needs the [env](https://github.com/tinkerbell/charts/blob/44ca35d1249294af1224f4b2c4fe66b41b92f965/tinkerbell/stack/templates/init_configmap.yaml#L8) binary to run. Since the existing image doesn't contain the env binary, the chart installation fails. 

Add env binary to the image

---

EKSD_LATEST_RELEASES
tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/types/types.go

[#2855](https://github.com/aws/eks-anywhere-internal/issues/2855)
This PR adds the end of standard support dates for all Kubernetes versions starting from v1.28 onwards to indicate the start of extended support period for that version. This file will act as a source of truth for the start of extended support period for each supported kubernetes version.

Add end of standard support dates for all kubernetes versions above 1.28

---

projects/tinkerbell/tink/docker/linux/tink-relay-init/Dockerfile

`host-interface.sh` [script](https://github.com/tinkerbell/charts/blob/main/tinkerbell/stack/templates/init_configmap.yaml#L70) that's responsible to auto-discover the interface to serve dhcp traffic on host network, uses `getopt` binary, which is not present in the base image. Install the binary so that the script doesn't error out.  

Add getopt binary to tink-relay-init image

---

tools/version-tracker/SKIPPED_PROJECTS
tools/version-tracker/pkg/constants/constants.go
tools/version-tracker/pkg/github/github.go

Allow specifying maximum semvers for projects which have upgrade restrictions due to breaking changes, incompatibilities with other projects, etc.
```console
$ version-tracker display --project containerd/containerd
ORGANIZATION  REPOSITORY  CURRENT VERSION  LATEST VERSION  
containerd    containerd  v1.7.23          v2.0.1
```
```console
$ version-tracker display --project containerd/containerd
ORGANIZATION  REPOSITORY  CURRENT VERSION  LATEST VERSION  
containerd    containerd  v1.7.23          v1.7.24
```

Allow specifying maximum semvers for projects

---

Makefile
build/lib/generate_staging_buildspec.sh
buildspecs/upgrade-eks-distro-build-tooling-buildspec.yml
tools/version-tracker/buildspecs/upgrade.yml
tools/version-tracker/pkg/commands/display/display.go
tools/version-tracker/pkg/commands/listprojects/listprojects.go
tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/constants/constants.go

The EKS Distro base tag file updates were handled by a separate automation which was managed by scripts in the eks-distro-build-tooling repository, but by bringing it under the umbrella of the version tracker owned by us, we can control and fine-tune the automation as we see fit. Also we can now automate the bumps in all 3 branches whereas the previous automation just opened an update PR on main (for example, #4170) and we were required to manually backport to the release branches which has led to misses over the years.
Example PR with this change: https://github.com/abhay-krishna/eks-anywhere-build-tooling/pull/59

Add EKS Distro base tag files to version-tracker automation

---

tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/util/file/file.go

Trim trailing newlines in file before string comparison to avoid false positive diffs, for example, `v1.2.3\n` vs `v1.2.3`.

Trim trailing newlines in file before string comparison

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES

https://github.com/aws/eks-anywhere-internal/issues/2764
Add BR release v1.31.0 version for 1.32

Add BR release version for 1.32

---

projects/tinkerbell/hook/CHECKSUMS
projects/tinkerbell/hook/patches/0002-builds-kernel-from-al2.patch

The recent Hook builds in CI have been creating HookOS kernels that are booting without loading drivers from `modules.dep.bin` properly. The `modules.dep.bin` do not show up on running systems at all. This causes most hardware to fail to load important things like Network Interface Card drivers. 
Troubleshooting pointed us to a potential issue with Yum repo package changes that have caused the HookOS kernel builds to be missing the linkage between the kernel and the `modules.dep.bin`. We don't know definitively what has changed to the packages or why this happened. What we do know through troubleshooting and testing is that adding a few packages resolves the issues. Comparing the logs between previous working kernels and the newer kernels, there is at least one …

Update hook kernel with missing modules

---

tools/version-tracker/cmd/display.go
tools/version-tracker/pkg/commands/display/display.go
tools/version-tracker/pkg/constants/constants.go
tools/version-tracker/pkg/github/github.go
tools/version-tracker/pkg/types/types.go
tools/version-tracker/pkg/util/version/version.go

Improve display command for version tracker:
1. Versions table shows project versions for all currently-supported EKS-D release branches
2. Versions table includes up-to-date column to denote if project's current version matches latest upstream version
3. Github version retrieval supports projects which don't have a patch version in their semver
4. 

Improve display command for version tracker

---

tools/version-tracker/go.mod
tools/version-tracker/go.sum
tools/version-tracker/pkg/commands/display/display.go
tools/version-tracker/pkg/constants/constants.go
tools/version-tracker/pkg/ecrpublic/ecrpublic.go
tools/version-tracker/pkg/github/github.go
tools/version-tracker/pkg/util/semver/semver.go

Support tagging schemes of `envoyproxy/envoy` and `isc-projects/dhcp` projects in display command. Earlier these were being skipped. Now they all show up in the display command output.
```console
➜ bin/version-tracker display --project envoyproxy/envoy 
2025/02/20 11:31:38 Error displaying version information: getting latest revision from GitHub for project envoyproxy/envoy: getting epoch time corresponding to current revision commit: getting date for commit  in [envoyproxy/envoy] repository: GET https://api.github.com/repos/envoyproxy/envoy/commits/: 422 No commit found for SHA:  []
➜ bin/version-tracker display --project isc-projects/dhcp
2025/02/20 11:31:33 Error displaying version information: getting latest revision from GitHub for project isc-projects/dhcp: getting semver for …
```

Support envoyproxy/envoy, isc-projects/dhcp projects in display command

---

projects/fluxcd/source-controller/Makefile
release/checksums-build.yml
release/staging-build.yml
tools/version-tracker/buildspecs/upgrade.yml

The ARM checksum for fluxcd/source-controller in our codeBuild does not match what we have in eks-a-build-tooling projects, because CodeBuild uses ARM container to calculate the checksum.
Use LINUX_CONTAINER as build environment type for fluxcd/source-controller

Use LINUX_CONTAINER as build platform for fluxcd/source-controller

---

tools/version-tracker/pkg/util/version/version.go

Fix latest semver detection for release branches.

Fix latest semver detection for release branches

---

projects/aws/image-builder/cmd/build.go
projects/aws/image-builder/cmd/build_test.go

This PR updates the RHEL OS version validation from image builder OVA builds. Image builds for RHEL 9 OVAs were enabled in [CR-182119085](https://code.amazon.com/reviews/CR-182119085) but they failed with the following error:
```
failed=false
timeout 1.5h /home/imagebuilder/image-builder build --hypervisor vsphere 
--os redhat --os-version 9 --vsphere-config
/home/imagebuilder/image_builder_config_file --release-channel 1-28
Creating builder config
2025/03/08 23:31:09 Invalid OS version for RedHat. Please choose 8
```

Update RHEL OS version validation from image builder

---

projects/kubernetes-sigs/image-builder/build/validate_ova_kubelet.sh
projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
projects/kubernetes-sigs/image-builder/patches/0004-RHEL-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0005-Nutanix-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0006-adds-retries-and-timeout-to-packer-image-builder.patch
projects/kubernetes-sigs/image-builder/patches/0007-Networking-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0008-Support-and-improvements-for-RHEL-9-EFI.patch
projects/kubernetes-sigs/image-builder/patches/0009-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
projects/kubernetes-sigs/image-builder/patches/0010-Remove-containerd-configuration-for-hosts.toml-paths.patch
projects/kubernetes-sigs/image-builder/patches/0011-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
projects/kubernetes-sigs/image-builder/patches/0012-Make-configurable-Nutanix-image-size.patch
projects/kubernetes-sigs/image-builder/patches/0013-Update-Packer-VM-hardware-version-to-support-RHEL-9.patch

Add patch to fix RHEL 9 OVA builds
Fixes the following error
```
==> Some builds didn't complete successfully and had errors:
--> vsphere-iso.vsphere: No host is compatible with the virtual machine.
```
/hold

Add patch to fix RHEL 9 OVA builds

---

projects/kubernetes-sigs/image-builder/build/validate_ova_kubelet.sh

Fix kubelet file check inside image during OVA validation. This was not properly working due to the pipefail option

Fix kubelet file check inside image

---

tools/version-tracker/pkg/constants/constants.go

Pin CAPI project to version v1.9.4 until we identify why 1.9.5 is causing Tinkerbell tests to fail. This will prevent the bot from opening upgrade PRs for v1.9.5.
Ref: https://github.com/aws/eks-anywhere-build-tooling/pull/4442

Pin CAPI project to version v1.9.4

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/README.md
projects/aws/image-builder/builder/builder.go
projects/aws/image-builder/builder/constants.go
projects/aws/image-builder/builder/types.go

https://github.com/aws/eks-anywhere-internal/issues/3096
Allow `vmx_version` to be configurable in image-builder cli instead of always using the default value 15 from upstream image-builder. Also add a validation to prevent using vmx_version of less than 15.
*Testing:
1. Do not specify vmx_version in vsphere.json, the output ova has 15 as vm version
2. Specify 14 as vmx_version value, image-build failed during validation because the min version should be 15.
3. Specify 18 as vmx_version and build the ova, in the output .ovf file we can see the VirtualSystemType is override.
```
<VirtualHardwareSection>
<Info>Virtual hardware requirements</Info>
<System>
<vssd:ElementName>Virtual Hardware Family</vssd:ElementName> …
```

Allow vmx_version to be configurable in image-builder cli

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/README.md
projects/aws/image-builder/builder/builder.go
projects/aws/image-builder/builder/constants.go
projects/aws/image-builder/builder/types.go

Manually cherry-picked from https://github.com/aws/eks-anywhere-build-tooling/pull/4510

[release-0.22] Allow vmx_version to be configurable in image-builder cli

---

projects/kubernetes-sigs/metrics-server/EKS_ADDON_IMAGE_TAG

* Update metrics server to latest EKS Add-on Image version which resolves CVE issues in the current version
*Testing:*
- Tested using package install using helm on `VSphere Cluster`
-  Replicate image to personal repo
```
skopeo copy docker://602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/metrics-server:v0.7.2-eksbuild.3 docker://public.ecr.aws/g0y6o3v0/metrics-server/eks-distro/kubernetes-sigs/metrics-server:v0.7.2-eksbuild.3 -f oci --all
```
- Install package using helm
```
helm install metrics-server oci://public.ecr.aws/g0y6o3v0/metrics-server/charts/metrics-server --version 0.7.2-eksbuild.3-8b4f46cc05160e83cbce6eec328f4553cbc33243 --set sourceRegistry=public.ecr.aws/g0y6o3v0
```
By submitting this pull request, I confirm that you can use, modify, copy, and …

Update metrics server to latest EKS Addon Image version

---

EKSD_LATEST_RELEASES

Since eksd 1.28-44, the coredns version was changed from v1.11.1 to v1.10.1, this will cause trouble when user try to upgrade from 1.27 to 1.28 because 1.27 eksd is using coredns version v1.11.1 and component version cannot be downgraded during an upgrade.
Revert eksd version back to 1.28-43 until 1.28 has a new eksd release with coredns v1.11
https://distro.eks.amazonaws.com/releases/1-28/44/
https://distro.eks.amazonaws.com/releases/1-28/43/

[release-0.21] Revert EKS-D 1.28 back to 1.28-43

---

projects/distribution/distribution/CHECKSUMS
projects/distribution/distribution/Makefile

Got a build failure in codepipelines, so using the checksums generated from there specifically for the arm build. We also don't need the "include_oss" and "include_gcs" build tags as they are for specific cloud providers that we don't support. The redigo patch also seems outdated as the repo doesn't exist anymore.
```
_output/bin/distribution/linux-amd64/registry: OK
_output/bin/distribution/linux-arm64/registry: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
Checksums do not match!
```

Update checksums from build of distrbution upgrade

---

tools/version-tracker/pkg/constants/constants.go

https://github.com/aws/eks-anywhere-internal/issues/3112
*Description of changes:*    
CAPI project was pinned to 1.9.4 as subsequent versions were breaking metal tests. CAPT has a [fix](https://github.com/tinkerbell/cluster-api-provider-tinkerbell/pull/460) upstream in latest release that should be compatible with the latest versions of CAPI.

Remove hardcoded version pin for capi project in upgrader

---

projects/kubernetes-sigs/metrics-server/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
projects/kubernetes/autoscaler/1-30/helm/schema.json
projects/kubernetes/autoscaler/1-31/helm/schema.json
projects/kubernetes/autoscaler/1-32/helm/schema.json
projects/kubernetes/autoscaler/1-33/helm/schema.json

* Updated schema for autoscaler package.
* Updated patch for metrics-server to have correct repo name for metrics-server image.
*Testing*
* Verfied the package install on cluster with locally built package.

fix: Updated autoscaler schema and patch for metrics-server

---

Makefile

We do not need to generate the attribution files for packages on the nightly attribution job.

skip packages on attribution generation for release branches

---

projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
projects/kubernetes-sigs/cluster-api-provider-cloudstack/build/create_manifests.sh
projects/kubernetes-sigs/cluster-api-provider-cloudstack/patches/0001-Support-re-assignment-of-another-failure-domain-when.patch
projects/kubernetes-sigs/cluster-api-provider-cloudstack/patches/0002-Remove-kube-rbac-proxy.patch

In the CAPC upgrade from v0.5.0 to v0.6.0 cluster creation failed because CAPC controller pod kept crashing due to the 8443 port conflicts from [kube-rbac-proxy](https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/blob/main/config/default-with-metrics-port/manager_auth_proxy_patch.yaml#L15) and CAPI diagnostic feature (enabled in [v0.6.0](https://github.com/kubernetes-sigs/cluster-api-provider-cloudstack/blob/v0.6.0/config/manager/manager.yaml#L27))
Looks like int the past, rbac proxy was added as a workaround to serve metrics. With diagnostic feature enabled, I believe this rbac proxy is not needed because CAPI diagnostic feature now servers the same purpose - serving metrics endpoint via https (8443)and protected via …

Add patch for cloudstack to remove kube rbac proxy

---

projects/goharbor/harbor/docker/linux/harbor-portal/Dockerfile

[harbor-tooling-presubmit](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-anywhere-build-tooling/4600/harbor-tooling-presubmit/1947207287193997312) job is failing as it's unable to fetch apt repositories of buster release. This is because buster has reached end of life. So, we will be using archived repositories going forward. 

Use archived apt repositories for buster as original ones are deprecated

---

projects/tinkerbell/charts/helm/patches/0001-Load-stream-model-for-nginx-and-update-http2-command.patch
projects/tinkerbell/charts/helm/patches/0002-Fix-smee-deployment-tolerations-rendering.patch

Upstream chart values.yaml for smee had an issue rendering tolerations when Values.singleNodeClusterConfig.controlPlaneTolerationsEnabled is set to True. Patch the chart to conditionally apply tolerations when singleNodeClusterConfig settings are not set. With singleNodeClusterconfig set on the values-override yaml below is the error message we see:
`
{"stderr": "Pulled: public.ecr.aws/l0g8r8j6/tinkerbell/stack:0.6.2-eks-a-v0.24.0-dev-build.58\nDigest: sha256:26d12a718d65781f728fd3ca2f7022986f128ac51a8ba6a879396ab3bfe3606c\nError: YAML parse error on stack/charts/smee/templates/deployment.yaml: error converting YAML to JSON: yaml: line 128: did not find expected key\n"}
` 
Testing: 
Built a patched version of chart and was able to deploy …

Patch smee deployment.yaml on upstream chart

---

tools/version-tracker/pkg/constants/constants.go

We paused helm updates since we were having issues with proxy in an air gapped environment with the issue https://github.com/helm/helm/issues/30719 and https://github.com/helm/helm/issues/30816.
Resuming helm updates now since upstream seems to have fixed the issue https://github.com/helm/helm/pull/30590.

Resume helm updates

---

projects/tinkerbell/ipxedust/CHECKSUMS
projects/tinkerbell/ipxedust/patches/0001-do-not-use-nix-shell-for-building.patch
projects/tinkerbell/ipxedust/patches/0002-Enhance-iPXE-boot-script-interface-checks-retries-VL.patch
projects/tinkerbell/ipxedust/patches/0003-Bump-Ipxe-commit-and-fix-gcc-build-issues.patch

Some new NIC drivers such as BCM57504, BCM57412 aren't supported by the existing binaries that ipxedust serves.
Updates the iPXE commit from a year-old version to the latest upstream to include recent driver support and bug fixes that have been added over time. 

Bump iPXE commit to latest upstream

---

projects/kubernetes/cloud-provider-aws/1-32/CHECKSUMS
projects/kubernetes/cloud-provider-aws/1-33/CHECKSUMS

aws-eks-anywhere-build-tooling-checksums-update [codebuild job](https://tiny.amazon.com/y79lh06p/IsenLink) missed updating checksums in [PR](https://github.com/aws/eks-anywhere-build-tooling/pull/4812)

Fix ecr-credential-provider checksums for new builder-base

---

projects/aws/image-builder/builder/builder.go
projects/aws/image-builder/builder/constants.go
projects/aws/image-builder/builder/types.go
projects/aws/image-builder/cmd/build.go

1-33-redhat-8-raw, 1-30-redhat-8-raw, 1-29-redhat-8-raw, 1-28-redhat-8-raw builds are failing due to packer builder vm running out of default configured 6gb disk size, with the latest eks-d release. 
This PR configures the default disk size for raw image building to 6.5gb overriding the [upstream default](https://github.com/kubernetes-sigs/image-builder/blob/main/images/capi/packer/raw/packer.json.tmpl#L173) of 6gb using [user defined packer config parameter](https://github.com/kubernetes-sigs/image-builder/blob/main/images/capi/packer/raw/packer.json.tmpl#L16)

Increase default disk size for raw image-builder builds

---

Common.mk
projects/containerd/containerd/Makefile

Reverting Common.mk change made for containerd as it caused the word function to evaluate against a non-matching entry, producing below error in the kind build,
```
first argument to 'word' function must be greater than 0
```
This PR should fix this issue.

Fix kind build

---

projects/kubernetes-sigs/image-builder/build/build_image.sh

Add url of Ubuntu 24.04 image for Nutanix Ubuntu 24.04 build.

Add image_url for Nutanix Ubuntu 24.04

---

projects/aws/eks-a-admin-image/eks-a-admin-snow.pkr.hcl

Snow cluster provision failed as the admin instance does not have enough space to extract and import container images
```
Error: loading docker image mover source: loading images from file: write /usr/bin/dockerd: no space left on device
```
Increase the disk size from 60G to 70G

increase disk size of Snow admin machine from 60G to 70G
