projects/kubernetes-sigs/kind/build/build-kind-node-image.sh

Fix docker URI in kind node image script

---

projects/aws/eks-anywhere/docker/linux/eksa-diagnostic-collector/Dockerfile

update base image comment to reflect reality

update base image comment to reflect reality

---

projects/aws/eks-anywhere/Makefile
projects/fluxcd/flux2/Makefile
projects/fluxcd/helm-controller/Makefile
projects/fluxcd/kustomize-controller/Makefile
projects/fluxcd/notification-controller/Makefile
projects/fluxcd/source-controller/Makefile
projects/jetstack/cert-manager/Makefile
projects/kubernetes-sigs/cluster-api-provider-aws/Makefile
projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
projects/kubernetes-sigs/vsphere-csi-driver/Makefile
projects/kubernetes/cloud-provider-vsphere/Makefile
projects/plunder-app/kube-vip/Makefile
projects/replicatedhq/troubleshoot/Makefile

remove goproxy overrides so in prow these use athens

---

EKSD_LATEST_RELEASES

bump to latest eks-d release

---

README.md
build/lib/cherry_pick_pull.sh
docs/development/cherry-picks.md

add script to support backporting to release branches

---

projects/fluxcd/source-controller/Makefile
projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/kind/Makefile
projects/kubernetes-sigs/vsphere-csi-driver/Makefile
projects/kubernetes/cloud-provider-vsphere/Makefile

Make Clone URLs region specific.

Make Clone URLs region specific

---

projects/cilium/cilium/build/upload_artifacts.sh
projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
projects/kubernetes-sigs/cluster-api-provider-vsphere/build/upload_artifacts.sh
projects/kubernetes-sigs/image-builder/build/upload_artifacts.sh
projects/kubernetes-sigs/kind/build/upload_artifacts.sh
projects/kubernetes-sigs/vsphere-csi-driver/build/upload_artifacts.sh
projects/kubernetes/cloud-provider-vsphere/Makefile
projects/kubernetes/cloud-provider-vsphere/build/upload_artifacts.sh

Fixed artifacts upload script for some projects.

Fix artifacts upload script for projects

---

EKSD_LATEST_RELEASES

* Bumped the EKS-D versions to the latest releases. The Kubernetes versions did not change for these releases.

Updated the EKS-D versions to the latest ones

---

build/lib/upload_artifacts.sh
projects/kubernetes-sigs/kind/build/build-kind-node-image.sh

This one should cover all projects using Common makefile.

More fixup for uploading artifacts

---

release/staging-build.yml

Install openssl in staging build yaml

Install openssl in staging build release

---

build/lib/create_release_checksums.sh
projects/cilium/cilium/Makefile
projects/cilium/cilium/build/create_manifests.sh
projects/cilium/cilium/expected_artifacts

cilium: convert to common.mk

---

projects/aws/eks-anywhere/.gitignore
projects/aws/eks-anywhere/Makefile
projects/aws/eks-anywhere/build/fetch_binaries.sh
projects/aws/eks-anywhere/docker/linux/Dockerfile

diag-image: switch to common.mk

---

projects/fluxcd/source-controller/Makefile

Adding this target so `POST_BUILD` phase doesn't complain.

Add target to upload source controller artifacts

---

projects/fluxcd/source-controller/build/upload_artifacts.sh

Adding the script that will be invoked when the uploads target is triggered.

Add upload artifacts script for source controller project

---

UPSTREAM_PROJECTS.yaml
build/lib/generate_projects_list.sh
docs/development/add-new-project.md
hack/boilerplate.yq.txt
projects/mrajashree/etcdadm-bootstrap-provider/README.md
projects/mrajashree/etcdadm-controller/README.md

- Add versions to generated projects manifest.
- Update tags in README for `etcdadm-bootstrap-provider` and `etcdadm-controller` projects.

Add version info to generated list, update tags in README

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh
projects/kubernetes-sigs/image-builder/packer/config/additional_components.json.tmpl
projects/kubernetes-sigs/image-builder/packer/config/validate_goss_inline_vars.json.tmpl
projects/kubernetes-sigs/image-builder/patches/0007-additional-eks-specific-goss-validations.patch

Reverting PR #168 to assess OVA build flakiness.

Revert "image-builder: improve ova built stability (#168)"

---

projects/kubernetes-sigs/kind/Makefile
projects/kubernetes-sigs/kind/build/node-image-build-args.sh
projects/kubernetes-sigs/kind/buildspec.yml

Fix tagging for kind node image dependencies

---

Common.mk

fix attribution target for the typical ATTRIBUTION.txt targets

---

projects/aws/eks-anywhere-build-tooling/Makefile
projects/aws/eks-anywhere-build-tooling/README.md
projects/aws/eks-anywhere-build-tooling/build/fetch_binaries.sh
projects/aws/eks-anywhere-build-tooling/docker/linux/Dockerfile

eks-a-tools: switch to common.mk

---

projects/aws/eks-anywhere-build-tooling/Makefile

cli-tools: fix image component

---

projects/kubernetes-sigs/kind/build/build-kind-node-image.sh

kind: fix embedded arm images

---

projects/kubernetes-sigs/etcdadm/CHECKSUMS
projects/kubernetes-sigs/etcdadm/patches/0010-Support-linux-other-arch.patch

etcadm: fix pull arm64 tar

---

projects/kubernetes-sigs/kind/images/node/Dockerfile

kind: arm64 support for etcd when run with etcdadm

---

Common.mk

buildkit: enable inline caching in latest image

---

build/lib/validate_artifacts.sh
projects/kubernetes-sigs/kind/Makefile
projects/kubernetes-sigs/kind/expected_artifacts
projects/kubernetes-sigs/kind/images/node/Dockerfile

kindnetd: extract manifest for use in capd cluster

---

projects/kubernetes-sigs/kind/Makefile
projects/kubernetes-sigs/kind/expected_artifacts

kindnetd: fix manifest targets and artifacts

---

projects/aws/eks-anywhere-build-tooling/docker/linux/Dockerfile

cli-tools: add sleep binary for reusing the container

---

Common.mk
projects/kubernetes-sigs/kind/Makefile

only export image cache when pushing images

---

Common.mk
build/update-attribution-files/create_pr.sh
build/update-attribution-files/make_attribution.sh

update checksums in attribution periodic

---

Common.mk
build/lib/buildkit.sh
build/lib/update_checksum_docker.sh
build/lib/validate_artifacts.sh
build/update-attribution-files/create_pr.sh
docs/development/add-new-project.md

small changes to common scripts to better match eks-distro

---

Common.mk
Makefile
docs/development/building-locally.md
projects/cilium/cilium/buildspec.yml
projects/fluxcd/flux2/buildspec.yml
projects/kubernetes-sigs/cluster-api-provider-aws/buildspec.yml
projects/kubernetes-sigs/cluster-api/buildspec.yml
projects/kubernetes-sigs/cri-tools/buildspec.yml
projects/kubernetes-sigs/etcdadm/buildspec.yml

remove release-upload and use release in buildspecs

---

EKSD_LATEST_RELEASES
projects/kubernetes-sigs/kind/buildspec.yml

fix image-builder and kind

---

projects/kubernetes-sigs/image-builder/Makefile

We deleted this script in the previous commit.

Remove unnecessary script invocation

---

projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
projects/kubernetes-sigs/cluster-api-provider-vsphere/expected_artifacts

CAPV has manifests which need to be uploaded to S3.

Mark CAPV as producing S3 artifacts

---

projects/mrajashree/etcdadm-bootstrap-provider/manifests/metadata.yaml
projects/mrajashree/etcdadm-controller/manifests/metadata.yaml

Add v1beta1 contract for etcdadm providers

---

Common.mk
build/lib/helm_build.sh
build/lib/helm_push.sh
projects/aws/eks-anywhere-test/Makefile
projects/aws/eks-anywhere-test/helm/Chart.yaml.template
projects/aws/eks-anywhere-test/helm/eks-anywhere-test/values.yaml
projects/aws/eks-anywhere-test/helm/values.yaml.template

Attempting to simplify previous PR

Break helm build and push into two scripts

---

projects/aws/eks-anywhere-test/conf/entrypoint.sh
projects/aws/eks-anywhere-test/conf/index.template
projects/aws/eks-anywhere-test/helm/eks-anywhere-test/templates/deployment.yaml
projects/aws/eks-anywhere-test/helm/eks-anywhere-test/templates/pvc.yaml

Two things here:
* Added PVC to test helm chart
* Changed helm chart so it pulls the matching image tag

Add pvc to chart

---

projects/kubernetes-sigs/cluster-api-provider-vsphere/Makefile
projects/kubernetes-sigs/cluster-api-provider-vsphere/expected_artifacts
projects/mrajashree/etcdadm-bootstrap-provider/Makefile
projects/mrajashree/etcdadm-bootstrap-provider/build/create_manifests.sh
projects/mrajashree/etcdadm-bootstrap-provider/expected_artifacts
projects/mrajashree/etcdadm-controller/Makefile
projects/mrajashree/etcdadm-controller/build/create_manifests.sh
projects/mrajashree/etcdadm-controller/expected_artifacts

Backporting #235 to v1beta1 branch. 

Mark CAPV, etcdadm bootstrap provider and controller as producing S3 artifacts

---

projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh

Backporting changes from #244 to v1beta1 branch.

Remove trailing parenthesis in script

---

Common.mk

source-controller: fix cgo builder image to be builder-base

---

Common.mk

Made this change yesterday on the v1beta1 branch.

fix latest tag for other branches

---

build/update-attribution-files/create_pr.sh

fix create_pr for attribution on release branches

---

projects/kubernetes-sigs/cluster-api/Makefile

https://github.com/aws/eks-anywhere-build-tooling/issues/198
Update base image for capd

Update base image for capd

---

Common.mk
build/lib/install_go_versions.sh
build/update-attribution-files/create_pr.sh
projects/kubernetes-sigs/image-builder/Makefile

attribution: fix periodic and add support for release-branch periodic

---

Common.mk
build/lib/install_go_versions.sh
build/update-attribution-files/create_pr.sh
projects/aws/bottlerocket-bootstrap/ATTRIBUTION.txt
projects/fluxcd/flux2/ATTRIBUTION.txt
projects/fluxcd/helm-controller/ATTRIBUTION.txt
projects/fluxcd/kustomize-controller/ATTRIBUTION.txt
projects/fluxcd/notification-controller/ATTRIBUTION.txt
projects/fluxcd/source-controller/ATTRIBUTION.txt
projects/jetstack/cert-manager/ATTRIBUTION.txt
projects/kubernetes-sigs/cluster-api-provider-vsphere/ATTRIBUTION.txt
projects/kubernetes-sigs/etcdadm/ATTRIBUTION.txt
projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/kind/ATTRIBUTION.txt
projects/kubernetes-sigs/vsphere-csi-driver/ATTRIBUTION.txt
projects/kubernetes/cloud-provider-vsphere/1-20/ATTRIBUTION.txt
projects/kubernetes/cloud-provider-vsphere/1-21/ATTRIBUTION.txt
projects/mrajashree/etcdadm-bootstrap-provider/ATTRIBUTION.txt
projects/mrajashree/etcdadm-controller/ATTRIBUTION.txt
projects/plunder-app/kube-vip/ATTRIBUTION.txt

Update attributions - release 0.6

---

.gitignore

Add vi swp file to gitignore

---

projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0002-Modifying-workflow-action-to-image2disk.patch

Adding a CAPT patch to modify the workflow actions template

Adding a patch for CAPT template actions

---

EKSD_LATEST_RELEASES

bump eks-d release numbers

---

projects/helm/helm/buildspec.yml

helm: add buildspec

---

projects/aws/eks-anywhere-build-tooling/Makefile
projects/aws/eks-anywhere-build-tooling/build/organize_binaries.sh

After #283  merges, this will addd helm to the cli tools image.
/hold

cli-tools: add helm cli to cli tools image

---

Common.mk

Backporting #293 to release-0.6

Fix image tagging for release-branch specific projects

---

Common.mk
Makefile
build/lib/generate_help_body.sh
build/update-attribution-files/create_pr.sh

add help update to periodic and cleanup helm help

---

docs/development/attribution-files.md

Fix readme links

---

projects/jetstack/cert-manager/Makefile
projects/jetstack/cert-manager/helm/patches/0003-Activate-digests-with-templates.patch
projects/jetstack/cert-manager/helm/sedfile.template

Change the cert-manager helm chart to use image digest

Have the cert-manager helm chart use digest

---

UPSTREAM_PROJECTS.yaml

Updating the project versions we vend.

Update tags in upstream projects tracker

---

projects/cilium/cilium/Makefile

Fix Cilium release targets

---

projects/kubernetes-sigs/image-builder/patches/0004-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch

Fix image-builder patch

---

EKSD_LATEST_RELEASES

Update to latest eks-d versions

---

OWNERS

N/A
I'm not day-to-day working on this, and don't need approver permissions (or notifications)

Remove micahhausler from approvers

---

projects/tinkerbell/tink/Makefile
projects/tinkerbell/tink/expected_artifacts

upload tink artifacts to the s3 bucket

---

projects/aws/eks-anywhere-build-tooling/Makefile
projects/aws/eks-anywhere-build-tooling/build/organize_binaries.sh

add tink-cli binary to CLI tools image

---

Makefile

Build Helm and Tink projects as CLI tools image prerequisites.

Build Helm during staging build

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_OVA_RELEASES

Update BR version to 1.5.3

---

UPSTREAM_PROJECTS.yaml
projects/kubernetes-sigs/cluster-api/README.md
projects/mrajashree/etcdadm-bootstrap-provider/README.md
projects/mrajashree/etcdadm-controller/README.md

Update version references for cluster-api and etcdadm

---

projects/kubernetes-sigs/image-builder/build/build_raw_image.sh

Configure the EC2 instance for raw image builds to be created in one of the subnets used by Codebuild and configured with same security group.

Run EC2 instance in Codebuild's subnet and security group

---

projects/kubernetes-sigs/image-builder/build/build_raw_image.sh

The packer log parent folder must already exist.

Move raw image build packer log one level up

---

projects/kubernetes-sigs/kind/Makefile

Create manifest target directory

---

EKSD_LATEST_RELEASES

Increment the release to eksd release 2

Point to eksd release 2

---

projects/tinkerbell/pbnj/docker/linux/Dockerfile

Add pbnj files to the image

---

projects/tinkerbell/pbnj/docker/linux/Dockerfile

Re-order dockerfile copy root to the top

---

projects/tinkerbell/pbnj/docker/linux/Dockerfile

Fix install cmd for pbnj

---

projects/aws/eks-anywhere-test/eks-anywhere-test/Chart.yaml

Closes https://github.com/aws/modelrocket-add-ons/issues/242

Rename add-on => package

---

OWNERS

Add chrisdoherty4 to OWNERS

---

projects/tinkerbell/boots/README.md
projects/tinkerbell/hegel/README.md
projects/tinkerbell/pbnj/README.md
projects/tinkerbell/sandbox/.env
projects/tinkerbell/sandbox/README.md
projects/tinkerbell/sandbox/docker-compose.yml
projects/tinkerbell/sandbox/registry/registry_images.txt
projects/tinkerbell/sandbox/registry/upload.sh
projects/tinkerbell/sandbox/tls/ca-config.json
projects/tinkerbell/sandbox/tls/ca-csr.json
projects/tinkerbell/sandbox/tls/csr.json
projects/tinkerbell/sandbox/tls/generate.sh
projects/tinkerbell/sandbox/tls/trust.sh
projects/tinkerbell/tink/README.md

Add tinkerbell stack to tinkerbell project

---

EKSD_LATEST_RELEASES

* Bumped all EKS-D versions for all releases
* Changed 1.22 Kubernetes version from 1.22.4 to 1.22.6

Updated EKS-D versions

---

projects/aws/cluster-api-provider-aws-snow/manifests/infrastructure-components.yaml

Make snow controller image configurable

---

build/lib/image_shasum.sh

```
% ./build/lib/image_shasum.sh public.ecr.aws/j0a1m4z9 eks-anywhere-test latest
+ set -o errexit
+ set -o nounset
+ set -o pipefail
+ REGISTRY=public.ecr.aws/j0a1m4z9
+ REPOSITORY=eks-anywhere-test
+ IMAGE_TAG=latest
++ mktemp
+ TMPFILE=/var/folders/z6/10v9t4_d4lv318kzzlfsmfwxwr43d7/T/tmp.c9XyWeEN
+ trap 'rm -f /var/folders/z6/10v9t4_d4lv318kzzlfsmfwxwr43d7/T/tmp.c9XyWeEN' exit
+ TARGET=public.ecr.aws/j0a1m4z9/eks-anywhere-test:latest
+ skopeo inspect -n --raw docker://public.ecr.aws/j0a1m4z9/eks-anywhere-test:latest
+ skopeo manifest-digest /var/folders/z6/10v9t4_d4lv318kzzlfsmfwxwr43d7/T/tmp.c9XyWeEN
sha256:402e19f08df3a7f651a32ced51f72048af6eeab01f9c9e3c4c28cf94a9f27352
+ rm -f /var/folders/z6/10v9t4_d4lv318kzzlfsmfwxwr43d7/T/tmp.c9XyWeEN
```

Convert image_shasum.sh to use skopeo

---

EKSD_LATEST_RELEASES

eks-d: update to dev release 5 of 1.22

---

projects/aws/cluster-api-provider-aws-snow/manifests/infrastructure-components.yaml

Update CAPAS infrastructure components

---

projects/goharbor/harbor/helm/patches/0001-add-digest-support.patch

Update default registry for Harbor helm chart

---

projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap.sh
projects/kubernetes-sigs/image-builder/packer/ami/additional_files/generate-kube-vip-manifest.sh

Fix DNI ip leasing failure via DHCP
* Set hostname before DNI configuration to give the instance a unique
host name in the DHCP request
* Add `send-hostname` and `hostname` overrides to netplan config file,
to force the DHCP request using correct hostname in the message
* Retry `netplan apply` if we don't see ip assigned after 10s
Fixed typo: missing fi
Add some logging

Improve bootstrap scripts for Snow AMI

---

projects/kubernetes-sigs/etcdadm/CHECKSUMS
projects/kubernetes-sigs/etcdadm/patches/0013-Increase-wait-backoff-retries-during-join.patch

Increase default number of retries during join

---

projects/aws/cluster-api-provider-aws-snow/manifests/infrastructure-components.yaml

Pull CAPAS image from public repo

---

projects/aws/eks-anywhere-packages/README.md

Fix the readme badge now that the pipeline was created.

Fix build pipeline readme

---

projects/aws/cluster-api-provider-aws-snow/manifests/metadata.yaml

Update snow metadata

---

projects/kubernetes-sigs/image-builder/build/export-ami-to-s3.sh

Make latest raw ami in s3 public

---

projects/aws/cluster-api-provider-aws-snow/Makefile

Update upstream CAPAS image registry repo name

---

EKSD_LATEST_RELEASES

Updated dev release to 1.22-7

---

EKSD_LATEST_RELEASES

Combined previous 5 PRs into just one to avoid additional builds.
Need to merge first: https://github.com/aws/eks-anywhere-build-tooling/pull/569

eks-d: update to latest dev releases

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/build_qemu_rhel_local.sh

Fix local image building for RHEL

---

projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap-after.sh
projects/kubernetes-sigs/image-builder/packer/ami/additional_files/bootstrap.sh
projects/kubernetes-sigs/image-builder/packer/ami/additional_files/generate-kube-vip-manifest.sh
projects/kubernetes-sigs/image-builder/packer/ami/additional_files/logging.sh
projects/kubernetes-sigs/image-builder/packer/ami/ansible_extra_vars.yaml

Added logging to Snow AMI bootstrap scripts.

Added logging to Snow AMI bootstrap scripts.

---

EKSD_LATEST_RELEASES
projects/kubernetes-sigs/image-builder/Makefile

* Holding but ready to be merged when Jackson/whoever wants to merge this
/hold

Updated EKS-D prod releases and 1-22 dev

---

release/staging-build.yml

This PR modifies the staging release buildspec to support Codebuild batch builds.
/hold

Modify staging release buildspec to support batch builds

---

EKSD_LATEST_RELEASES

Update to the latest and greatest of EKS-D

Update latest to 1-22

---

projects/helm/helm/CHECKSUMS
projects/helm/helm/patches/0001-Insecure-flag-for-oci-push-pull-install.patch

Patch for adding insecure registry flag for pull, push and install

---

release/staging-build.yml

make flux2 dependent on source_controller build

---

projects/aws/eks-anywhere-test/eks-anywhere-test/templates/_helpers.tpl
projects/aws/eks-anywhere-test/eks-anywhere-test/templates/deployment.yaml
projects/aws/eks-anywhere-test/eks-anywhere-test/values.yaml
projects/aws/eks-anywhere-test/helm/requires-config.yaml

Use the sourceRegistry for the test app

Add source registry

---

projects/fluxcd/flux2/Makefile
projects/jetstack/cert-manager/Makefile

Disable cert-manager and flux helm builds

---

EKSD_LATEST_RELEASES

Updated EKS-D dev for 1.22-10

---

EKSD_LATEST_RELEASES

Updated EKS-D prod for 1.22-4

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
projects/kubernetes-sigs/image-builder/patches/0008-Add-support-for-RHEL-8-RAW-image-builds.patch

* Adding RHEL 8 image builds to CI
* Changing Ubuntu Raw images to be built with EFI support

Build Ubuntu raw images with EFI support, add RHEL 8 raw builds

---

projects/kubernetes-sigs/image-builder/build/build_raw_image.sh
projects/kubernetes-sigs/image-builder/patches/0008-Add-support-for-RHEL-8-RAW-image-builds.patch

Fixing some issues with SSH communicator.

Revert order swapping of Ubuntu partitions

---

build/lib/helm_require.sh

Couple things going on here, build works fine locally, but failing in pipeline
* pipeline builds in private and pushes to public
* we want the helm chart to pull from public
* the images are not available in private, but they are promoted to public after the build
* since the images may be coming from private or public, we check both

Fix the pipeline build for charts

---

Common.mk
Makefile
build/lib/common.sh
build/lib/install_go_versions.sh
projects/apache/cloudstack-cloudmonkey/CHECKSUMS
projects/aws/cluster-api-provider-cloudstack/CHECKSUMS
projects/grpc-ecosystem/grpc-health-probe/CHECKSUMS
release/staging-build.yml

We forget to add projects to the all_projects list sometimes which will cause issues when we do things like update golang versions and then miss updating checksums via the periodic job. 
Also brings in updates from https://github.com/aws/eks-distro/pull/848

add missing projects to all_projects list and update checksums

---

projects/tinkerbell/hook/Makefile

hook: use latest var instead of hardcoded latest

---

Common.mk
UPSTREAM_PROJECTS.yaml
build/lib/validate_artifacts.sh
projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/buildspecs/build-1-20-rhel-ova.yml
projects/kubernetes-sigs/image-builder/buildspecs/build-1-20-rhel-raw.yml
projects/kubernetes-sigs/image-builder/buildspecs/build-1-20-ubuntu-raw.yml
projects/kubernetes-sigs/image-builder/buildspecs/build-1-21-rhel-ova.yml
projects/kubernetes-sigs/image-builder/buildspecs/build-1-21-rhel-raw.yml
projects/kubernetes-sigs/image-builder/buildspecs/build-1-21-ubuntu-ova.yml
projects/kubernetes-sigs/image-builder/buildspecs/build-1-21-ubuntu-raw.yml
projects/kubernetes-sigs/image-builder/buildspecs/build-1-22-rhel-ova.yml
projects/kubernetes-sigs/image-builder/buildspecs/build-1-22-rhel-raw.yml
projects/kubernetes-sigs/image-builder/buildspecs/build-1-22-ubuntu-ova.yml
projects/kubernetes-sigs/image-builder/expected_artifacts_ova
projects/kubernetes-sigs/image-builder/expected_artifacts_raw
projects/kubernetes-sigs/image-builder/patches/0009-Add-support-for-RHEL-8-OVA-builds.patch

* Adding buildspecs for RHEL 8 OVA and Raw image builds.
* Adding patch to support RHEL 8 OVA builds in image-builder.

Add buildspecs for RHEL 8 OVA and Raw image builds

---

projects/tinkerbell/hub/Makefile
projects/tinkerbell/hub/docker/linux/reboot/Dockerfile

Add reboot Tinkerbell action image to hub

Add reboot action to hub

---

projects/goharbor/harbor/helm/patches/0001-add-digest-support.patch

Rename imageRegistry to sourceRegistry

---

build/lib/helm_require.sh

Add the tag to the requires.yaml for images:
```
---
kind: EksaPackageRequires
metadata:
name: eks-anywhere-packages-0.1.6-d9445c8c5fb88710487ac5c9ee2ac00cf1f00a6b
namespace: eksa-packages
spec:
images:
- repository: eks-anywhere-packages
tag: v0.1.6-d9445c8c5fb88710487ac5c9ee2ac00cf1f00a6b
digest: sha256:83d383690372991d2b9a58a798ad1676333a4ca0f45caaba841831be5b910495
- repository: brancz/kube-rbac-proxy
tag: v0.8.0-eks-a-v0.0.0-dev-release-0.8-build.0
digest: sha256:1be94d8bd371034d7050c3a688838c5439c98f700f101c466d18ebf9963f34af
configurations:
- name: sourceRegistry
- ```

Populate tag in helm chart requires.yaml

---

projects/aws-containers/hello-eks-anywhere/Makefile

Reverts aws/eks-anywhere-build-tooling#706

Revert "Fixing hello build job"

---

projects/aws/eks-a-snow-admin-image/Help.mk
projects/aws/eks-a-snow-admin-image/Makefile
projects/aws/eks-a-snow-admin-image/README.md
projects/aws/eks-a-snow-admin-image/build/export-ami-to-s3.sh
projects/aws/eks-a-snow-admin-image/build/get_kubectl_url.sh
projects/aws/eks-a-snow-admin-image/provisioners/cleanup.sh
projects/aws/eks-a-snow-admin-image/provisioners/download_eksa_artifacts.sh
projects/aws/eks-a-snow-admin-image/provisioners/install_docker.sh
projects/aws/eks-a-snow-admin-image/provisioners/install_eksa.sh
projects/aws/eks-a-snow-admin-image/provisioners/install_kubectl.sh
projects/aws/eks-a-snow-admin-image/provisioners/test/download_eksa_artifacts.sh
projects/aws/eks-a-snow-admin-image/provisioners/test/install_docker.sh
projects/aws/eks-a-snow-admin-image/provisioners/test/install_eksa.sh
projects/aws/eks-a-snow-admin-image/provisioners/test/install_kubectl.sh
projects/aws/eks-a-snow-admin-image/provisioners/upgrade_linux.sh
projects/aws/eks-a-snow-admin-image/snow-admin.pkr.hcl

https://github.com/aws/eks-anywhere/issues/1166
TODO

Snow EKS-A admin AMI packer build

---

projects/kubernetes-sigs/image-builder/patches/0008-Add-support-for-RHEL-8-RAW-image-builds.patch
projects/kubernetes-sigs/image-builder/patches/0009-Add-support-for-RHEL-8-OVA-builds.patch
projects/kubernetes-sigs/image-builder/patches/0010-Install-Open-VM-tools-for-RHEL-8-OVA-builds.patch

Hopefully should fix IP timeout problems.

Add patch to install Open VM tools during RHEL 8 OVA build

---

EKSD_LATEST_RELEASES

* Related PRs:
* https://github.com/aws/eks-distro/pull/870
* https://github.com/aws/eks-distro/pull/872
* https://github.com/aws/eks-distro/pull/874
* https://github.com/aws/eks-distro/pull/875
---

Bumped EKS-D prod versions for 1.19-1.22

---

Common.mk
docs/development/add-new-project.md
projects/aws/bottlerocket-bootstrap/Makefile
projects/goharbor/harbor/Makefile
projects/kubernetes-sigs/cluster-api-provider-aws/Makefile
projects/kubernetes-sigs/cluster-api/Makefile
projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/kind/CHECKSUMS
projects/kubernetes-sigs/kind/Makefile
projects/kubernetes-sigs/kind/expected_artifacts
projects/kubernetes/cloud-provider-vsphere/Makefile
projects/tinkerbell/cluster-api-provider-tinkerbell/Makefile
projects/tinkerbell/hook/Makefile
projects/tinkerbell/hub/Makefile

better handling for projects with multiple go mod paths

---

UPSTREAM_PROJECTS.yaml

Update notification controller git tag to latest in upstream projects tracker.

Update notification controller git tag in upstream projects tracker

---

build/lib/buildkit.sh
projects/fluxcd/source-controller/CHECKSUMS

Fix source controller

---

projects/kubernetes-sigs/image-builder/patches/0008-Add-support-for-RHEL-8-RAW-image-builds.patch
projects/kubernetes-sigs/image-builder/patches/0009-Add-support-for-RHEL-8-OVA-builds.patch

Installl gdisk for disk partitioning.

Install gdisk utility on RHEL 8 OS images

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
projects/kubernetes-sigs/image-builder/BOTTLEROCKET_OVA_RELEASES

Bump Bottlerocket version to their latest release.

Bump bottlerocket OVA version to latest

---

EKSD_LATEST_RELEASES

new eks-d releases

---

projects/tinkerbell/cluster-api-provider-tinkerbell/CHECKSUMS
projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0015-Make-hardware-template-workflow-CRDs-namespace-scope.patch

Patch to change hardware, template, workflow CRDs to namespaced scope

---

release/staging-build.yml

Trying to get eks anywhere packages included in the build/release process.

Build eks-anywhere-packages and include it in releases

---

projects/goharbor/harbor/helm/patches/0001-add-digest-and-namespace-support.patch

add namespace to all nginx service types

---

projects/goharbor/harbor/README.md
projects/goharbor/harbor/helm/patches/0001-add-digest-and-namespace-support.patch

update harbor badge and sourceRegistry

---

projects/kubernetes-sigs/image-builder/build/build_raw_image.sh

Add retry to EC2 instance creation in raw image build.

Add retries to EC2 instance creation

---

projects/kubernetes-sigs/image-builder/build/build_raw_image.sh

We need to use the Availability zone that the subnet exists in.
Follow-up to #772.

Use the availability zone that the subnet exists in

---

projects/goharbor/harbor/Makefile

Remove extraneous white space

---

docs/development/building-locally.md
docs/development/docker-auth.md

I've written this doc after having lots of problems authenticating to
various registries with various tools to do builds or other tasks that
involve interacting with Docker or OCI registries. I hope it's useful.
Suggestions welcome.
PS- is this the best place for this information to live?

Docs: docker registry login

---

build/lib/validate_artifacts.sh

I also took the opportunity to apply some fixes suggested by
shellcheck, as well as some minor indentation adjustments for
consistency.

Use consistent sorting between macOS/Linux

---

projects/aws/eks-a-admin-image/common.pkr.hcl
projects/aws/eks-a-admin-image/eks-a-admin-ci.pkr.hcl

fix presubmit packer validation

---

Common.mk

The create-ecr-repos Makefile target is extended to create the repos
of helm charts as well. In many cases the helm chart will end up in
one of the repos that's already created for a container image, but in
other cases, they're different repos, and this code will handle that
situation.

Create helm chart repos

---

EKSD_LATEST_RELEASES

Updates eks-d release

---

EKSD_LATEST_RELEASES

Bumped dev release number for 1.23

---

projects/tinkerbell/helm-chart/.helmignore
projects/tinkerbell/helm-chart/Chart.yaml
projects/tinkerbell/helm-chart/templates/boots-deployment.yaml
projects/tinkerbell/helm-chart/templates/boots-role.yaml
projects/tinkerbell/helm-chart/templates/boots-rolebinding.yaml
projects/tinkerbell/helm-chart/templates/boots-service-account.yaml
projects/tinkerbell/helm-chart/templates/hardware-crd.yaml
projects/tinkerbell/helm-chart/templates/hegel-deployment.yaml
projects/tinkerbell/helm-chart/templates/hegel-role.yaml
projects/tinkerbell/helm-chart/templates/hegel-rolebinding.yaml
projects/tinkerbell/helm-chart/templates/hegel-service-account.yaml
projects/tinkerbell/helm-chart/templates/namespace.yaml
projects/tinkerbell/helm-chart/templates/template-crd.yaml
projects/tinkerbell/helm-chart/templates/tink-controller-cluster-role-binding.yaml
projects/tinkerbell/helm-chart/templates/tink-controller-cluster-role.yaml
projects/tinkerbell/helm-chart/templates/tink-controller-deployment.yaml
projects/tinkerbell/helm-chart/templates/tink-controller-service-account.yaml
projects/tinkerbell/helm-chart/templates/tink-leader-election-role.yaml
projects/tinkerbell/helm-chart/templates/tink-leader-election-rolebinding.yaml
projects/tinkerbell/helm-chart/templates/tink-server-deployment.yaml
projects/tinkerbell/helm-chart/templates/tink-server-role.yaml
projects/tinkerbell/helm-chart/templates/tink-server-rolebinding.yaml
projects/tinkerbell/helm-chart/templates/tink-server-service-account.yaml
projects/tinkerbell/helm-chart/templates/workflow-crd.yaml
projects/tinkerbell/helm-chart/values.yaml

This PR only adds all the files needed for tinkerbell helm chart.
There will be a separate PR to actually build and publish these charts

Helm chart to install tinkerbell

---

build/lib/common.sh
build/lib/install_go_versions.sh
projects/kubernetes-sigs/cluster-api/Makefile
projects/kubernetes-sigs/kind/Makefile
projects/tinkerbell/hook/Makefile
projects/tinkerbell/hub/Makefile

Updates go-licenses and silences some new noisy messages

---

projects/goharbor/harbor/Help.mk
projects/goharbor/harbor/Makefile
projects/goharbor/harbor/docker/linux/harbor-trivy/Dockerfile

Add harbor-trivy

---

build/lib/common.sh
build/lib/install_go_versions.sh
projects/kubernetes-sigs/cluster-api/Makefile
projects/kubernetes-sigs/kind/Makefile
projects/tinkerbell/hook/Makefile
projects/tinkerbell/hub/Makefile

Backport updates to support new go-licenses

Updates go-licenses and silences some new noisy messages (#871)

---

projects/goharbor/harbor/Makefile

fix where trivy image is pushed to

---

projects/kubernetes-sigs/image-builder/buildspecs/build-1-23-rhel-ova.yml
projects/kubernetes-sigs/image-builder/buildspecs/build-1-23-rhel-raw.yml

The lack of these files has been causing build pipeline failures (see Slack
channel for details).

Adds RHEL v1-23 build specs

---

projects/goharbor/harbor/helm/requires-config.yaml

Add configuration values for Harbor

Helm add Harbor requires configs

---

projects/goharbor/harbor/helm/patches/0001-add-digest-and-namespace-support.patch
projects/goharbor/harbor/helm/sedfile.template

update harbor helm chart

---

projects/goharbor/harbor/docker/linux/harbor-trivy/Dockerfile

fix permission issue

---

projects/aws/eks-anywhere-packages/Makefile

remove kube-rbac-proxy from helm list for packages

---

projects/tinkerbell/hub/CHECKSUMS
projects/tinkerbell/hub/patches/0001-Write-DHCP-offer-to-static-Netplan-file.patch

This create a workflow action to write a static netplan from a DHCP host reservation from Boots.

Patch writefile workflow template:

---

build/lib/common.sh
build/lib/install_go_versions.sh

add go1.18

---

Makefile
build/lib/readme_check.sh
projects/aws-containers/hello-eks-anywhere/README.md
projects/aws/eks-anywhere-packages/README.md
projects/cilium/cilium/README.md
projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md
projects/kubernetes-sigs/cluster-api/README.md
projects/redis/redis/README.md
projects/tinkerbell/boots/README.md
projects/tinkerbell/hegel/README.md
projects/tinkerbell/hook/README.md
projects/tinkerbell/pbnj/README.md
projects/tinkerbell/rufio/README.md
projects/tinkerbell/tink/README.md

Maybe there is something like this I don't know about and this could be expanded, but this is a start:
```
% ./build/lib/readme_check.sh; echo $?
Did not find version projects/aws/cluster-api-provider-aws-snow/README.md
Did not find version projects/aws/eks-anywhere-build-tooling/README.md
Missing file projects/aws/eks-anywhere/README.md
Missing file projects/tinkerbell/tinkerbell-chart/README.md
0
```

Add readme check script

---

projects/aquasecurity/trivy/ATTRIBUTION.txt
projects/aquasecurity/trivy/CHECKSUMS
projects/aquasecurity/trivy/patches/0001-security-patch.patch

Security patch for Trivy

---

projects/goharbor/harbor/helm/requires-config.yaml

This is needed to satisfy marshaling values to current struct of configurations.

Changing harbor values to strings

---

EKSD_LATEST_RELEASES

Bumps to latest ekd-s releases

---

projects/goharbor/harbor/docker/linux/harbor-trivy/Dockerfile

add packages to support air-gapped use case of harbor-trivy

---

EKSD_LATEST_RELEASES

closes https://github.com/aws/eks-distro/issues/1090
~HOLD! Do not merge until releases are out!!!~ EKS-D releases are out. This can be merged whenever
---

Updated EKS-D versions for 1.19 - 1.23

---

projects/kubernetes-sigs/image-builder/build/get_bottlerocket_artifacts.sh

Provide absolute path to Tuftool executable

---

projects/goharbor/harbor/helm/requires-config.yaml

Add trivy configs to the list

---

projects/aws-containers/hello-eks-anywhere/helm/schema.json

Currently the json schema doesn't validate when a user adds an unknown configuration. This fixes that issue.

schema should validate any extra configurations not available to use

---

projects/aws/eks-anywhere/docker/linux/Dockerfile

Add nmap and iputils installation to Docker file

Add nmap and iputils installations to Docker file

---

build/lib/helm_require.sh

Add gzipped, base64 encoded json schema to requires.yaml file.

Add json schema to requires.yaml file

---

projects/kubernetes/cloud-provider-aws/.gitignore
projects/kubernetes/cloud-provider-aws/Makefile

I didn't detect any problem from this, but this is more correct

Fix cloud-provider-aws extra flags

---

projects/emissary-ingress/emissary/helm/schema.json

Adding emissary-schema

---

projects/kubernetes-sigs/image-builder/Makefile

Makefile changes for local image-builder cli

---

projects/goharbor/harbor/helm/schema.json

adding harbor-schema

---

EKSD_LATEST_RELEASES

closes https://github.com/aws/eks-distro/issues/1150
Base image updates. THIS IS THE LAST 1.19 RELEASE!
----

Updated EKS-D versions for 1.19, 1.20, and 1.21

---

build/lib/helm_require.sh

Fixing schema base64 script

---

docs/development/update-helm-charts.md

*Issue #, if available:* N/A
*Description of changes:* Add docs for updating helm charts

Add docs for updating helm charts

---

projects/metallb/metallb/helm/patches/0001-Use-CRD-format-from-v0.13.x-and-convert-to-configmap.patch
projects/metallb/metallb/helm/schema.json

Mimic v0.13.x metallb configuration where CRDs are used for configuration. For now, convert to a configmap until 

MetalLB patches for GA

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/builder.go

Support kube channel 1-23 on image-builder cli

---

EKSD_LATEST_RELEASES

Changed to use EKS-D 1.23-4

---

projects/goharbor/harbor/helm/patches/0002-Adding-imagePullSecret-and-default-Namespace.patch
projects/metallb/metallb/helm/patches/0002-Adding-imagePullSecrets-and-extracting-default-names.patch

Patch to both harbor and metallb to populate imagePullSecret with data as well as defaultNamespace to the Helm Values. The default for metallb is metallb-system to match upstream and harbor for harbor.

Metallb and Harbor imagePullSecret and defaultNamespace

---

projects/aws/eks-anywhere-packages/ECRTOKENREFRESHER_ATTRIBUTION.txt

*Issue #, if available:* N/A
*Description of changes:* Add package attribution

Add package attribution

---

projects/goharbor/harbor/helm/schema.json

Update required list

---

projects/emissary-ingress/emissary/helm/patches/0001-helm-changes.patch

Works without and with the `defaultNamespace` field in the package config.
Without 
With

Emissary namespace patch

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/builder.go
projects/aws/image-builder/builder/types.go
projects/aws/image-builder/builder/utils.go
projects/aws/image-builder/cmd/build.go
projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh

Minor fixes for image-builder.

Typos and minor fixes for image-builder

---

projects/aws-containers/hello-eks-anywhere/helm/patches/0001-Adding-namespace-and-imagePullSecret-support.patch

Adding ImagePullSecrets and default namespace to hello-eksa

Adding namespace and imagePullSecret support to hello-eksa

---

projects/emissary-ingress/emissary/helm/patches/0002-imagepullsecret.patch

Imagepullsecret patch

---

projects/kubernetes-sigs/image-builder/Makefile
release/staging-build.yml

Split bottlerocket CI builds jobs from ubuntu

---

projects/aws/eks-anywhere-packages/Makefile
release/staging-build.yml

These are no longer needed as prerequisites.

Remove dependencies for EKS-A package-controller

---

projects/emissary-ingress/emissary/helm/patches/0003-apiext-move.patch

Moves the namespace into the templates section so it works on deletes > re-installs.

emissary patch for namespace

---

Common.mk
build/lib/helm_push.sh

fix for helm push a 2nd tag

---

projects/aws/image-builder/README.md

Adding readme for image-builder

Add readme for image-builder

---

Common.mk
build/lib/helm_push.sh

fix for helm push script

---

Common.mk
build/lib/helm_push.sh

fix for semvar2 helm req

---

Common.mk
build/lib/helm_push.sh

fix for helm/push for harbor

---

projects/aws/image-builder/.gitignore
projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/builder.go
projects/kubernetes-sigs/image-builder/build/build_image.sh
projects/kubernetes-sigs/image-builder/build/build_raw_image.sh

1. Set the remote repo directory path properly
2. Do not clean up repo when running builds on CI

Fix raw ubuntu builds - Set directory path properly

---

projects/kubernetes-sigs/image-builder/Makefile

Run bottlerocket targets if the version exists in BR releases

---

projects/aws-observability/aws-otel-collector/helm/schema.json

*Issue #, if available:* N/A
*Description of changes:* Add ADOT helm chart json schema

Add ADOT helm chart json schema

---

projects/emissary-ingress/emissary/helm/schema.json

This prevents installing emissary.

Emissary has no required configuration

---

EKSD_LATEST_RELEASES

Update EKS-D versions

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES

Update bottlerocket to v1.9.2

---

docs/development/update-helm-charts.md

Add notes about CRDs in packages

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/builder.go
projects/aws/image-builder/builder/utils.go
projects/aws/image-builder/builder/utils_test.go

Add 24 as a supported release branch

---

Common.mk
build/lib/helm_require.sh
projects/aws-observability/aws-otel-collector/Makefile

Business logic changes necessary to support building release-branched helm charts.
Required for merging https://github.com/aws/eks-anywhere-build-tooling/pull/1287.

Build business logic changes for release-branched helm support

---

projects/kubernetes/autoscaler/1-21/HELM_GIT_TAG
projects/kubernetes/autoscaler/1-21/helm/patches/0001-Configure-image-digest.patch
projects/kubernetes/autoscaler/1-21/helm/patches/0002-Set-clusterapi-as-default-cloud-provider.patch
projects/kubernetes/autoscaler/1-21/helm/patches/0003-Add-regcred-secret.patch
projects/kubernetes/autoscaler/1-21/helm/sedfile.template
projects/kubernetes/autoscaler/1-22/HELM_GIT_TAG
projects/kubernetes/autoscaler/1-22/helm/patches/0001-Configure-image-digest.patch
projects/kubernetes/autoscaler/1-22/helm/patches/0002-Set-clusterapi-as-default-cloud-provider.patch
projects/kubernetes/autoscaler/1-22/helm/patches/0003-Add-regcred-secret.patch
projects/kubernetes/autoscaler/1-22/helm/sedfile.template
projects/kubernetes/autoscaler/1-23/HELM_GIT_TAG
projects/kubernetes/autoscaler/1-23/helm/patches/0001-Configure-image-digest.patch
projects/kubernetes/autoscaler/1-23/helm/patches/0002-Set-clusterapi-as-default-cloud-provider.patch
projects/kubernetes/autoscaler/1-23/helm/patches/0003-Add-regcred-secret.patch
projects/kubernetes/autoscaler/1-23/helm/sedfile.template
projects/kubernetes/autoscaler/1-24/HELM_GIT_TAG
projects/kubernetes/autoscaler/1-24/helm/patches/0001-Configure-image-digest.patch
projects/kubernetes/autoscaler/1-24/helm/patches/0002-Set-clusterapi-as-default-cloud-provider.patch
projects/kubernetes/autoscaler/1-24/helm/patches/0003-Add-regcred-secret.patch
projects/kubernetes/autoscaler/1-24/helm/sedfile.template
projects/kubernetes/autoscaler/Makefile

Ticket: https://github.com/aws/eks-anywhere/issues/3336, https://github.com/aws/eks-anywhere/issues/3268
First pass at creating a helm chart for cluster autoscaler.
I've tested applying the generated helm chart to a cluster locally and it applies correctly as far as I can tell. I'll do more extensive testing once we publish

Autoscaler Helm Chart

---

projects/kubernetes-sigs/image-builder/build/build_image.sh

Support uniform osFamily name "Redhat" instead of "Rhel"

---

projects/kubernetes/autoscaler/1-21/helm/schema.json
projects/kubernetes/autoscaler/1-22/helm/schema.json
projects/kubernetes/autoscaler/1-23/helm/schema.json
projects/kubernetes/autoscaler/1-24/helm/schema.json

Adding schema to publish helm chart as part of packages bundle.

Cluster Autoscaler Packages schema.json

---

projects/tinkerbell/tinkerbell-chart/helm/sedfile.template

fixup! Add flag to deploy kubevip in tinkerbell-chart

---

docs/development/packages/update-helm-charts.md

*Description of changes:* Move package specific docs under `packages` directory.

Move package helm-chart doc

---

projects/kubernetes-sigs/image-builder/build/build_image.sh

Update RHEL base image to 8.4

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/builder.go

Image builder change rhel target to call rhel-8

---

build/lib/helm_push.sh

The helm install from shasum does not work

Remove helm install from shasum

---

build/lib/install_go_versions.sh

bugfix: typo in the installation destination of go-licenses

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/builder.go
projects/aws/image-builder/builder/types.go
projects/aws/image-builder/cmd/build.go
projects/kubernetes-sigs/image-builder/build/build_image.sh

*Issue #, if available:* #1352 
Changes for building redhat image for baremetal workflows.

Image builder support for Redhat on baremetal

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/cmd/build.go

Fix iso validation for ubuntu builds

---

projects/kubernetes-sigs/metrics-server/1-21/helm/schema.json
projects/kubernetes-sigs/metrics-server/1-22/helm/schema.json
projects/kubernetes-sigs/metrics-server/1-23/helm/schema.json

Epic: https://github.com/aws/eks-anywhere/issues/3187
Adds schema.json to metrics-server helm chart.

Add metrics-server schema.json

---

build/lib/helm_push.sh

I feel like I have solved this exact problem for ecr-public, but I cannot find the answer and I just don't care that much. I'm probably the only one building to ecr public.

Fix helm_push for ecr public

---

projects/kubernetes-sigs/image-builder/build/build_raw_image.sh

Export required environment vars for raw redhat builds

---

projects/cert-manager/cert-manager/helm/patches/0003-Remove-namespace-from-chart.patch

- Remove namespace from helm chart

Remove namespace from chart

---

projects/cert-manager/cert-manager/helm/schema.json

- Include json schema for cert manager

Include cert manager schema

---

EKSD_LATEST_RELEASES

* First EKS-D 1.24 prod release. See https://github.com/aws/eks-distro/pull/1278

Added EKS-D 1.24-1 prod

---

build/lib/helm_push.sh
projects/kubernetes/autoscaler/1-21/helm/schema.json

Certain fields were marked as null that should have been strings in cluster autoscaler's schema.json.

Replace Cluster Autoscaler Null Schema Fields With Strings

---

EKSD_LATEST_RELEASES

* Updates EKS-D for 1.20 - 1.23, which includes Kubernetes patch version updates for 1.22 and 1.23

Update EKS-D for 1.20 - 1.23

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/builder.go
projects/aws/image-builder/builder/types.go
projects/aws/image-builder/builder/utils.go
projects/aws/image-builder/cmd/build.go
projects/kubernetes-sigs/image-builder/Makefile

Image builder support for building qcow2 images for Cloudstack provider. 

Image builder support for Cloudstack

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/build_image.sh
projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
projects/kubernetes-sigs/image-builder/buildspecs/cloudstack.yml

Support building cloudstack images for Redhat OS on CI.

Cloudstack - Redhat Image Builds on CI

---

projects/cert-manager/cert-manager/helm/patches/0004-Configure-cert-manager-namespace-and-imagePullSecret.patch

- Include cert manager default namespace
- Include imagePullSecrets reference

Include cert manager namespace and image Pull secret to chart

---

build/lib/helm_require.sh

Fix dependencies being generated with empty list when none are defined.

Fix dependencies being empty if undefined

---

projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh

Fix output image extension for metal builds

---

projects/metallb/metallb/helm/patches/0001-packages-patches.patch

Adds peers and makes the template simpler by omitting fields that would conflict instead of adding one by one.

Standardize templates for easier maintenance and add peer

---

EKSD_LATEST_RELEASES
projects/kubernetes/cloud-provider-vsphere/1-22/CHECKSUMS

* Base image updates for all versions and etcd updates for 1.20 and 1.21
* This will likely be the last or second to last 1.20 release

Updated EKS-D to latest for all versions

---

OWNERS

Remove gwesterfieldjr as they've left the project.

Remove gwesterfieldjr from OWNERs

---

projects/fluxcd/source-controller/CHECKSUMS
projects/fluxcd/source-controller/Makefile

Updates source-controller arm checksum and removes debug info

---

Makefile

Fix project path for clean and checksums

---

Makefile

Fixes attribution job by cleanup disk space

---

Makefile

Splits attribution periodic

---

docs/development/add-new-project.md

Update add-new-project for pkgs

---

build/lib/create_release_checksums.sh

Create checksums for cloudstack builds

---

projects/prometheus/prometheus/HELM_GIT_TAG
projects/prometheus/prometheus/Help.mk
projects/prometheus/prometheus/Makefile
projects/prometheus/prometheus/helm/patches/0001-chart-patch.diff
projects/prometheus/prometheus/helm/patches/0002-image-patch.diff
projects/prometheus/prometheus/helm/patches/0003-namespace-patch.diff
projects/prometheus/prometheus/helm/sedfile.template

Add Prometheus helm chart

---

projects/prometheus/prometheus/helm/patches/0004-values-patch.diff
projects/prometheus/prometheus/helm/patches/0005-json-schema-patch.diff
projects/prometheus/prometheus/helm/schema.json

Add json validation for prometheus helm chart

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/cmd/build.go

Fixing a nil pointer error that occured when running this binary.

Fix nil pointer error when parsing AMI config

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_CONTROL_CONTAINER_METADATA

https://github.com/aws/eks-anywhere/issues/4050

Add Bottlerocket control container image v0.6.3

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES

Update BR version to v1.11.0

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_ADMIN_CONTAINER_METADATA
projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES

This reverts commit 3b894ef1e2e1de29130d59fae617b6caa82dfcae.

Revert "Update BR version to v1.11.0 (#1601)"

---

projects/nutanix-cloud-native/cluster-api-provider-nutanix/build/create_manifests.sh

Update image repo and tag in Nutanix infrastructure components

Update image repo and tag in Nutanix infrastructure components

---

projects/aws-observability/aws-otel-collector/helm/sedfile.template

*Issue #, if available:* https://github.com/aws/eks-anywhere-packages/issues/636

Update adot helm chart appVersion

---

projects/prometheus/prometheus/helm/patches/0007-values-patch.diff
projects/prometheus/prometheus/helm/sedfile.template

*Issue #, if available:* https://github.com/aws/eks-anywhere-packages/issues/639

Update Prometheus helm charts

---

EKSD_LATEST_RELEASES

Added 1.25 dev 1 for EKS-D

---

EKSD_LATEST_RELEASES

Update EKSD to the latest release.

update EKS-D to latest releases

---

OWNERS

Add rcrozean(EKS-Distro team member) to OWNERS file.

Add rcrozean to OWNERS file

---

OWNERS

add zafs23 in OWNERS

---

Common.mk
build/lib/common.sh

Adds rerun to cgo docker build

---

build/lib/setup.sh

Bump up binfmt image to latest

Bump up binfmt image to latest

---

build/update-attribution-files/create_pr.sh

Same change that was done in https://github.com/aws/eks-distro-build-tooling/pull/757

Adds slash hold to add label instead of API labels arg

---

UPSTREAM_PROJECTS.yaml
projects/kubernetes-sigs/cluster-api-provider-cloudstack/ATTRIBUTION.txt
projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
projects/kubernetes-sigs/cluster-api-provider-cloudstack/Makefile
projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md

cherry pick CAPC bumps (with bug fix)
cherry pick CAPC bumps (with bug fix)

cherry pick CAPC bumps

---

UPSTREAM_PROJECTS.yaml
projects/kubernetes-sigs/cluster-api-provider-cloudstack/ATTRIBUTION.txt
projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
projects/kubernetes-sigs/cluster-api-provider-cloudstack/Makefile
projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md

This reverts commit a9a49d017a2f9ae7bc4c73c2349afb482c32ed11.

Revert "Bumps CAPC to new commit with bug fix (#1719)"

---

UPSTREAM_PROJECTS.yaml
projects/kubernetes-sigs/cluster-api-provider-cloudstack/ATTRIBUTION.txt
projects/kubernetes-sigs/cluster-api-provider-cloudstack/CHECKSUMS
projects/kubernetes-sigs/cluster-api-provider-cloudstack/GIT_TAG
projects/kubernetes-sigs/cluster-api-provider-cloudstack/Makefile
projects/kubernetes-sigs/cluster-api-provider-cloudstack/README.md

Reverts aws/eks-anywhere-build-tooling#1725

Revert "cherry pick CAPC bumps"

---

docs/development/packages/update-helm-charts.md

Update how to deal with CRDs for packages

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES
projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/get_bottlerocket_artifacts.sh
projects/kubernetes-sigs/image-builder/build/upload_bottlerocket_artifacts.sh
projects/kubernetes-sigs/image-builder/expected-artifacts/expected_artifacts_ami_bottlerocket
release/staging-build.yml

This PR adds the Bottlerocket AWS variants to build/release CI.

Add build logic for Bottlerocket AWS variants

---

projects/tinkerbell/tinkerbell-chart/helm/sedfile.template

Update missing tinkerbell chart version reference.

Update missing tinkerbell chart version reference.

---

projects/tinkerbell/hub/CHECKSUMS
projects/tinkerbell/hub/patches/0007-Update-vlan-checking.patch

Hook already creates the vlan interface so we don't need to create it here.

update vlan interface logic

---

projects/tinkerbell/hub/CHECKSUMS
projects/tinkerbell/hub/patches/0008-Fix-netplan-vlan-file.patch

Fixes the netplan file creation when using tagged vlan.

Fix netplan VLAN file creation

---

EKSD_LATEST_RELEASES

Bump EKSD releases

---

projects/aws-observability/aws-otel-collector/helm/schema.json

*Issue #, if available:* https://github.com/aws/eks-anywhere-packages/issues/786

Update ADOT json validation schema

---

projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh

Tagging EC2 instances and key-pairs with the job ID of the CI build that created them. This makes it easy to filter and delete them periodically.

Tag EC2 instances and key-pairs with CI job ID

---

EKSD_LATEST_RELEASES

Bumps to latest eks-d releases

---

EKSD_LATEST_RELEASES

bump eks-d releases

---

projects/tinkerbell/tinkerbell-chart/Makefile
projects/tinkerbell/tinkerbell-chart/scripts/verify.sh

This will verify the `tinkerbell-chart` versions are updated when changes are made to `tinkerbell-chart` and that the chart versions match in `GIT_TAG`, `Chart.yaml` and `sedfile.template`

Add verify script to verify the tinkerbell chart

---

EKSD_LATEST_RELEASES

Released twice this week due to announcement of ALAS2-2023-1957, hence the two version changes.

Update to newest release of eksd

---

EKSD_LATEST_RELEASES

Manually cherrypick #1876 to release-0.14 due to merge conflicts

Manual cherrypick update of eksd (#1876)

---

Common.mk
Makefile
build/lib/update_go_versions.sh
build/update-attribution-files/make_attribution.sh
projects/fluxcd/source-controller/Makefile
projects/kubernetes-sigs/image-builder/Makefile

backport of https://github.com/aws/eks-anywhere-build-tooling/pull/1886

Migrate space cleanup from eks-d

---

Common.mk

Adds retry around kustomize install

---

Common.mk
build/lib/common.sh
build/lib/go_mod_download.sh
build/lib/simple_create_binaries.sh
build/lib/simple_create_tarballs.sh
build/update-attribution-files/create_pr.sh

Adds logging similar to what was added to eks-d [here](https://github.com/aws/eks-distro/pull/1751)

Adds makefile logging from eks-d around key targets

---

projects/fluxcd/source-controller/Makefile

Removes source-controller periodic workaround

---

projects/aws/eks-anywhere-packages/Makefile

Reorder charts and fix dependency

Fix dependencies on new charts

---

projects/aws/eks-anywhere-packages/helm/schema.json

Add jsonschema for eksa-packages package.

add jsonschema for eksa-packages

---

Common.mk
Makefile
build/lib/common.sh
build/lib/fetch_binaries.sh
build/update-attribution-files/create_pr.sh
build/update-attribution-files/make_attribution.sh

Add more logging in common.mk, cleanup confusing log message in prow and improve cleanup to decrease build times.

Adds more logging and cleanup logs in prow

---

build/update-attribution-files/create_pr.sh

Fixes github login for prow periodic jobs

---

EKSD_LATEST_RELEASES

Update EKSD_LATEST_RELEASES (#1969)

---

Common.mk
Makefile
build/lib/generate_staging_buildspec.sh
build/lib/install_go_versions.sh
build/update-attribution-files/create_pr.sh
buildspecs/checksums-buildspec.yml
buildspecs/checksums-pr-buildspec.yml
projects/fluxcd/source-controller/Makefile
release/checksums-build.yml

Adds seperate build to checksums batch for pr

---

Common.mk
Makefile
build/lib/generate_staging_buildspec.sh
build/update-attribution-files/create_pr.sh
buildspecs/checksums-buildspec.yml
buildspecs/checksums-pr-buildspec.yml
projects/fluxcd/source-controller/Makefile
release/checksums-build.yml

Adds seperate build to checksums batch for pr (#1984)

---

EKSD_LATEST_RELEASES

Reverts aws/eks-anywhere-build-tooling#1977

Revert "Update EKSD_LATEST_RELEASES (#1969)"

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/upload_bottlerocket_artifacts.sh

Restores br artifacts upload flow for image-builder

---

EKSD_LATEST_RELEASES

Not cherry picking this to 0.14

Latest eks-d releases

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES

Add BR 1.26

---

projects/torvalds/linux/Makefile
release/checksums-build.yml
release/staging-build.yml

Changes bootconfig build to use linux/amd vs arm codebuild instances

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES

Upgrade Bottlerocket to 1.13.1

---

EKSD_LATEST_RELEASES

Updated EKS-D for all versions

---

projects/containerd/containerd/Makefile
projects/opencontainers/runc/Makefile

Do not delete on upload for runc/containerd

---

Makefile
build/lib/generate_staging_buildspec.sh
projects/containerd/containerd/Makefile
projects/containerd/containerd/build/create_tarballs.sh
release/staging-build.yml

includes runc in containerd tarball to match upstream

---

EKSD_LATEST_RELEASES

* changes for the release on 04/13/2023

Updated to the latest versions for EKS-D

---

projects/containerd/containerd/build/create_tarballs.sh

Add containerd.service to containerd tarball

---

projects/containerd/containerd/build/create_tarballs.sh

Fixes containerd tarball folder structure to match upstream

---

EKSD_LATEST_RELEASES

* Updated EKS-D for 1.22 - 1.26

Updated EKS-D

---

EKSD_LATEST_RELEASES

Updated EKS-D (#2129)

---

projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh

Handle released image-builder building from main

---

EKSD_LATEST_RELEASES

Updated EKS-D for latest releases

Updated EKS-D to latest releases

---

projects/aws/eks-anywhere-packages/README.md
projects/aws/etcdadm-bootstrap-provider/README.md
projects/cilium/cilium/README.md
projects/kubernetes-sigs/cluster-api/README.md
projects/kubernetes-sigs/etcdadm/README.md

Ran `build/lib/readme_check.sh` to update outdated badge versions.

Update badge versions for projects

---

projects/aws/eks-anywhere-packages/README.md
projects/aws/etcdadm-bootstrap-provider/README.md
projects/brancz/kube-rbac-proxy/README.md
projects/cilium/cilium/README.md
projects/fluxcd/flux2/README.md
projects/fluxcd/kustomize-controller/README.md
projects/fluxcd/notification-controller/README.md
projects/fluxcd/source-controller/README.md
projects/helm/helm/README.md
projects/kubernetes-sigs/cri-tools/README.md
projects/kubernetes-sigs/etcdadm/README.md
projects/kubernetes-sigs/image-builder/README.md
projects/kubernetes/cloud-provider-aws/README.md
projects/rancher/local-path-provisioner/README.md
projects/vmware/govmomi/README.md

Ran `build/lib/readme_check.sh` to update outdated badge versions.

Update badges for projects

---

build/lib/fetch_binaries.sh

Fix an issue brought by https://github.com/aws/eks-anywhere-build-tooling/pull/2236

Update fetch_binaries for eksd

---

projects/aws/eks-anywhere-packages/Makefile

Update eks-anywhere-packages IMAGE_TAG and HELM_TAG to include release branch

---

build/lib/common.sh
build/lib/install_go_versions.sh

cleans up go version for go-licenses flow

---

projects/kubernetes-sigs/vsphere-csi-driver/Makefile
projects/tinkerbell/hub/Makefile
release/checksums-build.yml
release/staging-build.yml

removes projects we arent building from buildspecs

---

EKSD_LATEST_RELEASES

bumps eks-d releases

---

.github/workflows/baseimage-pr-notifier.yaml

Adds a GH action to notify us when a new base image PR is opened against the repo

Add notifier action

---

projects/kubernetes-sigs/image-builder/Makefile

fixes ami image build upload

---

Common.mk
release/staging-build.yml

Fixing staging build yml

---

build/lib/generate_staging_buildspec.sh
release/staging-build.yml

fixes staging buildspec generation to account of release branched deps

---

EKSD_LATEST_RELEASES

All versions Include a base image update

Updated to latest EKS-D versions

---

build/lib/eksa_releases.sh

Suppress shell opts restoration output

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/utils.go

Remove bad quotes

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/utils.go

Allow users to force checking out main branch

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/build_image.sh

adds support to build ubuntu ova using efi firmware

---

Makefile

Add space in Makefile

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/builder.go
projects/aws/image-builder/builder/constants.go
projects/aws/image-builder/builder/files.go
projects/aws/image-builder/builder/types.go
projects/aws/image-builder/cmd/build.go
projects/aws/image-builder/cmd/build_test.go

Fixing issues in image-builder builds with additional files as input.

Refactor additional files mount logic

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/builder/builder.go
projects/aws/image-builder/builder/constants.go
projects/aws/image-builder/builder/files.go
projects/aws/image-builder/builder/types.go
projects/aws/image-builder/cmd/build.go
projects/aws/image-builder/cmd/build_test.go

Backporting #2350 and #2352 to release-0.17.

Backport ami build fixes

---

EKSD_LATEST_RELEASES

Bump eks d releases for EKS A

---

projects/tinkerbell/hub/CHECKSUMS
projects/tinkerbell/hub/patches/0011-Ensure-content-is-specified-before-writing-file.patch

Patch writefile to error when no content specified

---

EKSD_LATEST_RELEASES

I'll merge this tonight to limit the vmware test image churn.
/hold

Latest eks-d versions

---

projects/kubernetes-sigs/image-builder/build/build_image.sh
projects/kubernetes-sigs/image-builder/buildspecs/ami.yml
projects/kubernetes-sigs/image-builder/buildspecs/cloudstack.yml
projects/kubernetes-sigs/image-builder/buildspecs/ova.yml
projects/kubernetes-sigs/image-builder/buildspecs/raw.yml

fixes raw/cloudstack builds

---

projects/goharbor/harbor/Makefile
projects/goharbor/harbor/buildspecs/batch-build.yml

splits harbor into batch build for images

---

OWNERS

Add tatlat to OWNERS

---

build/lib/eksa_releases.sh
projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh

Image builds parse the (dev) bundle manifest to retrieve tarball URLs for binaries such as `crictl`, `etcdadm` and `containerd`. The bundle is divided into several sections, one for each EKS-D release branch (Kubernetes version) and the scripts pass in the release branch to get the URL from that section. When building images for a new release branch for the first time, the section for that release branch would not have been added to the bundle yet, so the URLs will be returned as empty strings by the `yq` query. So we fall back to the previous release branch section to get the URLs. These artifacts for these projects are common across Kubernetes versions so we can use the artifact URL from any other release branch.
By submitting this pull request, I confirm that you can use, modify, copy, …

Fall back to previous release branch section for common binaries

---

projects/kubernetes-sigs/kind/build/build-kind-node-image.sh

fixes kubelet version check in kind node build

---

projects/goharbor/harbor/docker/linux/harbor-portal/Dockerfile

Can't access harbor api webpage
Fix harbor portal image.

Fix harbor api webpage access issue

---

projects/aws/eks-a-admin-image/build/export-ami-to-s3.sh

Fix regex check for SSM managed instances

---

OWNERS

add cxbrowne1207 to owners

---

EKSD_LATEST_RELEASES

Update eks-d release to latest

---

projects/tinkerbell/tinkerbell-chart/README.md

Add a readme for the tinkerbell stack chart.

---

projects/cilium/cilium/build/create_manifests.sh
projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/ansible.cfg

- https://github.com/ansible/awx/issues/14495#issuecomment-1752708302
- https://github.com/helm/helm/issues/12423

fixes cilium and image-builder builds

---

Common.mk
build/lib/common.sh
build/lib/create_release_checksums.sh
build/lib/generate_help_body.sh
build/lib/helm_pull.sh
build/lib/helm_push.sh
build/lib/helm_replace.sh
build/lib/readme_check.sh
build/lib/update_checksums.sh
build/lib/validate_artifacts.sh
build/lib/version.sh

improves mac gnu variant detection

---

projects/goharbor/harbor/docker/linux/harbor-registry/Dockerfile
projects/goharbor/harbor/docker/linux/harbor-registryctl/Dockerfile
projects/goharbor/harbor/docker/linux/harbor-trivy/Dockerfile

The dependencies harbor is pulling in are not release branched nor is the harbor build. Currently this just resolves to empty string.

removes release_branch from harbor docker files

---

projects/kubernetes-sigs/image-builder/buildspecs/ami.yml
projects/kubernetes-sigs/image-builder/buildspecs/ova.yml

fixes image-builder home directory permissions

---

projects/kubernetes-sigs/image-builder/Makefile

remove workaround for old ansible version

---

projects/tinkerbell/hub/Makefile

We started building bootconfig for arm so we should be able to build the arm versions of these images.

builds arm images for tink actions

---

Common.mk
build/lib/buildkit.sh

Recently I added a prereq for buildctl when building images. I had, incorrectly, assumed everyone was building images via the host since when using `make images` and pushing to some remote registry auth is most likely involved. @jacobweinstock informed me that he actually used to build images via the builder-base, the `make run-in-docker` targets, to avoid setting up buildctl/buildkit (he obviously did not read my building-locally doc....).  This new prereq broke his workflow since it no longer allows to build images in the builder base since the prereq is checking for the host to be setup and fails otherwise.
As a short history lesson, we have always used buildctl to build out images since from the early days of eks-d we were building …

adds support for buildx if buildctl is missing

---

projects/tinkerbell/hub/Makefile
release/staging-build.yml

fix depend-on for hub on bootconfig

---

projects/aws/image-builder/builder/builder.go
projects/aws/image-builder/builder/constants.go

This PR fixes Nutanix build issues introduced after we moved around some cloning/repo prep operations.

Fix config file path for Nutanix image builds

---

build/lib/run_target_docker.sh

fixes builder base image url

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/build/build_image_on_metal.sh
projects/kubernetes-sigs/image-builder/build/prow_build.sh

uses build acct instead of prow acct for metal testing

---

projects/emissary-ingress/emissary/.gitignore
projects/emissary-ingress/emissary/Makefile
projects/emissary-ingress/emissary/buildspecs/batch-build.yml

fixes emissary buildspec

---

projects/goharbor/harbor/helm/sedfile.template

fixup! Bump harbor version (#2670)

---

projects/kubernetes-sigs/metrics-server/README.md

Includes a ref to EKS-D ECR public gallery.

Add Ref to EKS-D Metrics Server ECR Gallery

---

projects/kubernetes-sigs/image-builder/build/build_image.sh

We had a failure in codebuild which may be the retry code, but I actually think its ansible just stalling. This refactors this code a bit and also adds a timeout to ansible. 1h was picked because the individual provisioners have a 30 min time out.

refactor ansible retry and timeout after 1h

---

projects/kubernetes-sigs/image-builder/build/build_image.sh

fix stray quote in build-image

---

projects/kubernetes-sigs/image-builder/build/build_image.sh

properly quote stuff

---

projects/aws/upgrader/upgrade.sh

Coredns config map needs to be deleted from all the CP nodes (not just the first CP) before running kubeadm upgrade as coredns tag mismatch can lead to kubeadm upgrade failure. Before upgrading each of the CP backup coredns config and restore it once the upgrade is successful.

Fix upgrade script to delete coredns config for all the CPs 

---

EKSD_LATEST_RELEASES

updates to latest eksd (#2706)

---

OWNERS

add rayzhng to owners

---

tools/version-tracker/pkg/constants/constants.go
tools/version-tracker/pkg/git/git.go

Configure author for Git commit step, and add release tarball config for `containerd` and `runc` projects.

Configure author for Git commit step

---

buildspecs/upgrade-buildspec.yml
tools/version-tracker/Makefile

Run upgrade tool in verbose mode in CodeBuild so we can debug failures.

Run upgrade CLI in verbose mode in CodeBuild

---

build/lib/setup.sh
config/policy.json

fixes skopeo for helm chart tagging

---

EKSD_LATEST_RELEASES

updates to latest eksd

---

OWNERS

Add rahulbabu95 as owner for this repo.

Add me as owner

---

EKSD_LATEST_RELEASES

[release-0.18] bump eksd

---

EKSD_LATEST_RELEASES

Bump eks-d to latest versions

---

projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/patches/0001-Add-goss-validations-for-EKS-D-artifacts.patch
projects/kubernetes-sigs/image-builder/patches/0002-Output-vsphere-builds-to-content-library-instead-of-.patch
projects/kubernetes-sigs/image-builder/patches/0003-Create-etc-pki-tls-certs-dir-as-part-of-image-builds.patch
projects/kubernetes-sigs/image-builder/patches/0004-Add-etcdadm-and-etcd.tar.gz-to-image-for-unstacked-e.patch
projects/kubernetes-sigs/image-builder/patches/0005-Additional-EKS-A-specific-goss-validations.patch
projects/kubernetes-sigs/image-builder/patches/0006-Tweak-Product-info-in-OVF.patch
projects/kubernetes-sigs/image-builder/patches/0007-Support-crictl-validation-from-input-checksum.patch
projects/kubernetes-sigs/image-builder/patches/0008-Exclude-kernel-and-cloud-init-from-yum-updates.patch
projects/kubernetes-sigs/image-builder/patches/0009-Patch-cloud-init-systemd-unit-to-wait-for-network-ma.patch
projects/kubernetes-sigs/image-builder/patches/0010-Add-instance-metadata-options-to-Packer-config.patch
projects/kubernetes-sigs/image-builder/patches/0011-Rename-Snow-node-image-to-reflect-appropriate-CAPI-p.patch
projects/kubernetes-sigs/image-builder/patches/0012-Add-EKS-A-specific-inline-Goss-vars-to-all-supported.patch
projects/kubernetes-sigs/image-builder/patches/0013-Use-tar.gz-extension-for-CNI-plugins-tarball.patch
projects/kubernetes-sigs/image-builder/patches/0014-uses-latest-ubuntu-22.04-iso.patch
projects/kubernetes-sigs/image-builder/patches/0015-adds-support-for-raw-ubuntu-22.04-builds.patch
projects/kubernetes-sigs/image-builder/patches/0016-sets-OS_VERSION-for-goss-validation-on-raw-image-bui.patch
projects/kubernetes-sigs/image-builder/patches/0017-Disable-UDP-offload-service-for-Redhat-and-Ubuntu.patch
projects/kubernetes-sigs/image-builder/patches/0018-Add-dracut-cmd-to-generate-initramfs-with-all-driver.patch
projects/kubernetes-sigs/image-builder/patches/0019-Add-proxy-register-with-satellite-and-pull-packages-.patch
projects/kubernetes-sigs/image-builder/patches/0020-Ubuntu-switch-to-offline-install-when-mirrors-are-un.patch
projects/kubernetes-sigs/image-builder/patches/0021-Default-Flatcar-version-to-avoid-pulling-from-intern.patch
projects/kubernetes-sigs/image-builder/patches/0022-TEMP-skip-python-3.9-check-if-ansible-already-instal.patch
projects/kubernetes-sigs/image-builder/patches/0023-Nutanix-RHEL-support-for-AWS-image-builder.patch
projects/kubernetes-sigs/image-builder/patches/0024-Fix-redhat-9-cloud-init-feature-flags-bug.patch
projects/kubernetes-sigs/image-builder/patches/0025-Fix-ensure-iptables-present-for-rhel.patch
projects/kubernetes-sigs/image-builder/patches/0026-adds-retries-and-timeout-to-packer-image-builder.patch
projects/kubernetes-sigs/image-builder/patches/0027-Adds-support-for-cloudstack-rhel-9.patch

Add rhel9 support for cloudstack

---

projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh

While running `setup_packer_configs.sh` with Ubuntu OS, user might have `route` command not found issue while checking with `$(route |awk '/^default/{print $NF}')`. Consider not all OS variant comes with `route` command, it could be replaced with the `ip` instead, which is used in elsewhere in the same script.
Furthermore, PR #2219 was initially aim to support Ubuntu 22.04 ( see #2219 ), but it also unblock all the Ubuntu versions. If the script is aim to support all Ubuntu versions, it would better to have `ens5` supported.

Detect PACKER_ACTIVE_INTERFACE with "/proc/net/route" if possible

---

EKSD_LATEST_RELEASES

Bump EKS-D releases to latest

---

OWNERS

Remove raymond-zhang00 from OWNERS

---

projects/metallb/metallb/helm/patches/0001-packages-patches.patch

Remove FRR values from the metallb helm chart since it's not supported

Fix metallb helm chart

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES

Bump Bottlerocket release version to latest

---

projects/kubernetes-sigs/image-builder/buildspecs/ami.yml
projects/kubernetes-sigs/image-builder/buildspecs/cloudstack.yml
projects/kubernetes-sigs/image-builder/buildspecs/ova.yml
projects/kubernetes-sigs/image-builder/buildspecs/raw.yml

Ensure proper values are passed to release branch support check Make target.

Ensure proper values are passed to release branch support check

---

projects/aws/upgrader/upgrade.sh

Fix a small typo in the upgrader script

Fix upgrader script

---

tools/version-tracker/pkg/commands/display/display.go
tools/version-tracker/pkg/commands/listprojects/listprojects.go
tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/constants/constants.go
tools/version-tracker/pkg/git/git.go
tools/version-tracker/pkg/github/github.go
tools/version-tracker/pkg/util/file/file.go
tools/version-tracker/pkg/util/slices/slices.go

Fixes: #2082
Example PRs: 
https://github.com/abhay-krishna/eks-anywhere-build-tooling/pull/51 (only releases)
https://github.com/abhay-krishna/eks-anywhere-build-tooling/pull/52 (releases and host containers)

Automate Bottlerocket release version updates

---

EKSD_LATEST_RELEASES

Bump EKS-D to latest version

---

projects/kubernetes-sigs/image-builder/buildspecs/ova.yml

Update image-builder buildspec to use colo vsphere

Update image-builder buildspec to use colo vsphere

---

tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/git/git.go
tools/version-tracker/pkg/github/github.go

This PR fixes the condition for adding the failed patches warning comment on upgrade PRs.

Fix condition for patches warning comment on upgrade PRs

---

OWNERS

add sp1999 to OWNERS

---

tools/version-tracker/pkg/github/github.go

This PR adds logic to filter out pre-release tags in upgrader flow so that they are skipped from consideration.

Filter out pre-release tags in upgrader flow

---

projects/kubernetes-sigs/metrics-server/1-30/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch

Use prod metrics-server image instead of dev

---

tools/version-tracker/pkg/commands/upgrade/upgrade.go

Handle patches application for release-branched projects.

Handle patches application for release-branched projects

---

projects/kubernetes-sigs/image-builder/build/setup_packer_configs.sh

Add log showing packer http server ip change

---

projects/kubernetes-sigs/image-builder/build/build_image.sh

Add retry when there ssh connection timeout during image building

---

EKSD_LATEST_RELEASES

[release-0.19] Bump EKS Distro releases to latest (#3167)

---

projects/kubernetes-sigs/image-builder/Makefile

Update instance to t3.micro

---

projects/kubernetes-sigs/image-builder/build/validate_required_deps.sh
projects/kubernetes-sigs/image-builder/patches/0009-point-to-abhnvp-github.patch

Temporary change for nutanix image-builder test

---

EKSD_LATEST_RELEASES

This is a manual cherry-pick of #3269

[release-0.19] Bump EKS Distro releases to latest

---

UPSTREAM_PROJECTS.yaml
build/lib/generate_projects_list.sh

use supported release branches for upstream generation

---

projects/prometheus/prometheus/helm/patches/0001-Remove-prometheus-chart-dependencies.patch
projects/prometheus/prometheus/helm/patches/0002-Add-node-exporter-component.patch
projects/prometheus/prometheus/helm/patches/0003-Update-image-repo.patch
projects/prometheus/prometheus/helm/patches/0004-Add-namespace-to-charts.patch
projects/prometheus/prometheus/helm/patches/0005-Update-pod-update-strategy-due-to-configmap-changes.patch
projects/prometheus/prometheus/helm/patches/0006-Update-values.yaml-and-add-values.schema.json.patch

Fix helm chart namespace issue for prometheus package upgrade

Fix helm chart namespace issue for prometheus package upgrade

---

OWNERS

Add jhaanvi5 to OWNERS

---

projects/aws/eks-anywhere-packages/Help.mk
projects/aws/eks-anywhere-packages/Makefile
projects/aws/eks-anywhere-packages/docker/linux/credentialprovider/Dockerfile
release/staging-build.yml

Update ecr-credential-provider binary

---

build/lib/fetch_binaries.sh
projects/kubernetes-sigs/kind/Makefile
projects/kubernetes-sigs/kind/build/build-kind-node-image.sh

See https://github.com/aws/eks-anywhere-build-tooling/pull/3242 and https://github.com/aws/eks-distro/pull/3089
Lets merge https://github.com/aws/eks-anywhere-build-tooling/pull/3269 first

use kube-server.tgz directly for kind node image

---

tools/version-tracker/pkg/commands/upgrade/upgrade.go

Update the PR title with the release name for project bump PRs with a base branch other than main

Update project bumps PR title for release branches

---

projects/isc-projects/dhcp/expected_artifacts

Fix small typo in dhcp expected artifacts

Fix typo in dhcp expected artifacts

---

projects/aws/eks-a-admin-image/eks-a-admin-snow.pkr.hcl

Increase disk size of the snow admin machine

---

projects/prometheus/prometheus/ATTRIBUTION.txt

This reverts commit 930bb52b0faa6d8a9dcd1adea09b728a485f5960.
The PR is wrong, it contains a rate-limit error message.

Revert "[PR BOT] Update prometheus/prometheus/ATTRIBUTION.txt (#3576)"

---

projects/aws/upgrader/upgrade.sh

Add force flag to kubeadm upgrade command

---

projects/tinkerbell/hook/Makefile
projects/tinkerbell/hook/patches/0001-patches-build.sh-flow-for-linuxkit.patch
projects/tinkerbell/hook/patches/0002-builds-kernel-from-al2.patch

fixes hook in codebuild

---

projects/linuxkit/linuxkit/Makefile

fix dhcpd image component

---

projects/linuxkit/linuxkit/Makefile

fixes linuxkit artifacts upload

---

tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/constants/constants.go
tools/version-tracker/pkg/github/github.go

Allow upgrader to open pull requests even in case of failures.

Allow upgrader to open pull requests even in case of failures

---

projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
projects/kubernetes-sigs/image-builder/patches/0004-Ubuntu-22.04-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0005-RHEL-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0006-Nutanix-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0007-adds-retries-and-timeout-to-packer-image-builder.patch
projects/kubernetes-sigs/image-builder/patches/0008-Networking-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0009-RHEL-9-EFI-support-and-improvements.patch

[release-0.20] RHEL 9 EFI support and improvements

---

OWNERS

Add Shizhao to OWNERS

---

projects/aws/image-builder/Makefile

Fix typo in EKS-A latest version function name.

Fix typo in EKS-A latest version function name

---

Common.mk

This adds support for pulling image cache from additional ecr repos. In our case, this means well pull the cache in prow from the eksa build account, prow [jobs](https://github.com/aws/eks-anywhere-prow-jobs/pull/424).  This should improve the build times slightly, but for a couple of the builds. such as the hook-kernel build, this will greatly improve the time since it will be able to use the cache if nothing change in the code.
That build tho uses multiple build stages.  Our current inline-caching approach only suppports `mode=min` which means it will only keep the cache for layers that end up in the final image.  There is also a registry option where you can push this cache, and use mode=max to include all stages, to a separate …

add support to pull image cache from other repo

---

projects/aws/cluster-api-provider-aws-snow/Makefile

fixes snow image cache build

---

projects/tinkerbell/boots/CHECKSUMS

Update CHECKSUMS file for tinkerbell boots.

Update CHECKSUMS for tinkerbell boots

---

projects/tinkerbell/hook/Makefile

adds comment to hook build

---

tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/constants/constants.go

Backporting #3861 to release-0.20 branch

Update cert-manager manifest when bumping Git tag

---

projects/kube-vip/kube-vip/CHECKSUMS

Fix checksums for kube-vip/kube-vip.

Fix checksums for kube-vip/kube-vip

---

build/lib/setup.sh

If the binfmt-misc image is used to install the emulator corresponding to the host architecture itself, it throws an error.
```console
installing: amd64 cannot register "/usr/bin/qemu-x86_64" to /proc/sys/fs/binfmt_misc/register: write /proc/sys/fs/binfmt_misc/register: no such file or directory
```
```console
installing: arm64 cannot register "/usr/bin/qemu-aarch64" to /proc/sys/fs/binfmt_misc/register: write /proc/sys/fs/binfmt_misc/register: no such file or directory
```
So we are changing the script to not install the emulator for the host architecture.

Install emulator only for architecture not matching with host

---

build/lib/setup.sh

Fix `if` condition in setup script
/cherrypick release-0.21

Fix if condition in setup script

---

build/lib/setup.sh

Fix condition for current architecture in setup script

---

projects/kubernetes-sigs/image-builder/README.md

Fixing typos in README 🐛

---

OWNERS

[release-0.20] Add 2ez4szliu to OWNERS

---

Common.mk
build/lib/generate_staging_buildspec.sh
projects/kubernetes-sigs/kind/Makefile
projects/kubernetes-sigs/kind/build/node-image-build-args.sh
projects/kubernetes-sigs/kind/buildspecs/base-images.yml
projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
projects/kubernetes-sigs/kind/buildspecs/binaries.yml
projects/kubernetes-sigs/kind/buildspecs/node-images.yml
release/checksums-build.yml
release/staging-build.yml
tools/version-tracker/buildspecs/upgrade.yml

Cherry-picked from https://github.com/aws/eks-anywhere-build-tooling/pull/4133

[release-0.20] breaks kind batch build up even more

---

Common.mk
build/lib/generate_staging_buildspec.sh
projects/kubernetes-sigs/kind/Makefile
projects/kubernetes-sigs/kind/build/node-image-build-args.sh
projects/kubernetes-sigs/kind/buildspecs/base-images.yml
projects/kubernetes-sigs/kind/buildspecs/batch-build.yml
projects/kubernetes-sigs/kind/buildspecs/binaries.yml
projects/kubernetes-sigs/kind/buildspecs/node-images.yml
release/checksums-build.yml
release/staging-build.yml
tools/version-tracker/buildspecs/upgrade.yml

Backporting #4133 to release-0.21 branch.

breaks kind batch build up even more

---

Makefile
build/lib/generate_staging_buildspec.sh
buildspecs/upgrade-eks-distro-build-tooling-buildspec.yml
tools/version-tracker/buildspecs/upgrade.yml
tools/version-tracker/pkg/commands/display/display.go
tools/version-tracker/pkg/commands/listprojects/listprojects.go
tools/version-tracker/pkg/commands/upgrade/upgrade.go
tools/version-tracker/pkg/constants/constants.go

Backporting #4195 to release-0.21

Add EKS Distro base tag files to version-tracker automation

---

projects/kube-vip/kube-vip/ATTRIBUTION.txt
projects/kube-vip/kube-vip/CHECKSUMS

Update attribution file and checksums for kube-vip/kube-vip

Update attribution file and checksums for kube-vip/kube-vip

---

projects/aquasecurity/trivy/ATTRIBUTION.txt
projects/aquasecurity/trivy/CHECKSUMS
projects/aquasecurity/trivy/Makefile
projects/aquasecurity/trivy/patches/0002-Update-CSAF-module-dependency-from-csaf-poc-to-gocsa.patch

Migrate csaf-poc/csaf_distribution to gocsaf/csaf

---

EKSD_LATEST_RELEASES

Fix endOfSupport date for 1-32

---

projects/tinkerbell/hook/CHECKSUMS
projects/tinkerbell/hook/patches/0002-builds-kernel-from-al2.patch

Update hook kernel with missing modules

---

projects/aws/image-builder/builder/builder.go
projects/aws/image-builder/builder/constants.go
projects/aws/image-builder/builder/types.go
projects/aws/image-builder/cmd/build.go
projects/kubernetes-sigs/image-builder/patches/0014-Make-configurable-Nutanix-image-size.patch

Add Nutanix optional parameter to define image size

Add Nutanix optional parameter to define image size

---

OWNERS

Add rajeshvenkata to OWNERS

---

projects/kubernetes-sigs/metrics-server/1-32/HELM_GIT_TAG
projects/kubernetes-sigs/metrics-server/1-32/helm/patches/0001-Conform-helm-chart-to-packages-standards.patch
projects/kubernetes-sigs/metrics-server/1-32/helm/patches/0002-Remove-Addon-Resizer.patch
projects/kubernetes-sigs/metrics-server/1-32/helm/schema.json
projects/kubernetes-sigs/metrics-server/1-32/helm/sedfile.template
projects/kubernetes-sigs/metrics-server/README.md

Adding release branch 1-32 for metrics server

Add release branch 1-32 for metrics server

---

tools/version-tracker/pkg/constants/constants.go
tools/version-tracker/pkg/ecrpublic/ecrpublic.go

Fix ECR Public latest version retrieval.

Fix ECR Public latest version retrieval

---

tools/version-tracker/pkg/ecrpublic/ecrpublic.go
tools/version-tracker/pkg/github/github.go

More fixes to latest semver detection for release branches.

More fixes to latest semver detection for release branches

---

projects/kubernetes-sigs/image-builder/build/build_image.sh

Make Nutanix source image import names specific to image name.
We're also extending the local fileserver image hosting technique to Ubuntu as well so each source image gets hosted with a separate name and thus gets imported as a separate image. This should hopefully prevent errors like
```console
==> nutanix: Error creating virtual machine request: error while 
findImageByUUID, Error error while checking if image exists, your 
query returned more than one result with same Name/URI
```

Make Nutanix source image import names specific to image name

---

projects/emissary-ingress/emissary/helm/schema.json

- Updated schema.json for emissary helm chart

Updated schema.json for emissary helm chart

---

OWNERS

Add Amelia (peirulu) to OWNERS

Update OWNERS add Amelia

---

config/docker-ecr-config.json
config/policy.json

* Add EKS add-on registry to `policy.json` and credHelpers list

Add EKS add-on registry to policy.json and credHelpers list

---

OWNERS

Adds subbu vakati to owners

---

projects/kubernetes-sigs/image-builder/BOTTLEROCKET_RELEASES

https://github.com/aws/eks-anywhere-internal/issues/3288
Upstream releases - https://github.com/bottlerocket-os/bottlerocket/releases

Add BR release version for 1.33

---

projects/kubernetes-sigs/image-builder/patches/0005-Nutanix-improvements.patch

Cherry-pick of pull request https://github.com/aws/eks-anywhere-build-tooling/pull/4697

[release-0.22] Fix nutanix rhel 8 release 0.22

---

projects/tinkerbell/ipxedust/CHECKSUMS
projects/tinkerbell/ipxedust/Makefile
projects/tinkerbell/ipxedust/ipxe-config/boot.ipxe
projects/tinkerbell/ipxedust/ipxe-config/custom.h

Same as PR https://github.com/aws/eks-anywhere-build-tooling/pull/4711 from main. Had to add it manually because cherry pick failed due to conflicts in CHECKSUMS

Add retry mechanism and increase timeout for network link wait

---

build/lib/update_checksums.sh

https://github.com/aws/eks-anywhere-internal/issues/3582
Some of the project binaries are built on architecture specific machines including linuxkit, ipxedust. update_checksums script currently removes entries of the missing binaries from the checksums file. For instance codebuild job `aws-eks-anywhere-build-tooling-checksums-update` uses arm64 container and removes checsum entries for amd64 binaries for linuxkit and ipxedust. This changes the script to preserve the checksums of files not present in the OUTPUT_BIN_DIR

Preserve missing binary checksums

---

projects/aws/image-builder/CHECKSUMS
projects/aws/image-builder/README.md
projects/aws/image-builder/builder/builder.go
projects/aws/image-builder/builder/constants.go
projects/aws/image-builder/builder/types.go
projects/aws/image-builder/cmd/build.go
projects/kubernetes-sigs/image-builder/Makefile
projects/kubernetes-sigs/image-builder/patches/0001-OVA-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0002-EKS-D-support-and-changes.patch
projects/kubernetes-sigs/image-builder/patches/0003-Snow-AMI-support.patch
projects/kubernetes-sigs/image-builder/patches/0004-RHEL-support-and-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0005-Nutanix-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0006-adds-retries-and-timeout-to-packer-image-builder.patch
projects/kubernetes-sigs/image-builder/patches/0007-Networking-improvements.patch
projects/kubernetes-sigs/image-builder/patches/0008-Support-and-improvements-for-RHEL-9-EFI.patch
projects/kubernetes-sigs/image-builder/patches/0009-Pin-Packer-Goss-plugin-version-to-3.1.4.patch
projects/kubernetes-sigs/image-builder/patches/0010-Remove-containerd-configuration-for-hosts.toml-paths.patch
projects/kubernetes-sigs/image-builder/patches/0011-Revert-updating-preseed-and-cloud-init-to-use-CD-for.patch
projects/kubernetes-sigs/image-builder/patches/0012-Make-configurable-Nutanix-image-size.patch
projects/kubernetes-sigs/image-builder/patches/0013-Add-non-EFI-builds-for-RHEL-9-OVA.patch
projects/kubernetes-sigs/image-builder/patches/0014-Allow-setting-releasever-during-yum-update.patch
projects/kubernetes-sigs/image-builder/patches/0015-Ubunutu-2404-iso-url-fix.patch
projects/kubernetes-sigs/image-builder/patches/0016-Vsphere-clone-builder-support.patch

Add support for image-builder CLI to use vsphere-clone builder.
The PR adds make targets for clone build in kubernetes-sigs/image-builder project Makefile to support using vsphere-clone builder, and then add logic in aws/image-builder to use clone build target if using vsphere-clone builder.
We also added one patch to disable firewall service(firewalld on Rhel and ufw on Ubuntu) because if the base template has firewall enabled, it will block certain ports used by kubelet/api-server, or any other services that are deployed to the cluster, this behavior aligns with the iso build produced by image-builder CLI.
The template for base image can be specified in the vsphere json config file:
```
{
"cluster":"<vsphere cluster used for image building>",
"convert_to_template":"false", …
```

Support vsphere-clone builder
